// apps/vtdf-site/src/components/home/TerminalDemo.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import codeGroupSvgData from '../../utils/code-group-svg-data';

const props = withDefaults(
	defineProps<{
		lang?: 'zh_CN' | 'en_US';
	}>(),
	{
		lang: 'zh_CN'
	}
);

type Command = {
	cmd: string;
	output: string;
	delay: number;
	isDevOutput?: boolean;
};

const isZh = computed(() => props.lang === 'zh_CN');
const packageManagers = ['bun', 'npm', 'pnpm', 'yarn'] as const;
type PackageManager = (typeof packageManagers)[number];
const packageManagerLabels: Record<PackageManager, string> = {
	bun: 'Bun',
	npm: 'npm',
	pnpm: 'pnpm',
	yarn: 'Yarn'
};

const getManagerIcon = (manager: PackageManager) => codeGroupSvgData.find((item) => item.name === manager)?.svg || '';

const getCommands = (manager: PackageManager): Command[] => {
	const createCommand = {
		bun: 'bun create any-tdf@latest my-vtdf -f vue',
		npm: 'npm create any-tdf@latest my-vtdf -f vue',
		pnpm: 'pnpm create any-tdf@latest my-vtdf -f vue',
		yarn: 'yarn create any-tdf@latest my-vtdf -f vue'
	};
	const installCommand = { bun: 'bun i', npm: 'npm i', pnpm: 'pnpm i', yarn: 'yarn' };
	const devCommand = { bun: 'bun dev', npm: 'npm run dev', pnpm: 'pnpm dev', yarn: 'yarn dev' };

	return [
		{ cmd: createCommand[manager], output: isZh.value ? '正在创建 VTDF 项目……' : 'Creating VTDF project...', delay: 480 },
		{ cmd: 'cd my-vtdf', output: '', delay: 160 },
		{ cmd: installCommand[manager], output: isZh.value ? '安装依赖中……' : 'Installing dependencies...', delay: 560 },
		{ cmd: devCommand[manager], output: 'http://localhost:5173/', delay: 360, isDevOutput: true }
	];
};

const highlightCommand = (command: string) => {
	const keywords = ['bun', 'npm', 'pnpm', 'yarn', 'cd', 'create', 'install', 'i', 'run', 'dev'];
	return command
		.split(' ')
		.map((part, index) => {
			if (index === 0 || keywords.includes(part)) return `<span class="text-primary dark:text-dark">${part}</span>`;
			if (part.startsWith('any-tdf@') || part === 'vue') return `<span class="text-cyan-600 dark:text-cyan-400">${part}</span>`;
			if (part.startsWith('my-')) return `<span class="text-amber-600 dark:text-amber-400">${part}</span>`;
			return `<span class="text-gray-700 dark:text-gray-300">${part}</span>`;
		})
		.join(' ');
};

const activeManager = ref<PackageManager>('bun');
const currentStep = ref(0);
const currentText = ref('');
const showOutput = ref(false);
const showCursor = ref(true);
const isAnimating = ref(false);
const hasStarted = ref(false);
const completedCommands = ref<Array<Pick<Command, 'cmd' | 'output' | 'isDevOutput'>>>([]);
const commands = computed(() => getCommands(activeManager.value));
let typingTimer: ReturnType<typeof setInterval> | undefined;
let cursorTimer: ReturnType<typeof setInterval> | undefined;
let stepTimer: ReturnType<typeof setTimeout> | undefined;

const stopStepTimers = () => {
	if (typingTimer) clearInterval(typingTimer);
	if (stepTimer) clearTimeout(stepTimer);
};

const typeCommand = (text: string, onComplete: () => void) => {
	let index = 0;
	currentText.value = '';
	showOutput.value = false;
	typingTimer = setInterval(() => {
		if (index < text.length) {
			currentText.value += text[index];
			index += 1;
			return;
		}
		if (typingTimer) clearInterval(typingTimer);
		onComplete();
	}, 42);
};

const nextStep = () => {
	if (currentStep.value >= commands.value.length) {
		isAnimating.value = false;
		return;
	}

	const command = commands.value[currentStep.value];
	typeCommand(command.cmd, () => {
		showOutput.value = true;
		stepTimer = setTimeout(() => {
			completedCommands.value = [...completedCommands.value, command];
			currentStep.value += 1;
			currentText.value = '';
			showOutput.value = false;
			nextStep();
		}, command.delay);
	});
};

const replay = () => {
	stopStepTimers();
	completedCommands.value = [];
	currentStep.value = 0;
	currentText.value = '';
	showOutput.value = false;
	isAnimating.value = true;
	nextStep();
};

const switchManager = (manager: PackageManager) => {
	if (manager === activeManager.value) return;
	activeManager.value = manager;
	replay();
};

let observer: IntersectionObserver | null = null;

onMounted(() => {
	cursorTimer = setInterval(() => (showCursor.value = !showCursor.value), 530);
	observer = new IntersectionObserver(
		(entries) => {
			if (entries[0].isIntersecting && !hasStarted.value) {
				hasStarted.value = true;
				replay();
			}
		},
		{ threshold: 0.25 }
	);
	const section = document.getElementById('terminal-demo');
	if (section) observer.observe(section);
});

onBeforeUnmount(() => {
	stopStepTimers();
	if (cursorTimer) clearInterval(cursorTimer);
	observer?.disconnect();
});
</script>

<template>
	<section id="terminal-demo" class="terminal-demo">
		<div class="terminal-manager-bar">
			<div class="terminal-manager-tabs">
				<button
					v-for="manager in packageManagers"
					:key="manager"
					:class="{ active: activeManager === manager }"
					type="button"
					@click="switchManager(manager)"
				>
					<span class="terminal-manager-icon" aria-hidden="true" v-html="getManagerIcon(manager)"></span>
					<span class="terminal-manager-name">{{ packageManagerLabels[manager] }}</span>
				</button>
			</div>
			<button class="terminal-replay" type="button" :disabled="isAnimating" @click="replay">↻ {{ isZh ? '重播' : 'Replay' }}</button>
		</div>

		<div class="terminal-command-log" aria-live="polite">
			<div v-for="command in completedCommands" :key="command.cmd" class="terminal-command-entry">
				<div class="terminal-command-line"><span>$</span><span v-html="highlightCommand(command.cmd)"></span></div>
				<template v-if="command.output">
					<div v-if="command.isDevOutput" class="terminal-output"><span>READY</span> {{ command.output }}</div>
					<div v-else class="terminal-output">{{ command.output }}</div>
				</template>
			</div>

			<div v-if="currentStep < commands.length" class="terminal-command-entry">
				<div class="terminal-command-line">
					<span>$</span><span v-html="highlightCommand(currentText)"></span
					><span class="terminal-cursor" :class="{ visible: showCursor }"></span>
				</div>
				<div v-if="showOutput && commands[currentStep]?.output" class="terminal-output">{{ commands[currentStep].output }}</div>
			</div>
			<div v-else class="terminal-ready"><span>✓ READY</span><span>http://localhost:5173/</span></div>
		</div>
	</section>
</template>

// apps/rtdf-site/src/components/home/TerminalDemo.tsx
import { useEffect, useRef, useState } from 'react';
import codeGroupSvgData from '../../utils/code-group-svg-data';

type Command = {
	cmd: string;
	output: string;
	delay: number;
	isDevOutput?: boolean;
};

type TerminalDemoProps = {
	lang?: 'zh_CN' | 'en_US';
};

const packageManagers = ['bun', 'npm', 'pnpm', 'yarn'] as const;
type PackageManager = (typeof packageManagers)[number];
const packageManagerLabels: Record<PackageManager, string> = {
	bun: 'Bun',
	npm: 'npm',
	pnpm: 'pnpm',
	yarn: 'Yarn'
};

const getManagerIcon = (manager: PackageManager) => codeGroupSvgData.find((item) => item.name === manager)?.svg || '';

const highlightCommand = (command: string) => {
	const keywords = ['bun', 'npm', 'pnpm', 'yarn', 'cd', 'create', 'install', 'i', 'run', 'dev'];
	return command
		.split(' ')
		.map((part, index) => {
			if (index === 0 || keywords.includes(part)) return `<span class="text-primary dark:text-dark">${part}</span>`;
			if (part.startsWith('any-tdf@') || part === 'react') return `<span class="text-cyan-600 dark:text-cyan-400">${part}</span>`;
			if (part.startsWith('my-')) return `<span class="text-amber-600 dark:text-amber-400">${part}</span>`;
			return `<span class="text-gray-700 dark:text-gray-300">${part}</span>`;
		})
		.join(' ');
};

const TerminalDemo = ({ lang = 'zh_CN' }: TerminalDemoProps) => {
	const isZh = lang === 'zh_CN';

	const getCommands = (manager: PackageManager): Command[] => {
		const createCommand = {
			bun: 'bun create any-tdf@latest my-rtdf -f react',
			npm: 'npm create any-tdf@latest my-rtdf -f react',
			pnpm: 'pnpm create any-tdf@latest my-rtdf -f react',
			yarn: 'yarn create any-tdf@latest my-rtdf -f react'
		};
		const installCommand = { bun: 'bun i', npm: 'npm i', pnpm: 'pnpm i', yarn: 'yarn' };
		const devCommand = { bun: 'bun dev', npm: 'npm run dev', pnpm: 'pnpm dev', yarn: 'yarn dev' };

		return [
			{ cmd: createCommand[manager], output: isZh ? '正在创建 RTDF 项目……' : 'Creating RTDF project...', delay: 480 },
			{ cmd: 'cd my-rtdf', output: '', delay: 160 },
			{ cmd: installCommand[manager], output: isZh ? '安装依赖中……' : 'Installing dependencies...', delay: 560 },
			{ cmd: devCommand[manager], output: 'http://localhost:5173/', delay: 360, isDevOutput: true }
		];
	};

	const [activeManager, setActiveManager] = useState<PackageManager>('bun');
	const [currentStep, setCurrentStep] = useState(0);
	const [currentText, setCurrentText] = useState('');
	const [showOutput, setShowOutput] = useState(false);
	const [showCursor, setShowCursor] = useState(true);
	const [isAnimating, setIsAnimating] = useState(false);
	const [hasStarted, setHasStarted] = useState(false);
	const [completedCommands, setCompletedCommands] = useState<Array<Pick<Command, 'cmd' | 'output' | 'isDevOutput'>>>([]);
	const commands = getCommands(activeManager);

	const typingTimerRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined);
	const cursorTimerRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined);
	const stepTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
	// 用 ref 跟踪最新的步骤状态，避免闭包捕获旧值
	const stateRef = useRef({ currentStep, commands });
	stateRef.current = { currentStep, commands };

	const stopStepTimers = () => {
		if (typingTimerRef.current) clearInterval(typingTimerRef.current);
		if (stepTimerRef.current) clearTimeout(stepTimerRef.current);
	};

	const typeCommand = (text: string, onComplete: () => void) => {
		let index = 0;
		setCurrentText('');
		setShowOutput(false);
		typingTimerRef.current = setInterval(() => {
			if (index < text.length) {
				setCurrentText((prev) => prev + text[index]);
				index += 1;
				return;
			}
			if (typingTimerRef.current) clearInterval(typingTimerRef.current);
			onComplete();
		}, 42);
	};

	const nextStep = () => {
		const { currentStep: step, commands: cmds } = stateRef.current;
		if (step >= cmds.length) {
			setIsAnimating(false);
			return;
		}

		const command = cmds[step];
		typeCommand(command.cmd, () => {
			setShowOutput(true);
			stepTimerRef.current = setTimeout(() => {
				setCompletedCommands((prev) => [...prev, command]);
				setCurrentStep(step + 1);
				stateRef.current.currentStep = step + 1;
				setCurrentText('');
				setShowOutput(false);
				nextStep();
			}, command.delay);
		});
	};

	const replay = () => {
		stopStepTimers();
		setCompletedCommands([]);
		setCurrentStep(0);
		stateRef.current.currentStep = 0;
		setCurrentText('');
		setShowOutput(false);
		setIsAnimating(true);
		nextStep();
	};

	const switchManager = (manager: PackageManager) => {
		if (manager === activeManager) return;
		setActiveManager(manager);
		stateRef.current.commands = getCommands(manager);
		replay();
	};

	useEffect(() => {
		cursorTimerRef.current = setInterval(() => setShowCursor((prev) => !prev), 530);
		const observer = new IntersectionObserver(
			(entries) => {
				if (entries[0].isIntersecting && !hasStarted) {
					setHasStarted(true);
					replay();
				}
			},
			{ threshold: 0.25 }
		);
		const section = document.getElementById('terminal-demo');
		if (section) observer.observe(section);
		return () => {
			observer.disconnect();
			stopStepTimers();
			if (cursorTimerRef.current) clearInterval(cursorTimerRef.current);
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [hasStarted]);

	return (
		<section id="terminal-demo" className="terminal-demo">
			<div className="terminal-manager-bar">
				<div className="terminal-manager-tabs">
					{packageManagers.map((manager) => (
						<button
							key={manager}
							className={activeManager === manager ? 'active' : ''}
							onClick={() => switchManager(manager)}
							type="button"
						>
							<span className="terminal-manager-icon" aria-hidden="true" dangerouslySetInnerHTML={{ __html: getManagerIcon(manager) }} />
							<span className="terminal-manager-name">{packageManagerLabels[manager]}</span>
						</button>
					))}
				</div>
				<button className="terminal-replay" onClick={replay} disabled={isAnimating} type="button">
					↻ {isZh ? '重播' : 'Replay'}
				</button>
			</div>

			<div className="terminal-command-log" aria-live="polite">
				{completedCommands.map((command) => (
					<div className="terminal-command-entry" key={command.cmd}>
						<div className="terminal-command-line">
							<span>$</span>
							<span dangerouslySetInnerHTML={{ __html: highlightCommand(command.cmd) }} />
						</div>
						{command.output ? (
							command.isDevOutput ? (
								<div className="terminal-output">
									<span>READY</span> {command.output}
								</div>
							) : (
								<div className="terminal-output">{command.output}</div>
							)
						) : null}
					</div>
				))}

				{currentStep < commands.length ? (
					<div className="terminal-command-entry">
						<div className="terminal-command-line">
							<span>$</span>
							<span dangerouslySetInnerHTML={{ __html: highlightCommand(currentText) }} />
							<span className={`terminal-cursor${showCursor ? ' visible' : ''}`}></span>
						</div>
						{showOutput && commands[currentStep]?.output ? <div className="terminal-output">{commands[currentStep].output}</div> : null}
					</div>
				) : (
					<div className="terminal-ready">
						<span>✓ READY</span>
						<span>http://localhost:5173/</span>
					</div>
				)}
			</div>
		</section>
	);
};

export default TerminalDemo;
