// packages/vtdf/src/lib/components/Badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { BadgeProps } from '../types';
import { resolveBadgeDerived, resolveBadgeStateOptions } from '@any-tdf/common/derived/badge';

const props = withDefaults(defineProps<BadgeProps>(), {
	text: '',
	radius: '',
	isLeft: false,
	isShow: true,
	offsetY: 0,
	offsetX: 0,
	isInner: false,
	injClass: ''
});

// 公共派生层只接收 Badge 状态，组件层只负责模板绑定。
// The shared derived layer receives Badge state; the component layer only binds the template.
const badgeState = computed(() =>
	resolveBadgeDerived(
		resolveBadgeStateOptions({
			props: {
				text: props.text,
				radius: props.radius,
				isLeft: props.isLeft,
				isShow: props.isShow,
				offsetY: props.offsetY,
				offsetX: props.offsetX,
				isInner: props.isInner,
				injClass: props.injClass
			}
		})
	)
);
</script>

<template>
	<div v-if="badgeState.isInner" :class="badgeState.classes.innerClass" :style="badgeState.innerStyleValue">
		{{ text }}
	</div>
	<div v-else :class="badgeState.classes.wrapperClass">
		<slot />
		<div :class="badgeState.classes.outerClass" :style="badgeState.outerStyleValue">
			{{ text }}
		</div>
	</div>
</template>

// packages/rtdf/src/lib/components/badge/index.tsx
import type { BadgeProps } from '../../types';
import { resolveBadgeDerived, resolveBadgeStateOptions } from '@any-tdf/common/derived/badge';

const Badge: React.FC<BadgeProps> = ({
	text = '',
	radius = '',
	isLeft = false,
	isShow = true,
	offsetY = 0,
	offsetX = 0,
	isInner = false,
	injClass = '',
	children
}) => {
	// 公共派生层只接收 Badge 状态，组件层只负责 JSX 绑定。
	// The shared derived layer receives Badge state; the component layer only binds JSX.
	const badgeState = resolveBadgeDerived(
		resolveBadgeStateOptions({
			props: { text, radius, isLeft, isShow, offsetY, offsetX, isInner, injClass }
		})
	);

	if (badgeState.isInner) {
		return (
			<div className={badgeState.classes.innerClass} style={badgeState.innerStyleValue}>
				{text}
			</div>
		);
	}

	return (
		<div className={badgeState.classes.wrapperClass}>
			{children}
			<div className={badgeState.classes.outerClass} style={badgeState.outerStyleValue}>
				{text}
			</div>
		</div>
	);
};

export default Badge;
