// packages/stdf/src/lib/components/pagination/SecondPageNext.svelte
<script lang="ts">
	import Page from './Page.svelte';
	import type { SmallAreaRadius } from '../../types/index.js';
	import { resolveHiddenScrollbarCss } from '@any-tdf/common/derived/helpers';
	import { resolvePaginationSecondPageDerived, resolvePaginationSecondPageStateOptions } from '@any-tdf/common/derived/pagination';

	type Props = {
		pageCol: number;
		Pages: number[];
		maxShowPage: number;
		radius: SmallAreaRadius;
		type: 'border' | 'block' | 'bold';
		bg: 'white' | 'surface' | 'gray' | 'theme';
		onclickItem: (index: number) => void;
	};
	let { pageCol = 3, Pages = [], maxShowPage = 9, radius = 'md', type = 'bold', bg = 'white', onclickItem }: Props = $props();
	// 公共派生层统一二级页码浮层结果，组件层只渲染按钮与绑定点击。
	// Common derivation unifies second-level page popover output; the component layer only renders buttons and binds clicks.
	let secondPageState = $derived(resolvePaginationSecondPageDerived(resolvePaginationSecondPageStateOptions({
		props: { bg, dropShadow: false, maxShowPage, pageCol, pages: Pages, placement: 'next' }
	})));
	const css = resolveHiddenScrollbarCss({ selector: '.second-page-contents' });

</script>

<svelte:head>
	<style>
		{css}
	</style>
</svelte:head>

{#if secondPageState.visible}
	<div
		class={secondPageState.containerClass}
		style={secondPageState.containerStyleString}
	>
		<div
			class={secondPageState.contentClass}
			style={secondPageState.gridStyleString}
		>
			{#each Pages as item, index (index)}
				<Page onclick={() => onclickItem && onclickItem(item)} {type} {radius}>{item}</Page>
			{/each}
		</div>
		<div class={secondPageState.arrowClass}></div>
	</div>
{/if}

// packages/rtdf/src/lib/components/pagination/secondPageNext.tsx
import type { SmallAreaRadius } from '../../types';
import Page from './page';
import { resolvePaginationSecondPageDerived, resolvePaginationSecondPageStateOptions } from '@any-tdf/common/derived/pagination';

type SecondPageProps = {
	pageCol?: number;
	pages?: number[];
	maxShowPage?: number;
	radius?: SmallAreaRadius;
	type?: 'border' | 'block' | 'bold';
	bg?: 'white' | 'surface' | 'gray' | 'theme';
	onClickItem?: (index: number) => void;
};

const SecondPageNext: React.FC<SecondPageProps> = ({
	pageCol = 3,
	pages = [],
	maxShowPage = 9,
	radius = 'md',
	type = 'bold',
	bg = 'white',
	onClickItem
}) => {
	// 公共派生层统一二级页码浮层结果，组件层只渲染按钮与绑定点击。
	// Common derivation unifies second-level page popover output; the component layer only renders buttons and binds clicks.
	const secondPageState = resolvePaginationSecondPageDerived(
		resolvePaginationSecondPageStateOptions({
			props: { bg, maxShowPage, pageCol, pages, placement: 'next' }
		})
	);
	if (!secondPageState.visible) return null;

	return (
		<div className={secondPageState.containerClass} style={secondPageState.containerStyleValue}>
			<div className={secondPageState.contentClass} style={secondPageState.gridStyleValue}>
				{pages.map((item) => (
					<Page key={item} type={type} radius={radius} onClick={() => onClickItem?.(item)}>
						{item}
					</Page>
				))}
			</div>
			<div className={secondPageState.arrowClass}></div>
		</div>
	);
};

export default SecondPageNext;
