// packages/rtdf/src/lib/components/loading/loadings/oneColor/1_12.tsx
import type { FC } from 'react';
import { parseStyle } from '../../../utils/style';
import {
	resolveLoadingLayoutClass,
	resolveLoadingOneColorClassState,
	loadingClimbingDotStepIndexes,
	resolveLoadingClimbingDotBallStyle,
	resolveLoadingClimbingDotCss,
	resolveLoadingClimbingDotStepRootClass,
	resolveLoadingClimbingDotStepStyle,
	resolveLoadingRoundedElementClass
} from '@any-tdf/common/derived/loading';

type Props = {
	theme?: boolean;
	inverse?: boolean;
	size?: string;
	customColor?: string[];
	speed?: number;
};

const Loading1_12: FC<Props> = ({ theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = 1 }) => {
	const loadingClassState = resolveLoadingOneColorClassState({ theme, inverse });

	const css = resolveLoadingClimbingDotCss({ scope: 'rtdf_loading_1_12' });

	return (
		<>
			{css ? <style>{css}</style> : null}
			<div className="rtdf_loading_1_12">
				<div className={resolveLoadingLayoutClass({ kind: 'loadingRelativeBox', size })}>
					<div
						className={resolveLoadingRoundedElementClass({
							bgClass: loadingClassState.bgClass,
							className: 'absolute ball',
							size: 'none'
						})}
						style={parseStyle(resolveLoadingClimbingDotBallStyle({ color: customColor[0], speed }))}
					></div>
					{loadingClimbingDotStepIndexes.map((stepIndex) => (
						<div
							key={stepIndex}
							className={resolveLoadingClimbingDotStepRootClass({
								stepIndex,
								bgClass: loadingClassState.bgClass
							})}
							style={parseStyle(resolveLoadingClimbingDotStepStyle({ color: customColor[0], speed }))}
						></div>
					))}
				</div>
			</div>
		</>
	);
};

export default Loading1_12;

// packages/stdf/src/lib/components/loading/loadings/oneColor/1_12.svelte
<script lang="ts">
	import { resolveLoadingLayoutClass, resolveLoadingOneColorClassState, loadingClimbingDotStepIndexes, resolveLoadingClimbingDotBallStyle, resolveLoadingClimbingDotCss, resolveLoadingClimbingDotStepRootClass, resolveLoadingClimbingDotStepStyle, resolveLoadingRoundedElementClass } from '@any-tdf/common/derived/loading';
	type Props = { theme?: boolean; inverse?: boolean; size?: string; customColor?: any[]; speed?: number };
	let { theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = $bindable(1) }: Props = $props();

	const loadingClassState = $derived(resolveLoadingOneColorClassState({ theme, inverse }));

	const css = resolveLoadingClimbingDotCss({ scope: 'stdf_loading_1_12' });
</script>

<svelte:head>
	{@html `<style>${css}</style>`}
</svelte:head>

<div class="stdf_loading_1_12">
	<div class={resolveLoadingLayoutClass({ kind: 'loadingRelativeBox', size })}>
		<div
			class={resolveLoadingRoundedElementClass({ bgClass: loadingClassState.bgClass, className: 'absolute ball', size: 'none' })}
			style={resolveLoadingClimbingDotBallStyle({ color: customColor[0], speed })}
		></div>
		{#each loadingClimbingDotStepIndexes as stepIndex (stepIndex)}
			<div
				class={resolveLoadingClimbingDotStepRootClass({ stepIndex, bgClass: loadingClassState.bgClass })}
				style={resolveLoadingClimbingDotStepStyle({ color: customColor[0], speed })}
			></div>
		{/each}
	</div>
</div>
