// packages/rtdf/src/lib/components/loading/loadings/oneColor/1_53.tsx
import type { FC } from 'react';
import { Fragment } from 'react';
import { parseStyle } from '../../../utils/style';
import {
	resolveLoadingLayoutClass,
	loadingRotatingLineFrames,
	resolveLoadingLineRotateCss,
	resolveLoadingRotatingLineClass,
	resolveLoadingRotatingLineStyle,
	resolveLoadingOneColorClassState
} from '@any-tdf/common/derived/loading';

type Props = {
	theme?: boolean;
	inverse?: boolean;
	size?: string;
	customColor?: string[];
	speed?: number;
};

const Loading1_53: FC<Props> = ({ theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = 1 }) => {
	const loadingClassState = resolveLoadingOneColorClassState({ theme, inverse });

	const css = resolveLoadingLineRotateCss({ scope: 'rtdf_loading_1_53' });

	return (
		<>
			{css ? <style>{css}</style> : null}
			<div className="rtdf_loading_1_53">
				<div className={resolveLoadingLayoutClass({ kind: 'relativeCenter', size })}>
					{loadingRotatingLineFrames.map((item, i) => (
						<Fragment key={i}>
							<div
								className={resolveLoadingRotatingLineClass(loadingClassState.bgClass)}
								style={parseStyle(
									resolveLoadingRotatingLineStyle({
										color: customColor[0],
										frame: item,
										speed,
										top: '50%'
									})
								)}
							></div>
						</Fragment>
					))}
				</div>
			</div>
		</>
	);
};

export default Loading1_53;

// packages/stdf/src/lib/components/loading/loadings/oneColor/1_53.svelte
<script lang="ts">
	import { resolveLoadingLayoutClass, loadingRotatingLineFrames, resolveLoadingLineRotateCss, resolveLoadingRotatingLineClass, resolveLoadingRotatingLineStyle, resolveLoadingOneColorClassState } from '@any-tdf/common/derived/loading';
	type Props = { theme?: boolean; inverse?: boolean; size?: string; customColor?: any[]; speed?: number };
	let { theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = $bindable(1) }: Props = $props();

	const loadingClassState = $derived(resolveLoadingOneColorClassState({ theme, inverse }));
	const css = resolveLoadingLineRotateCss({ scope: 'stdf_loading_1_53' });
</script>

<svelte:head>
	{@html `<style>${css}</style>`}
</svelte:head>

<div class="stdf_loading_1_53">
	<div class={resolveLoadingLayoutClass({ kind: 'relativeCenter', size })}>
		{#each loadingRotatingLineFrames as item, i (i)}
			<div
				class={resolveLoadingRotatingLineClass(loadingClassState.bgClass)}
				style={resolveLoadingRotatingLineStyle({ color: customColor[0], frame: item, speed, top: '50%' })}
			></div>
		{/each}
	</div>
</div>
