// packages/rtdf/src/lib/components/loading/loadings/oneColor/1_8.tsx
import type { FC } from 'react';
import { parseStyle } from '../../../utils/style';
import {
	resolveLoadingLayoutClass,
	resolveLoadingRoundDotClass,
	resolveLoadingRotateScaleCss,
	resolveLoadingOneColorClassState,
	resolveLoadingBaseAnimationStyle,
	resolveLoadingOneColorBackgroundStyle
} from '@any-tdf/common/derived/loading';

type Props = {
	theme?: boolean;
	inverse?: boolean;
	size?: string;
	customColor?: string[];
	speed?: number;
};

const Loading1_8: FC<Props> = ({ theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = 1 }) => {
	const loadingClassState = resolveLoadingOneColorClassState({ theme, inverse });

	const css = resolveLoadingRotateScaleCss({ scope: 'rtdf_loading_1_8' });

	return (
		<>
			{css ? <style>{css}</style> : null}
			<div className="rtdf_loading_1_8">
				<div
					className={resolveLoadingLayoutClass({ kind: 'loadingFlexBetween', size })}
					style={parseStyle(resolveLoadingBaseAnimationStyle({ speed }))}
				>
					<div
						className={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })}
						style={parseStyle(resolveLoadingOneColorBackgroundStyle({ customColor }))}
					></div>
					<div
						className={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })}
						style={parseStyle(resolveLoadingOneColorBackgroundStyle({ customColor }))}
					></div>
					<div
						className={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })}
						style={parseStyle(resolveLoadingOneColorBackgroundStyle({ customColor }))}
					></div>
				</div>
			</div>
		</>
	);
};

export default Loading1_8;

// packages/stdf/src/lib/components/loading/loadings/oneColor/1_8.svelte
<script lang="ts">
	import { resolveLoadingLayoutClass, resolveLoadingRoundDotClass, resolveLoadingRotateScaleCss, resolveLoadingOneColorClassState, resolveLoadingBaseAnimationStyle, resolveLoadingOneColorBackgroundStyle } from '@any-tdf/common/derived/loading';
	type Props = { theme?: boolean; inverse?: boolean; size?: string; customColor?: string[]; speed?: number };

	let { theme = false, inverse = false, size = 'w-8 h-8', customColor = [], speed = $bindable(1) }: Props = $props();

	const loadingClassState = $derived(resolveLoadingOneColorClassState({ theme, inverse }));
	const css = resolveLoadingRotateScaleCss({ scope: 'stdf_loading_1_8' });
</script>

<svelte:head>
	{@html `<style>${css}</style>`}
</svelte:head>

<div class="stdf_loading_1_8">
	<div
		class={resolveLoadingLayoutClass({ kind: 'loadingFlexBetween', size })}
		style={resolveLoadingBaseAnimationStyle({ speed })}
	>
		<div class={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })} style={resolveLoadingOneColorBackgroundStyle({ customColor })}></div>
		<div class={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })} style={resolveLoadingOneColorBackgroundStyle({ customColor })}></div>
		<div class={resolveLoadingRoundDotClass({ bgClass: loadingClassState.bgClass })} style={resolveLoadingOneColorBackgroundStyle({ customColor })}></div>
	</div>
</div>
