// apps/vtdf-site/src/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, watch } from 'vue';
import {
	getSiteNavigationState,
	getSitePage,
	legacyGeneratorPath,
	normalizeSiteLanguage,
	resolveSiteLanguage,
	resolveSiteThemeName,
	sitePaths
} from '@any-tdf/site-common/site';
import { switchTheme } from 'vtdf/theme';
import Header from './components/Header.vue';
import CmdK from './components/CmdK.vue';
import Fund from './components/Fund.vue';
import HomePage from './pages/Home.vue';
import ComponentsPage from './pages/components/ComponentsPage.vue';
import GuideLayout from './pages/guide/GuideLayout.vue';
import GeneratorPage from './pages/generator/GeneratorPage.vue';
import NotFound from './pages/NotFound.vue';
import { appState, syncRouteState } from './store/appStore';
import { delParamsUrl } from './utils/index';

const isZh = computed(() => appState.lang === 'zh_CN');

const updateFavicon = (mode: 'light' | 'dark') => {
	document
		.querySelector<HTMLLinkElement>('[data-theme-favicon]')
		?.setAttribute('href', mode === 'dark' ? '/favicon_black.ico' : '/favicon.ico');
};

// 是否显示左侧导航（路由改变时更新）
const showLeftNav = computed(() => getSiteNavigationState(appState.pathname).showLeftNav);
const currentPage = computed(() => getSitePage(appState.pathname));

const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
const handleThemeChange = (event: MediaQueryListEvent) => {
	appState.sysTheme = event.matches ? 'dark' : 'light';
};
const handleRouteChange = () => {
	syncRouteState();
};

// 同步 URL 中的 lang 参数到 localStorage，并从 URL 中移除
const syncLangFromUrl = () => {
	const url = new URL(window.location.href);
	const langParam = url.searchParams.get('lang');
	const urlLanguage = normalizeSiteLanguage(langParam);
	if (urlLanguage) {
		appState.lang = urlLanguage;
		localStorage.setItem('lang', urlLanguage);
		url.searchParams.delete('lang');
		window.history.replaceState({}, '', url.toString());
		syncRouteState();
		return;
	}
	appState.lang = resolveSiteLanguage(null, localStorage.getItem('lang'), navigator.language);
	localStorage.setItem('lang', appState.lang);
};

// 同步主题色：iframe 内优先取 URL theme 参数，否则取本地存储
const syncThemeFromUrl = () => {
	const urlParams = new URLSearchParams(window.location.search);
	const themeParam = urlParams.get('theme');
	const isIframe = window.self !== window.top;
	const nextTheme = resolveSiteThemeName(themeParam, localStorage.getItem('theme_color'), isIframe);
	if (localStorage.getItem('theme_color') !== nextTheme) {
		localStorage.setItem('theme_color', nextTheme);
	}
	appState.currentColor = nextTheme;
};

// 根据 params 判断当前 URL 是否含有 fund 参数，如果有则显示赞赏弹窗
const syncFundFromUrl = () => {
	const urlParams = new URLSearchParams(window.location.search);
	if (urlParams.has('fund')) {
		appState.isShowFund = true;
		// 去除 URL 中的 fund 参数
		setTimeout(() => {
			window.history.replaceState({}, '', delParamsUrl(window.location.href, 'fund'));
			syncRouteState();
		}, 10);
	}
};

watch(
	() => appState.currentColor,
	(color) => {
		switchTheme(color);
		localStorage.setItem('theme_color', color);
	},
	{ immediate: true }
);

watch(
	() => [appState.themeMode, appState.sysTheme] as const,
	([themeMode, sysTheme]) => {
		const currentThemeMode = themeMode === 'auto' ? sysTheme : themeMode;
		appState.currentThemeMode = currentThemeMode;
		document.documentElement.setAttribute('data-mode', currentThemeMode);
		updateFavicon(currentThemeMode);
		localStorage.setItem('theme', themeMode);
	},
	{ immediate: true }
);

watch(
	isZh,
	(zh) => {
		document.title = zh ? 'VTDF - 移动 web 组件库' : 'VTDF - Mobile web component library';
	},
	{ immediate: true }
);

onMounted(() => {
	if (appState.pathname === legacyGeneratorPath) {
		window.history.replaceState({}, '', `${sitePaths.generator}${appState.search}`);
		syncRouteState();
	}
	syncLangFromUrl();
	syncThemeFromUrl();
	syncFundFromUrl();

	mediaQuery.addEventListener('change', handleThemeChange);
	window.addEventListener('popstate', handleRouteChange);
});

onBeforeUnmount(() => {
	mediaQuery.removeEventListener('change', handleThemeChange);
	window.removeEventListener('popstate', handleRouteChange);
});
</script>

<template>
	<main class="site-app relative min-h-screen text-left antialiased">
		<Header :show-left-nav="showLeftNav" />
		<HomePage v-if="currentPage === 'home'" />
		<GeneratorPage v-else-if="currentPage === 'generator'" />
		<GuideLayout v-else-if="currentPage === 'guide'" />
		<ComponentsPage v-else-if="currentPage === 'components'" />
		<NotFound v-else />
		<CmdK />
		<!-- 赞赏 -->
		<Fund v-if="appState.isShowFund" />
	</main>
</template>

// apps/rtdf-site/src/App.tsx
import { useEffect, useMemo, useState } from 'react';
import { Navigate, Route, Routes, useLocation } from 'react-router-dom';
import {
	getSiteNavigationState,
	legacyGeneratorPath,
	normalizeSiteLanguage,
	normalizeSiteThemeMode,
	resolveSiteLanguage,
	resolveSiteThemeName,
	sitePaths
} from '@any-tdf/site-common/site';
import { switchMode, switchTheme } from 'rtdf/theme';
import Header from './components/Header';
import CmdK from './components/CmdK';
import Fund from './components/Fund';
import HomePage from './pages/Home';
import GuideLayout from './pages/guide/GuideLayout';
import ComponentsPage from './pages/components/ComponentsPage';
import GeneratorPage from './pages/generator/GeneratorPage';
import NotFound from './pages/NotFound';
import { AppContextProvider, type LangType, type ThemeMode } from './store/appStore';
import { delParamsUrl } from './utils';

const getStoredLang = (): LangType => {
	return resolveSiteLanguage(null, localStorage.getItem('lang'), navigator.language);
};

const getStoredThemeMode = (): ThemeMode => {
	return normalizeSiteThemeMode(localStorage.getItem('theme'));
};

const updateFavicon = (mode: 'light' | 'dark') => {
	document
		.querySelector<HTMLLinkElement>('[data-theme-favicon]')
		?.setAttribute('href', mode === 'dark' ? '/favicon_black.ico' : '/favicon.ico');
};

function App() {
	const location = useLocation();
	const [lang, setLang] = useState<LangType>(getStoredLang());
	const [isShowNav, setIsShowNav] = useState(false);
	const [isCmdK, setIsCmdK] = useState(false);
	const [isShowFund, setIsShowFund] = useState(false);
	const [showThemeSwitch, setShowThemeSwitch] = useState(false);
	const [currentColor, setCurrentColor] = useState(resolveSiteThemeName(null, localStorage.getItem('theme_color'), false));
	const [themeMode, setThemeMode] = useState<ThemeMode>(getStoredThemeMode());
	const [sysTheme, setSysTheme] = useState<'light' | 'dark'>(window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
	const [isWideScreen, setIsWideScreen] = useState(localStorage.getItem('isFull') === 'full');

	const showLeftNav = useMemo(() => {
		return getSiteNavigationState(location.pathname).showLeftNav;
	}, [location.pathname]);

	// 路由改变时，更新页面标题（首页由 Home 页自行设置）
	useEffect(() => {
		if (location.pathname === '/') return;
		const isZh = lang === 'zh_CN';
		document.title = `RTDF - ${isZh ? '移动 web 组件库' : 'Mobile web component library'}`;
	}, [lang, location.pathname]);

	useEffect(() => {
		const urlParams = new URLSearchParams(window.location.search);
		const themeParam = urlParams.get('theme');
		const isIframe = window.self !== window.top;
		const nextTheme = resolveSiteThemeName(themeParam, localStorage.getItem('theme_color'), isIframe);
		if (isIframe && themeParam) {
			localStorage.setItem('theme_color', nextTheme);
		}
		setCurrentColor(nextTheme);
	}, [location.search]);

	useEffect(() => {
		switchTheme(currentColor);
		localStorage.setItem('theme_color', currentColor);
	}, [currentColor]);

	useEffect(() => {
		const mql = window.matchMedia('(prefers-color-scheme: dark)');
		const updateSysTheme = (isDark: boolean) => {
			setSysTheme(isDark ? 'dark' : 'light');
			if (themeMode === 'auto') {
				switchMode(isDark ? 'dark' : 'primary');
			}
		};
		updateSysTheme(mql.matches);
		const handler = (event: MediaQueryListEvent) => updateSysTheme(event.matches);
		mql.addEventListener('change', handler);
		return () => mql.removeEventListener('change', handler);
	}, [themeMode]);

	useEffect(() => {
		const resolvedThemeMode = themeMode === 'auto' ? sysTheme : themeMode;
		switchMode(resolvedThemeMode === 'dark' ? 'dark' : 'primary');
		updateFavicon(resolvedThemeMode);
		localStorage.setItem('theme', themeMode);
	}, [sysTheme, themeMode]);

	useEffect(() => {
		const urlParams = new URLSearchParams(window.location.search);
		const langParam = urlParams.get('lang');
		const urlLanguage = normalizeSiteLanguage(langParam);
		if (urlLanguage) {
			localStorage.setItem('lang', urlLanguage);
			setLang(urlLanguage);
			const nextUrl = new URL(window.location.href);
			nextUrl.searchParams.delete('lang');
			setTimeout(() => {
				window.history.replaceState({}, '', nextUrl.toString());
			}, 10);
			return;
		}
		const nextLanguage = resolveSiteLanguage(null, localStorage.getItem('lang'), navigator.language);
		localStorage.setItem('lang', nextLanguage);
		setLang(nextLanguage);
	}, [location.search]);

	// 根据 params 判断当前 URL 是否含有 fund 参数，如果有则显示赞赏弹窗
	useEffect(() => {
		const urlParams = new URLSearchParams(window.location.search);
		if (urlParams.has('fund')) {
			setIsShowFund(true);
			setTimeout(() => {
				window.history.replaceState({}, '', delParamsUrl(window.location.href, 'fund'));
			}, 10);
		}
	}, [location.search]);

	const contextValue = useMemo(
		() => ({
			lang,
			setLang,
			isShowNav,
			setIsShowNav,
			isCmdK,
			setIsCmdK,
			isShowFund,
			setIsShowFund,
			showThemeSwitch,
			setShowThemeSwitch,
			currentColor,
			setCurrentColor,
			themeMode,
			setThemeMode,
			sysTheme,
			setSysTheme,
			isWideScreen,
			setIsWideScreen
		}),
		[lang, isShowNav, isCmdK, isShowFund, showThemeSwitch, currentColor, themeMode, sysTheme, isWideScreen]
	);

	return (
		<AppContextProvider value={contextValue}>
			<main className="site-app relative min-h-screen text-left antialiased">
				<Header showLeftNav={showLeftNav} onclickCmdK={() => setIsCmdK(true)} />
				<Routes>
					<Route path="/" element={<HomePage />} />
					<Route path={legacyGeneratorPath} element={<Navigate to={sitePaths.generator} replace />} />
					<Route path="/guide/*" element={<GuideLayout />} />
					<Route path={sitePaths.generator} element={<GeneratorPage />} />
					<Route path="/components" element={<ComponentsPage />} />
					<Route path="*" element={<NotFound />} />
				</Routes>
				<CmdK />
				{/* 赞赏 */}
				{isShowFund ? <Fund /> : null}
			</main>
		</AppContextProvider>
	);
}

export default App;
