// packages/vtdf/src/lib/components/ImageList.vue
<script setup lang="ts">
import { computed, defineComponent, h, onBeforeUnmount, ref, watch, type PropType } from 'vue';
import {
	appendImageListItems,
	resolveImageListAddFilesFlow,
	resolveImageListDeleteFlow,
	resolveImageListDerived,
	resolveImageListInitialItems,
	resolveImageListItemFromFile,
	resolveImageListItemId,
	resolveImageListMutationAction,
	resolveImageListPreviewCurrent,
	resolveImageListPreviewCloseAction,
	resolveImageListPreviewFlow,
	resolveImageListPreviewKeyboardFlow
} from '@any-tdf/common/derived/imageList';
import { refreshSvg } from '@any-tdf/common/svg/common';
import type { ImageListItemProps, ImageListProps, LoadingProps, VueNode } from '../types';
import { zh_CN, type LangProps } from '../lang';
import { useConfig } from './adapter/config';
import Icon from './Icon.vue';
import ImagePreview from './ImagePreview.vue';
import Loading from './Loading.vue';
import SvgIcon from './SvgIcon.vue';

type ImageListComponentProps = Omit<ImageListProps, 'uploadChild' | 'itemChild' | 'statusChild'> & {
	uploadChild?: () => VueNode;
	itemChild?: (item: ImageListItemProps, index: number) => VueNode;
	statusChild?: (item: ImageListItemProps) => VueNode;
};

const RenderNode = defineComponent({
	name: 'RenderNode',
	props: {
		node: {
			type: null as unknown as PropType<VueNode>,
			default: null
		}
	},
	setup: (renderProps) => () => renderProps.node ?? null
});

const props = withDefaults(defineProps<ImageListComponentProps>(), {
	value: () => [],
	columns: 4,
	max: 9,
	maxSize: 10,
	accept: 'image/*',
	multiple: true,
	disabled: false,
	readonly: false,
	deletable: true,
	previewable: true,
	gap: '2',
	radius: '',
	aspectRatio: () => [1, 1],
	uploadText: '',
	loading: () => ({}),
	icon: () => ({}),
	deleteIcon: () => ({}),
	injClass: '',
	itemInjClass: ''
});

const emit = defineEmits<{
	(event: 'update:value', value: ImageListItemProps[]): void;
	(event: 'add', files: File[]): void;
	(event: 'delete', item: ImageListItemProps, index: number): void;
	(event: 'retry', item: ImageListItemProps, index: number): void;
	(event: 'preview', item: ImageListItemProps, index: number): void;
	(event: 'exceed', files: File[], max: number): void;
	(event: 'oversized', file: File, maxSize: number): void;
	(event: 'clickUpload'): void;
}>();

const config = useConfig();
const value = ref<ImageListItemProps[]>(resolveImageListInitialItems(props.value));
const previewVisible = ref(false);
const previewCurrent = ref(0);
const createdUrls = new Set<string>();

const imageListLang = computed(() => (config.locale.imageList || zh_CN.imageList) as NonNullable<LangProps['imageList']>);

// 输入组件状态，返回框架无关的 class、默认图标、预览和上传项视图派生结果。
// Receive component state and return framework-agnostic classes, default icons, preview data and item view derivations.
const imageListState = computed(() =>
	resolveImageListDerived<ImageListItemProps, NonNullable<typeof props.icon>, NonNullable<typeof props.deleteIcon>, LoadingProps>({
		items: value.value,
		columns: props.columns,
		gap: props.gap,
		radius: props.radius,
		aspectRatio: props.aspectRatio,
		icon: props.icon,
		deleteIcon: props.deleteIcon,
		loading: props.loading,
		injClass: props.injClass,
		itemInjClass: props.itemInjClass,
		max: props.max,
		readonly: props.readonly,
		disabled: props.disabled,
		previewable: props.previewable,
		useItemIdAsFallbackAlt: true,
		uploadFailedText: imageListLang.value.uploadFailedText,
		pendingText: imageListLang.value.pendingText
	})
);

const syncValue = (nextValue: ImageListItemProps[]) => {
	value.value = nextValue;
	emit('update:value', nextValue);
};

const generateId = () => resolveImageListItemId({ timestamp: Date.now(), random: Math.random() });

const createItemFromFile = (file: File): ImageListItemProps => {
	const url = URL.createObjectURL(file);
	createdUrls.add(url);
	return resolveImageListItemFromFile({ id: generateId(), file, url });
};

const emitAdd = (files: File[]) => {
	emit('add', files);
};

const emitDelete = (item: ImageListItemProps, index: number) => {
	emit('delete', item, index);
};

const emitRetry = (item: ImageListItemProps, index: number) => {
	emit('retry', item, index);
};

const emitPreview = (item: ImageListItemProps, index: number) => {
	emit('preview', item, index);
};

const emitExceed = (files: File[], max: number) => {
	emit('exceed', files, max);
};

const emitOversized = (file: File, maxSize: number) => {
	emit('oversized', file, maxSize);
};

const addFiles = (files: File[]) => {
	const flow = resolveImageListAddFilesFlow({
		disabled: props.disabled,
		readonly: props.readonly,
		files,
		currentLength: value.value.length,
		max: props.max,
		maxSize: props.maxSize
	});
	if (!flow.shouldAddFiles) return;
	if (flow.exceeded) {
		emitExceed(files, props.max);
	}
	flow.oversizedFiles.forEach((file) => emitOversized(file, props.maxSize));
	const validFiles = flow.validFiles;

	if (validFiles.length === 0) return;
	syncValue(appendImageListItems(value.value, validFiles.map(createItemFromFile)));
	emitAdd(validFiles);
};

const handleUploadClick = () => {
	const action = resolveImageListMutationAction({
		disabled: props.disabled,
		readonly: props.readonly
	});
	if (!action.shouldMutate) return;
	emit('clickUpload');
};

const handleDelete = (item: ImageListItemProps, index: number) => {
	const flow = resolveImageListDeleteFlow({
		disabled: props.disabled,
		readonly: props.readonly,
		items: value.value,
		item,
		index
	});
	if (!flow.shouldDelete) return;
	if (flow.shouldRevokeUrl && item.url) {
		URL.revokeObjectURL(item.url);
		createdUrls.delete(item.url);
	}
	syncValue(flow.nextItems);
	emitDelete(item, index);
};

const handleRetry = (item: ImageListItemProps, index: number) => {
	const action = resolveImageListMutationAction({
		disabled: props.disabled,
		readonly: props.readonly
	});
	if (!action.shouldMutate) return;
	emitRetry(item, index);
};

const handlePreview = (item: ImageListItemProps, index: number) => {
	const flow = resolveImageListPreviewFlow({
		items: value.value,
		itemId: item.id,
		previewable: props.previewable,
		url: item.url,
		disabled: props.disabled
	});
	if (!flow.shouldOpen) return;
	previewCurrent.value = flow.nextPreviewIndex;
	previewVisible.value = flow.nextPreviewVisible;
	if (flow.shouldEmitPreview) emitPreview(item, index);
};

const handlePreviewClose = () => {
	const action = resolveImageListPreviewCloseAction();
	if (action.shouldClose) previewVisible.value = action.nextPreviewVisible;
};

const handlePreviewKeyDown = (event: KeyboardEvent, item: ImageListItemProps, index: number) => {
	const flow = resolveImageListPreviewKeyboardFlow({
		key: event.key,
		items: value.value,
		itemId: item.id,
		previewable: props.previewable,
		url: item.url,
		disabled: props.disabled
	});
	if (flow.shouldPreventDefault) {
		event.preventDefault();
	}
	if (flow.shouldOpen) {
		previewCurrent.value = flow.nextPreviewIndex;
		previewVisible.value = flow.nextPreviewVisible;
		if (flow.shouldEmitPreview) emitPreview(item, index);
	}
};

watch(
	() => props.value,
	(nextValue) => {
		value.value = resolveImageListInitialItems(nextValue);
	},
	{ deep: true }
);

onBeforeUnmount(() => {
	createdUrls.forEach((url) => URL.revokeObjectURL(url));
	createdUrls.clear();
});

defineExpose({
	addFiles
});
</script>

<template>
	<div :class="imageListState.rootClass">
		<div
			v-for="itemViewState in imageListState.itemViewStates"
			:key="itemViewState.item.id"
			:class="imageListState.itemClass"
			:style="imageListState.aspectRatioStyleValue"
		>
			<slot v-if="$slots.item" name="item" :item="itemViewState.item" :index="itemViewState.index" />
			<RenderNode v-else-if="itemChild" :node="itemChild(itemViewState.item, itemViewState.index)" />
			<div
				v-else
				:class="imageListState.previewContainerClass"
				:role="itemViewState.previewAction.shouldPreview ? 'button' : undefined"
				:tabindex="itemViewState.previewAction.shouldPreview ? 0 : undefined"
				@click="handlePreview(itemViewState.item, itemViewState.index)"
				@keydown="handlePreviewKeyDown($event, itemViewState.item, itemViewState.index)"
			>
				<img
					v-if="itemViewState.imageState.showImage"
					:src="itemViewState.imageState.src"
					:alt="itemViewState.imageState.alt"
					:class="imageListState.imageClass"
				/>

				<div v-if="itemViewState.statusState.showOverlay" :class="imageListState.statusOverlayClass">
					<slot v-if="$slots.status" name="status" :item="itemViewState.item" />
					<RenderNode v-else-if="statusChild" :node="statusChild(itemViewState.item)" />
					<template v-else>
						<Loading v-if="itemViewState.statusState.isUploading" v-bind="imageListState.mergedLoading" />
						<button
							v-else-if="itemViewState.statusState.isError"
							type="button"
							:class="imageListState.retryButtonClass"
							@click.stop="handleRetry(itemViewState.item, itemViewState.index)"
						>
							<!-- 公共刷新 SVG 数据在 common 中维护。 / Shared refresh SVG data lives in common. -->
							<SvgIcon :svg="refreshSvg" width="24" height="24" :class-name="imageListState.retryIconClass" />
							<span :class="imageListState.retryMessageClass">{{ itemViewState.statusMessage }}</span>
						</button>
						<span v-else-if="itemViewState.statusState.isPending" :class="imageListState.pendingMessageClass">{{
							itemViewState.statusMessage
						}}</span>
					</template>
				</div>
			</div>

			<button
				v-if="deletable && !readonly && !disabled"
				type="button"
				:class="imageListState.deleteButtonClass"
				@click.stop="handleDelete(itemViewState.item, itemViewState.index)"
			>
				<Icon v-bind="imageListState.mergedDeleteIcon" />
			</button>
		</div>

		<button
			v-if="imageListState.showUploadButton"
			type="button"
			:class="imageListState.uploadClass"
			:style="imageListState.aspectRatioStyleValue"
			:disabled="disabled"
			@click="handleUploadClick"
		>
			<slot v-if="$slots.upload" name="upload" />
			<RenderNode v-else-if="uploadChild" :node="uploadChild()" />
			<template v-else>
				<Icon v-bind="imageListState.mergedIcon" :opacity="0.5" />
				<span v-if="uploadText" :class="imageListState.uploadTextClass">{{ uploadText }}</span>
			</template>
		</button>
	</div>

	<ImagePreview
		:visible="previewVisible"
		:images="imageListState.previewImages"
		:current="resolveImageListPreviewCurrent(previewCurrent)"
		@close="handlePreviewClose"
		@change="(index: number) => (previewCurrent = index)"
	/>
</template>

// packages/rtdf/src/lib/components/imageList/index.tsx
import { forwardRef, useEffect, useImperativeHandle, useState } from 'react';
import type { ImageListItemProps, ImageListProps, LoadingProps } from '../../types';
import { zh_CN, type LangProps } from '../../lang';
import { useConfig } from '../config-provider';
import Icon from '../icon';
import ImagePreview from '../imagePreview';
import Loading from '../loading';
import {
	appendImageListItems,
	resolveImageListAddFilesFlow,
	resolveImageListDeleteFlow,
	resolveImageListDerived,
	resolveImageListInitialItems,
	resolveImageListUploadText,
	resolveImageListItemFromFile,
	resolveImageListItemId,
	resolveImageListMutationAction,
	resolveImageListPreviewCurrent,
	resolveImageListPreviewCloseAction,
	resolveImageListPreviewFlow,
	resolveImageListPreviewKeyboardFlow
} from '@any-tdf/common/derived/imageList';
import { refreshSvg } from '@any-tdf/common/svg/common';
import { SvgIcon } from '../utils/SvgIcon';

export interface ImageListRef {
	addFiles: (files: File[]) => void;
}

const ImageList = forwardRef<ImageListRef, ImageListProps>((props, ref) => {
	const {
		value: valueProp,
		columns = 4,
		max = 9,
		maxSize = 10,
		disabled = false,
		readonly = false,
		deletable = true,
		previewable = true,
		gap = '2',
		radius = '',
		aspectRatio = [1, 1],
		uploadText: uploadTextProp,
		loading,
		icon,
		deleteIcon,
		injClass = '',
		itemInjClass = '',
		uploadChild,
		itemChild,
		statusChild,
		onAdd,
		onDelete,
		onRetry,
		onPreview,
		onExceed,
		onOversized,
		onClickUpload
	} = props;
	const initialValue = resolveImageListInitialItems(valueProp);
	const [innerValue, setInnerValue] = useState<ImageListItemProps[]>(initialValue);
	const [previewVisible, setPreviewVisible] = useState(false);
	const [previewCurrent, setPreviewCurrent] = useState(0);
	const { locale } = useConfig();
	const value = innerValue;
	const uploadText = resolveImageListUploadText(uploadTextProp);
	const imageListLang = (locale?.imageList || zh_CN.imageList) as NonNullable<LangProps['imageList']>;

	useEffect(() => {
		setInnerValue(resolveImageListInitialItems(valueProp));
	}, [valueProp]);

	// 输入组件状态，返回框架无关的 class、默认图标、预览和上传项视图派生结果。
	// Receive component state and return framework-agnostic classes, default icons, preview data and item view derivations.
	const imageListState = resolveImageListDerived<
		ImageListItemProps,
		NonNullable<typeof icon>,
		NonNullable<typeof deleteIcon>,
		LoadingProps
	>({
		items: value,
		columns,
		gap,
		radius,
		aspectRatio,
		icon,
		deleteIcon,
		loading,
		injClass,
		itemInjClass,
		max,
		readonly,
		disabled,
		previewable,
		useItemIdAsFallbackAlt: true,
		uploadFailedText: imageListLang.uploadFailedText,
		pendingText: imageListLang.pendingText
	});

	const createItemFromFile = (file: File): ImageListItemProps => {
		const id = resolveImageListItemId({ timestamp: Date.now(), random: Math.random() });
		const url = URL.createObjectURL(file);
		return resolveImageListItemFromFile({ id, url, file });
	};

	const addFiles = (files: File[]) => {
		const flow = resolveImageListAddFilesFlow({
			disabled,
			readonly,
			files,
			currentLength: value.length,
			max,
			maxSize
		});
		if (!flow.shouldAddFiles) return;
		if (flow.exceeded) {
			onExceed?.(files, max);
		}
		flow.oversizedFiles.forEach((file) => onOversized?.(file, maxSize));
		const validFiles = flow.validFiles;
		if (validFiles.length === 0) return;
		const newItems = validFiles.map(createItemFromFile);
		setInnerValue(appendImageListItems(value, newItems));
		onAdd?.(validFiles);
	};

	useImperativeHandle(ref, () => ({
		addFiles
	}));

	const handleDelete = (item: ImageListItemProps, index: number) => {
		const flow = resolveImageListDeleteFlow({ disabled, readonly, items: value, item, index });
		if (!flow.shouldDelete) return;
		if (flow.shouldRevokeUrl && item.url) {
			URL.revokeObjectURL(item.url);
		}
		onDelete?.(item, index);
		setInnerValue(flow.nextItems);
	};

	const handlePreview = (item: ImageListItemProps, index: number) => {
		const flow = resolveImageListPreviewFlow({
			items: value,
			itemId: item.id,
			previewable,
			url: item.url,
			disabled
		});
		if (!flow.shouldOpen) return;
		setPreviewCurrent(flow.nextPreviewIndex);
		setPreviewVisible(flow.nextPreviewVisible);
		if (flow.shouldEmitPreview) onPreview?.(item, index);
	};

	const handlePreviewClose = () => {
		const action = resolveImageListPreviewCloseAction();
		if (action.shouldClose) setPreviewVisible(action.nextPreviewVisible);
	};

	const handleRetry = (item: ImageListItemProps, index: number) => {
		const action = resolveImageListMutationAction({ disabled, readonly });
		if (!action.shouldMutate) return;
		onRetry?.(item, index);
	};
	const handlePreviewKeyDown = (event: React.KeyboardEvent<HTMLElement>, item: ImageListItemProps, index: number) => {
		const flow = resolveImageListPreviewKeyboardFlow({
			key: event.key,
			items: value,
			itemId: item.id,
			previewable,
			url: item.url,
			disabled
		});
		if (flow.shouldPreventDefault) {
			event.preventDefault();
		}
		if (flow.shouldOpen) {
			setPreviewCurrent(flow.nextPreviewIndex);
			setPreviewVisible(flow.nextPreviewVisible);
			if (flow.shouldEmitPreview) onPreview?.(item, index);
		}
	};

	const handleUploadClick = () => {
		const action = resolveImageListMutationAction({ disabled, readonly });
		if (!action.shouldMutate) return;
		onClickUpload?.();
	};

	return (
		<>
			<div className={imageListState.rootClass}>
				{imageListState.itemViewStates.map(({ item, index, imageState, statusState, statusMessage, previewAction }) => {
					return (
						<div key={item.id} className={imageListState.itemClass} style={imageListState.aspectRatioStyleValue}>
							{itemChild ? (
								itemChild(item, index)
							) : (
								<>
									{imageState.showImage ? (
										<button
											type="button"
											className={imageListState.previewButtonClass}
											disabled={!previewAction.shouldPreview}
											onClick={() => handlePreview(item, index)}
											onKeyDown={(event) => handlePreviewKeyDown(event, item, index)}
										>
											<img src={imageState.src} alt={imageState.alt} className={imageListState.imageClass} />
										</button>
									) : null}
									{statusState.showOverlay ? (
										<div className={imageListState.statusOverlayClass}>
											{statusChild ? (
												statusChild(item)
											) : (
												<>
													{statusState.isUploading ? <Loading {...imageListState.mergedLoading} /> : null}
													{statusState.isError ? (
														<button
															type="button"
															className={imageListState.retryButtonClass}
															onClick={(event) => {
																event.stopPropagation();
																handleRetry(item, index);
															}}
														>
															{/* 公共刷新 SVG 数据在 common 中维护。 / Shared refresh SVG data lives in common. */}
															<SvgIcon svg={refreshSvg} width={24} height={24} className={imageListState.retryIconClass} />
															<span className={imageListState.retryMessageClass}>{statusMessage}</span>
														</button>
													) : null}
													{statusState.isPending ? <span className={imageListState.pendingMessageClass}>{statusMessage}</span> : null}
												</>
											)}
										</div>
									) : null}
								</>
							)}

							{deletable && !readonly && !disabled ? (
								<button
									type="button"
									className={imageListState.deleteButtonClass}
									onClick={(event) => {
										event.stopPropagation();
										handleDelete(item, index);
									}}
								>
									<Icon {...imageListState.mergedDeleteIcon} />
								</button>
							) : null}
						</div>
					);
				})}

				{imageListState.showUploadButton ? (
					<button
						type="button"
						className={imageListState.uploadClass}
						style={imageListState.aspectRatioStyleValue}
						disabled={disabled}
						onClick={handleUploadClick}
					>
						{uploadChild ? (
							uploadChild()
						) : (
							<>
								<Icon {...imageListState.mergedIcon} opacity={0.5} />
								{uploadText ? <span className={imageListState.uploadTextClass}>{uploadText}</span> : null}
							</>
						)}
					</button>
				) : null}
			</div>

			<ImagePreview
				visible={previewVisible}
				images={imageListState.previewImages}
				current={resolveImageListPreviewCurrent(previewCurrent)}
				onClose={handlePreviewClose}
				onChange={setPreviewCurrent}
			/>
		</>
	);
});

ImageList.displayName = 'ImageList';

export default ImageList;
