// apps/stdf-demo/src/routes/components/Aphorism.svelte
<script lang="ts">
	// 引入数据
	// import data
	import { aphorisms } from '@any-tdf/site-common/data';

	/**
	 * @typedef {Object} Props
	 * @property {number} [num] - number of items to display
	 * @property {boolean} [compact] - whether to use compact mode
	 */
	/** @type {Props} */
	let { num = 0, compact = false } = $props();

	// 从 aphorisms 随机取出 num 条数据
	// get num items from aphorisms randomly
	let aphorismsList = $derived(aphorisms.sort(() => Math.random() - 0.5).slice(0, num));
</script>

<div class="{compact ? '' : 'px-4 py-8 '}divide-y divide-black/5 dark:divide-white/5">
	{#each aphorismsList as item}
		<div class:py-6={num > 1}>
			<div class="text-justify text-sm">{item.text}</div>
			<div class="mt-1 text-right" class:italic={item.fromItalic}>{item.from}</div>
		</div>
	{/each}
</div>

// apps/vtdf-demo/src/pages/components/Aphorism.vue
<script setup lang="ts">
import { computed } from 'vue';
import { aphorisms } from '@any-tdf/site-common/data';

const props = withDefaults(
	defineProps<{
		num?: number;
		compact?: boolean;
	}>(),
	{
		num: 0,
		compact: false
	}
);

const aphorismsList = computed(() => [...aphorisms].sort(() => Math.random() - 0.5).slice(0, props.num));
</script>

<template>
	<div :class="[compact ? '' : 'px-4 py-8', 'divide-y divide-black/5 dark:divide-white/5']">
		<div v-for="item in aphorismsList" :key="item.text" :class="{ 'py-6': num > 1 }">
			<div class="text-justify text-sm">{{ item.text }}</div>
			<div :class="['mt-1 text-right', item.fromItalic ? 'italic' : '']">{{ item.from }}</div>
		</div>
	</div>
</template>
