// packages/vtdf/src/lib/components/Modal.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue';
import type { ModalProps } from '../types';
import {
	resolveModalCloseAction,
	resolveModalConfirmAction,
	resolveModalDerived,
	resolveModalStateOptions
} from '@any-tdf/common/derived/modal';
import { zh_CN } from '../lang';
import Button from './Button.vue';
import Icon from './Icon.vue';
import Popup from './Popup.vue';
import { useConfig } from './adapter/config';

const props = withDefaults(defineProps<ModalProps>(), {
	visible: false,
	title: undefined,
	titleAlign: 'center',
	content: undefined,
	popup: () => ({}),
	showIcon: false,
	icon: () => ({}),
	showBtn: true,
	btnText: undefined,
	button: () => ({})
});

const emit = defineEmits<{
	'update:visible': [visible: boolean];
	confirm: [];
	close: [];
}>();

const config = useConfig();
const slots = useSlots();
const modalLang = computed(() => config.locale?.modal || zh_CN.modal);
// 公共派生层处理 Modal 状态推导，关闭事件和 slot 留在组件内。
// The shared derived layer handles Modal state derivation; close events and slots stay in the component.
const modalState = computed(() =>
	resolveModalDerived(
		resolveModalStateOptions({
			props: {
				title: props.title,
				titleAlign: props.titleAlign,
				content: props.content,
				btnText: props.btnText,
				showBtn: props.showBtn,
				popup: props.popup,
				showIcon: props.showIcon
			},
			defaults: modalLang.value,
			hasCustomContent: Boolean(slots.default)
		})
	)
);

const closeModalFunc = () => {
	// 公共动作函数只返回关闭决策，组件层负责状态写入和事件触发。
	// Shared action function only returns close decisions; the component writes state and fires events.
	const action = resolveModalCloseAction();
	emit('update:visible', action.nextVisible);
	if (action.shouldClose) emit('close');
};

const confirmModalFunc = () => {
	const action = resolveModalConfirmAction();
	if (action.shouldConfirm) emit('confirm');
	if (action.shouldClose) {
		emit('update:visible', action.nextVisible);
		emit('close');
	}
};
</script>

<template>
	<Popup
		:visible="visible"
		v-bind="modalState.popupProps"
		@update:visible="(value) => emit('update:visible', value)"
		@close="closeModalFunc"
	>
		<div :class="modalState.contentClass">
			<div :class="modalState.titleClass">{{ modalState.texts.title }}</div>
			<div v-if="modalState.contentState.showIcon">
				<Icon v-bind="icon" />
			</div>
			<div>
				<slot v-if="modalState.contentState.showCustomContent" />
				<template v-else-if="modalState.contentState.showContentText">{{ modalState.texts.content }}</template>
			</div>
			<div v-if="modalState.contentState.showButton">
				<Button size="full" v-bind="button" @click="confirmModalFunc">{{ modalState.texts.btnText }}</Button>
			</div>
		</div>
	</Popup>
</template>

// packages/rtdf/src/lib/components/modal/index.tsx
import type { ModalProps } from '../../types';
import { forwardRef, useState, useEffect } from 'react';
import Popup from '../popup';
import Button from '../button';
import Icon from '../icon';
import { zh_CN } from '../../lang';
import { useConfig } from '../config-provider';
import {
	resolveModalCloseAction,
	resolveModalConfirmAction,
	resolveModalDerived,
	resolveModalInitialVisible,
	resolveModalStateOptions
} from '@any-tdf/common/derived/modal';
import { splitButtonCallbacks, splitPopupCallbacks } from '@any-tdf/common/derived/props';

const Modal = forwardRef<HTMLDivElement, ModalProps>(
	(
		{
			visible = false,
			title: titleProp,
			titleAlign = 'center',
			content: contentProp,
			popup = {},
			showIcon = false,
			icon,
			showBtn = true,
			btnText: btnTextProp,
			button,
			contentChild,
			onClose
		},
		_ref
	) => {
		const { locale } = useConfig();
		const modalLang = locale?.modal || zh_CN.modal;
		const [internalVisible, setInternalVisible] = useState(() => resolveModalInitialVisible(visible));
		const { buttonProps, buttonOnClick } = splitButtonCallbacks(button);
		const { popupProps, popupOnClose } = splitPopupCallbacks(popup);
		// 公共派生层处理 Modal 状态推导，关闭事件和 children 留在组件内。
		// The shared derived layer handles Modal state derivation; close events and children stay in the component.
		const modalState = resolveModalDerived(
			resolveModalStateOptions({
				props: {
					title: titleProp,
					titleAlign,
					content: contentProp,
					btnText: btnTextProp,
					showBtn,
					popup: popupProps,
					showIcon
				},
				defaults: modalLang,
				hasCustomContent: Boolean(contentChild)
			})
		);

		useEffect(() => {
			setInternalVisible(resolveModalInitialVisible(visible));
		}, [visible]);

		// 处理关闭
		// Handle close
		const handleClose = () => {
			// 公共动作函数只返回关闭决策，组件层负责状态写入和事件触发。
			// Shared action function only returns close decisions; the component writes state and fires events.
			const action = resolveModalCloseAction();
			setInternalVisible(action.nextVisible);
			if (action.shouldClose) onClose?.();
		};

		const handlePopupClose = () => {
			handleClose();
			popupOnClose?.();
		};

		const handleButtonClick = (event?: React.MouseEvent<HTMLButtonElement>) => {
			buttonOnClick?.(event);
			const action = resolveModalConfirmAction();
			if (action.shouldClose) {
				setInternalVisible(action.nextVisible);
				onClose?.();
			}
		};

		return (
			<Popup visible={internalVisible} {...modalState.popupProps} onClose={handlePopupClose}>
				<div className={modalState.contentClass}>
					<div className={modalState.titleClass}>{modalState.texts.title}</div>
					{modalState.contentState.showIcon && (
						<div>
							<Icon {...icon} />
						</div>
					)}
					{modalState.contentState.showCustomContent ? (
						<div>{contentChild}</div>
					) : modalState.contentState.showContentText ? (
						<div>{modalState.texts.content}</div>
					) : null}
					{modalState.contentState.showButton && (
						<div>
							<Button size="full" fill="base" state="theme" {...buttonProps} onClick={handleButtonClick}>
								{modalState.texts.btnText}
							</Button>
						</div>
					)}
				</div>
			</Popup>
		);
	}
);

Modal.displayName = 'Modal';

export type { ModalProps } from '../../types';
export default Modal;
