// apps/vtdf-site/src/pages/guide/GuideLayout.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { buildSiteOutline, observeActiveSiteOutline, type SiteOutlineItem } from '@any-tdf/site-common/outline';
import Menu from '../../components/Menu.vue';
import { guideMenuList, type GuideMenuChild, type SiteMenuChild } from '../../data/menuList';
import { appState, navigateTo } from '../../store/appStore';
import GuidePage from './GuidePage.vue';

const isZh = computed(() => appState.lang === 'zh_CN');
const contentRoot = ref<HTMLDivElement | null>(null);
const outline = ref<SiteOutlineItem[]>([]);
const activeId = ref('');
const mobileOutlineOpen = ref(false);

const flatMenuList = guideMenuList.flatMap((group) => group.childs);
const getGuideNavFromPath = (pathname: string) => pathname.split('/').filter(Boolean)[1] ?? 'quick-start';
const guideDocMap: Record<string, string> = {
	'icon-plugin': 'iconPlugin',
	md: 'mdPlugin'
};
const currentNav = computed<GuideMenuChild>(() => {
	const path = appState.pathname;
	const guideNav = getGuideNavFromPath(path);
	return flatMenuList.find((item) => item.nav === guideNav) ?? flatMenuList[0];
});

watch(
	() => appState.pathname,
	() => {
		mobileOutlineOpen.value = false;
	}
);

const refreshOutline = () => {
	if (!contentRoot.value) {
		outline.value = [];
		activeId.value = '';
		return () => undefined;
	}
	outline.value = buildSiteOutline(contentRoot.value);
	return observeActiveSiteOutline(contentRoot.value, (id) => (activeId.value = id));
};

let stopOutline = refreshOutline();
let observer: MutationObserver | null = null;

onMounted(() => {
	stopOutline = refreshOutline();
	observer = new MutationObserver(() => {
		stopOutline();
		stopOutline = refreshOutline();
	});
	if (contentRoot.value) observer.observe(contentRoot.value, { childList: true, subtree: true });
});

onBeforeUnmount(() => {
	observer?.disconnect();
	stopOutline();
});

const selectMenu = (item: SiteMenuChild) => {
	appState.isShowNav = false;
	navigateTo(`/guide${item.nav === 'quick-start' ? '' : `/${item.nav}`}`);
};

const editUrl = computed(() => {
	const base = 'https://github.com/any-tdf/any-tdf/edit/main/content/vtdf/guide/';
	if (currentNav.value.nav === 'create')
		return `https://github.com/any-tdf/any-tdf/edit/main/packages/create-any-tdf/README${isZh.value ? '_CN' : ''}.md`;
	const currentDoc = currentNav.value.doc ?? guideDocMap[currentNav.value.nav];
	return `${base}${currentDoc}${isZh.value ? '' : '_en'}.md`;
});
</script>

<template>
	<div class="site-doc-toolbar">
		<button class="site-header-action" type="button" @click="appState.isShowNav = !appState.isShowNav">
			☰ {{ isZh ? '目录' : 'Menu' }}
		</button>
		<button class="site-header-action" type="button" :disabled="outline.length === 0" @click="mobileOutlineOpen = !mobileOutlineOpen">
			{{ isZh ? '本页目录' : 'On this page' }} {{ outline.length > 0 ? '⌄' : '' }}
		</button>
	</div>

	<div class="site-doc-layout">
		<aside class="site-sidebar" :class="{ 'is-open': appState.isShowNav }">
			<Menu
				:menu-list="guideMenuList"
				:current-nav="currentNav.nav"
				:show-num="false"
				show-icons
				icon-set="guide"
				@menu-click="selectMenu"
			/>
		</aside>

		<main class="site-doc-main">
			<div class="site-doc-main-inner is-wide" ref="contentRoot">
				<GuidePage :current-nav="currentNav.nav" />
			</div>

			<div
				v-if="!['color', 'logo', 'shortkey'].includes(currentNav.nav)"
				class="mt-10 flex flex-wrap items-center gap-3 border-t border-(--site-divider) pt-5 text-sm"
			>
				<a class="text-(--site-accent)" :href="editUrl" target="_blank">{{ isZh ? '在 GitHub 上编辑' : 'Edit on GitHub' }} ↗</a>
			</div>
		</main>

		<aside class="site-outline" :aria-label="isZh ? '本页目录' : 'On this page'">
			<template v-if="outline.length > 0">
				<h2 class="site-outline-title">{{ isZh ? '本页目录' : 'On this page' }}</h2>
				<a
					v-for="item in outline"
					:key="item.id"
					class="site-outline-link"
					:class="{ 'is-active': activeId === item.id }"
					:data-level="item.level"
					:aria-current="activeId === item.id ? 'location' : undefined"
					:href="`#${item.id}`"
				>
					{{ item.title }}
				</a>
			</template>
		</aside>
	</div>

	<div v-if="mobileOutlineOpen && outline.length > 0" class="mobile-outline-panel">
		<div class="mb-2 flex items-center justify-between">
			<strong>{{ isZh ? '本页目录' : 'On this page' }}</strong>
			<button class="site-header-action" type="button" @click="mobileOutlineOpen = false">×</button>
		</div>
		<a
			v-for="item in outline"
			:key="item.id"
			class="site-outline-link"
			:class="{ 'is-active': activeId === item.id }"
			:data-level="item.level"
			:href="`#${item.id}`"
			@click="mobileOutlineOpen = false"
		>
			{{ item.title }}
		</a>
	</div>
</template>

// apps/rtdf-site/src/pages/guide/GuideLayout.tsx
import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { buildSiteOutline, observeActiveSiteOutline, type SiteOutlineItem } from '@any-tdf/site-common/outline';
import { guideMenuList, type GuideMenuChild } from '@any-tdf/site-common/data';
import Menu from '../../components/Menu';
import { useAppContext } from '../../store/appStore';
import ColorPage from './ColorPage';
import IconPage from './IconPage';
import LogoPage from './LogoPage';
import ShortkeyPage from './ShortkeyPage';
import MdPage from './MdPage';

const flatMenuList = guideMenuList.flatMap((group) => group.childs);

// 无 doc 字段的条目对应的 mds/guide 文件名
const specialDocMap: Record<string, string> = {
	create: 'create',
	'icon-plugin': 'iconPlugin',
	md: 'mdPlugin'
};
const getGuideNavFromPath = (pathname: string) => pathname.split('/').filter(Boolean)[1] ?? 'quick-start';

const GuideLayout = () => {
	const location = useLocation();
	const navigate = useNavigate();
	const { lang, isShowNav, setIsShowNav } = useAppContext();
	const isZh = lang === 'zh_CN';

	const contentRootRef = useRef<HTMLDivElement | null>(null);
	const [outline, setOutline] = useState<SiteOutlineItem[]>([]);
	const [activeId, setActiveId] = useState('');
	const [mobileOutlineOpen, setMobileOutlineOpen] = useState(false);

	const path = location.pathname;
	const guideNav = getGuideNavFromPath(path);
	const currentNav: GuideMenuChild = flatMenuList.find((item) => item.nav === guideNav) ?? flatMenuList[0];

	// 路由变化时收起移动端目录
	useEffect(() => {
		setMobileOutlineOpen(false);
	}, [path]);

	// 文档目录
	useEffect(() => {
		const contentRoot = contentRootRef.current;
		if (!contentRoot) return;
		const refreshOutline = () => {
			setOutline(buildSiteOutline(contentRoot));
			return observeActiveSiteOutline(contentRoot, (id) => setActiveId(id));
		};
		let stopOutline = refreshOutline();
		const observer = new MutationObserver(() => {
			stopOutline();
			stopOutline = refreshOutline();
		});
		observer.observe(contentRoot, { childList: true, subtree: true });
		return () => {
			observer.disconnect();
			stopOutline();
		};
	}, [currentNav.nav]);

	const selectMenu = (item: GuideMenuChild) => {
		setIsShowNav(false);
		void navigate(`/guide${item.nav === 'quick-start' ? '' : `/${item.nav}`}`);
	};

	const currentDoc = currentNav.doc ?? specialDocMap[currentNav.nav];
	const editUrl = `https://github.com/any-tdf/any-tdf/edit/main/content/rtdf/guide/${currentDoc}${isZh ? '' : '_en'}.md`;

	const renderPage = () => {
		switch (currentNav.nav) {
			case 'color':
				return <ColorPage />;
			case 'logo':
				return <LogoPage />;
			case 'shortkey':
				return <ShortkeyPage />;
			case 'icon':
				return <IconPage />;
			case 'quick-start':
				return <MdPage doc="quickStart" groupIcon="after" pb12 />;
			case 'theme':
				return <MdPage doc="theme" pb12 />;
			case 'utils':
				return <MdPage doc="utils" pb12 />;
			case 'create':
				return <MdPage doc="create" groupIcon="after" />;
			case 'icon-plugin':
				return <MdPage doc="iconPlugin" groupIcon="before" />;
			case 'md':
				return <MdPage doc="mdPlugin" groupIcon="before" />;
			case 'contribution':
				return <MdPage doc="contribution" groupIcon="after" />;
			default:
				return <MdPage doc={currentNav.doc ?? currentNav.nav} />;
		}
	};

	return (
		<>
			<div className="site-doc-toolbar">
				<button className="site-header-action" onClick={() => setIsShowNav(!isShowNav)} type="button">
					☰ {isZh ? '目录' : 'Menu'}
				</button>
				<button
					className="site-header-action"
					onClick={() => setMobileOutlineOpen(!mobileOutlineOpen)}
					disabled={outline.length === 0}
					type="button"
				>
					{isZh ? '本页目录' : 'On this page'} {outline.length > 0 ? '⌄' : ''}
				</button>
			</div>

			<div className="site-doc-layout">
				<aside className={`site-sidebar${isShowNav ? ' is-open' : ''}`}>
					<Menu menuList={guideMenuList} currentNav={currentNav.nav} onMenuClick={selectMenu} showNum={false} showIcons iconSet="guide" />
				</aside>

				<main className="site-doc-main">
					<div className="site-doc-main-inner is-wide" ref={contentRootRef}>
						{renderPage()}
					</div>

					{!['color', 'logo', 'shortkey'].includes(currentNav.nav) ? (
						<div className="mt-10 flex flex-wrap items-center gap-3 border-t border-(--site-divider) pt-5 text-sm">
							<a className="text-(--site-accent)" href={editUrl} target="_blank" rel="noreferrer">
								{isZh ? '在 GitHub 上编辑' : 'Edit on GitHub'} ↗
							</a>
						</div>
					) : null}
				</main>

				<aside className="site-outline" aria-label={isZh ? '本页目录' : 'On this page'}>
					{outline.length > 0 ? (
						<>
							<h2 className="site-outline-title">{isZh ? '本页目录' : 'On this page'}</h2>
							{outline.map((item) => (
								<a
									className={`site-outline-link${activeId === item.id ? ' is-active' : ''}`}
									data-level={item.level}
									aria-current={activeId === item.id ? 'location' : undefined}
									href={`#${item.id}`}
									key={item.id}
								>
									{item.title}
								</a>
							))}
						</>
					) : null}
				</aside>
			</div>

			{mobileOutlineOpen && outline.length > 0 ? (
				<div className="mobile-outline-panel">
					<div className="mb-2 flex items-center justify-between">
						<strong>{isZh ? '本页目录' : 'On this page'}</strong>
						<button className="site-header-action" onClick={() => setMobileOutlineOpen(false)} type="button">
							×
						</button>
					</div>
					{outline.map((item) => (
						<a
							className={`site-outline-link${activeId === item.id ? ' is-active' : ''}`}
							data-level={item.level}
							href={`#${item.id}`}
							onClick={() => setMobileOutlineOpen(false)}
							key={item.id}
						>
							{item.title}
						</a>
					))}
				</div>
			) : null}
		</>
	);
};

export default GuideLayout;
