// packages/rtdf/src/lib/components/loading/loadings/fourColor/4_1.tsx
import type { FC } from 'react';
import {
	resolveLoadingFourShapeTranslateCss,
	resolveLoadingFourColorShapeStyle,
	resolveLoadingShapeContainerClass,
	resolveLoadingShapePieceClass
} from '@any-tdf/common/derived/loading';
import { parseStyle } from '../../../utils/style';

type Props = { size?: string; customColor?: string[]; speed?: number };

const Loading4_1: FC<Props> = ({ size = 'w-8 h-8', customColor = [], speed = 1 }) => {
	const css = resolveLoadingFourShapeTranslateCss({ scope: 'rtdf_loading_4_1' });

	return (
		<>
			{css ? <style>{css}</style> : null}
			<div className="rtdf_loading_4_1">
				<div className={resolveLoadingShapeContainerClass({ kind: 'rotatedCorner', size })}>
					<div
						className={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 0 })}
						style={parseStyle(resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 0, customColor, speed }))}
					></div>
					<div
						className={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 1 })}
						style={parseStyle(resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 1, customColor, speed }))}
					></div>
					<div
						className={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 2 })}
						style={parseStyle(resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 2, customColor, speed }))}
					></div>
					<div
						className={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 3 })}
						style={parseStyle(resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 3, customColor, speed }))}
					></div>
				</div>
			</div>
		</>
	);
};

export default Loading4_1;

// packages/stdf/src/lib/components/loading/loadings/fourColor/4_1.svelte
<script lang="ts">
	import { resolveLoadingFourShapeTranslateCss, resolveLoadingFourColorShapeStyle, resolveLoadingShapeContainerClass, resolveLoadingShapePieceClass } from '@any-tdf/common/derived/loading';
	type Props = { size?: string; customColor?: string[]; speed?: number };

	let { size = 'w-8 h-8', customColor = [], speed = $bindable(1) }: Props = $props();
	const css = resolveLoadingFourShapeTranslateCss({ scope: 'stdf_loading_4_1' });
</script>

<svelte:head>
	{@html `<style>${css}</style>`}
</svelte:head>

<div class="stdf_loading_4_1">
	<div class={resolveLoadingShapeContainerClass({ kind: 'rotatedCorner', size })}>
		<div
			class={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 0 })}
			style={resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 0, customColor, speed })}
		></div>
		<div
			class={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 1 })}
			style={resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 1, customColor, speed })}
		></div>
		<div
			class={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 2 })}
			style={resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 2, customColor, speed })}
		></div>
		<div
			class={resolveLoadingShapePieceClass({ variant: 'cornerThird', index: 3 })}
			style={resolveLoadingFourColorShapeStyle({ variant: '4_1', index: 3, customColor, speed })}
		></div>
	</div>
</div>
