// packages/rtdf/src/lib/components/actionPopover/index.tsx
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import type { ActionPopoverProps, ActionProps, RingActionProps } from '../../types';
import Icon from '../icon';
import { useConfig } from '../config-provider';
import { zh_CN } from '../../lang';
import { useTransition } from '../utils/transition';
import { easingFunctions } from '../utils/easing';
import {
	resolveActionPopoverActionClickFlow,
	resolveActionPopoverCancelAction,
	resolveActionPopoverCloseAction,
	resolveActionPopoverDerived,
	resolveActionPopoverHideForViewportAction,
	resolveActionPopoverInlineCloseCompleteAction,
	resolveActionPopoverInlinePositionState,
	resolveActionPopoverInitialVisible,
	resolveActionPopoverMeasuredDimension,
	resolveActionPopoverRenderAction,
	resolveActionPopoverRestoreFromViewportAction,
	resolveActionPopoverRingCloseCompleteAction,
	resolveActionPopoverRingPositionState,
	resolveActionPopoverShouldBindGlobalListeners,
	resolveActionPopoverStateOptions,
	resolveActionPopoverTriggerElement,
	resolveActionPopoverTriggerInViewport,
	resolveActionPopoverViewportAction
} from '@any-tdf/common/derived/actionPopover';
import type { ActionPopoverTriggerRefLike } from '@any-tdf/common/derived/actionPopover';
import { resolveActionSheetCancelText } from '@any-tdf/common/derived/actionSheet';
import { resolveViewportDimension, resolveViewportFallbackDimension } from '@any-tdf/common/derived/helpers';

const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect;
const maxPositionAttempts = 4;

const ActionPopover: React.FC<ActionPopoverProps> = ({
	visible: visibleProp,
	title = '',
	titleAlign = 'center',
	actions = [],
	showCancel = false,
	cancelText: cancelTextProp,
	actionClosable = true,
	align = 'center',
	inverse = false,
	layout = 'v',
	gridColumns = 3,
	triggerRef = null,
	inlineAlign = 'center',
	inlineDirection = 'auto',
	inlineOffset = 8,
	inlineShadow = 'md',
	inlineRadius = '',
	ringActions = [],
	ringRadius = 0,
	ringItemSize = 44,
	ringShape = 'auto',
	onCancel,
	onClickAction,
	onClose
}) => {
	const { locale } = useConfig();
	const actionPopoverLang = locale?.actionSheet || zh_CN.actionSheet;
	const cancelText = resolveActionSheetCancelText(cancelTextProp, actionPopoverLang);
	const [innerVisible, setInnerVisible] = useState(() => resolveActionPopoverInitialVisible(visibleProp));
	const [inlinePosition, setInlinePosition] = useState({ top: 0, left: 0 });
	const [positionReady, setPositionReady] = useState(false);
	const [actualDirection, setActualDirection] = useState<'up' | 'down'>('down');
	const [ringPosition, setRingPosition] = useState({ x: 0, y: 0 });
	const [computedRingShape, setComputedRingShape] = useState<'full' | 'half' | 'quarter'>('quarter');
	const [ringStartAngle, setRingStartAngle] = useState(0);
	const [ringAnimate, setRingAnimate] = useState(false);
	const [hiddenByViewport, setHiddenByViewport] = useState(false);
	const [shouldRender, setShouldRender] = useState(() => resolveActionPopoverInitialVisible(visibleProp));
	const panelRef = useRef<HTMLDivElement | null>(null);
	const positionFrameRef = useRef<number | null>(null);
	const ringAnimationFrameRef = useRef<number | null>(null);
	const visibleRef = useRef(false);
	const hiddenByViewportRef = useRef(false);

	// 公共派生层只处理 ActionPopover class、style 和过渡参数，DOM 读取与事件留在组件内。
	// Shared derived layer only handles ActionPopover classes, styles and transition params; DOM reads and events stay in the component.
	const actionPopoverDerived = useMemo(
		() =>
			resolveActionPopoverDerived<ActionProps, RingActionProps>(
				resolveActionPopoverStateOptions<ActionProps, RingActionProps>({
					props: {
						actions,
						align,
						gridColumns,
						inlineAlign,
						inlineRadius,
						inlineShadow,
						inverse,
						layout,
						ringActions,
						ringItemSize,
						ringRadius,
						showCancel,
						title,
						titleAlign,
						visible: visibleProp
					},
					actualDirection,
					computedRingShape,
					hiddenByViewport,
					inlinePosition,
					innerVisible,
					positionReady,
					ringAnimate,
					ringPosition,
					ringStartAngle
				})
			),
		[
			actions,
			actualDirection,
			align,
			computedRingShape,
			gridColumns,
			hiddenByViewport,
			inlineAlign,
			inlinePosition,
			inlineRadius,
			inlineShadow,
			innerVisible,
			inverse,
			layout,
			positionReady,
			ringActions,
			ringAnimate,
			ringItemSize,
			ringPosition,
			ringRadius,
			ringStartAngle,
			showCancel,
			title,
			titleAlign,
			visibleProp
		]
	);
	const visible = actionPopoverDerived.visible;
	const getTriggerElement = useCallback(
		() => resolveActionPopoverTriggerElement<HTMLElement>(triggerRef as ActionPopoverTriggerRefLike<HTMLElement>),
		[triggerRef]
	);

	useEffect(() => {
		setInnerVisible(resolveActionPopoverInitialVisible(visibleProp));
		hiddenByViewportRef.current = false;
		setHiddenByViewport(false);
	}, [visibleProp]);

	useEffect(() => {
		visibleRef.current = visible;
	}, [visible]);

	useEffect(() => {
		hiddenByViewportRef.current = hiddenByViewport;
	}, [hiddenByViewport]);

	const clearPositionFrames = useCallback(() => {
		if (positionFrameRef.current !== null) {
			cancelAnimationFrame(positionFrameRef.current);
			positionFrameRef.current = null;
		}
		if (ringAnimationFrameRef.current !== null) {
			cancelAnimationFrame(ringAnimationFrameRef.current);
			ringAnimationFrameRef.current = null;
		}
	}, []);

	useEffect(() => {
		return clearPositionFrames;
	}, [clearPositionFrames]);

	const calculateRingLayout = useCallback(() => {
		const triggerElement = getTriggerElement();
		if (!triggerElement || layout !== 'ring') return false;
		const triggerRect = triggerElement.getBoundingClientRect();
		if (!triggerRect.width || !triggerRect.height) return false;
		const viewportWidth = resolveViewportDimension({ value: window.innerWidth });
		const viewportHeight = resolveViewportDimension({ value: window.innerHeight });
		// 公共位置派生只消费测量结果，DOM 读取保留在组件内。
		// Shared position derivation consumes measurements only; DOM reads stay in the component.
		const positionState = resolveActionPopoverRingPositionState({
			triggerRect,
			viewportWidth,
			viewportHeight,
			itemCount: ringActions.length,
			ringShape
		});
		setRingPosition(positionState.ringPosition);
		setComputedRingShape(positionState.computedRingShape);
		setRingStartAngle(positionState.ringStartAngle);
		return true;
	}, [getTriggerElement, layout, ringActions.length, ringShape]);

	const calculateInlinePosition = useCallback(() => {
		const triggerElement = getTriggerElement();
		if (!triggerElement || !panelRef.current) return false;
		const triggerRect = triggerElement.getBoundingClientRect();
		const panelRect = panelRef.current.getBoundingClientRect();
		const panelWidth = resolveActionPopoverMeasuredDimension({
			measured: panelRef.current.offsetWidth,
			fallback: panelRect.width
		});
		const panelHeight = resolveActionPopoverMeasuredDimension({
			measured: panelRef.current.offsetHeight,
			fallback: panelRect.height
		});
		const viewportHeight = resolveViewportDimension({ value: window.innerHeight });
		const viewportWidth = resolveViewportDimension({ value: window.innerWidth });

		const positionState = resolveActionPopoverInlinePositionState({
			triggerRect,
			panelWidth,
			panelHeight,
			viewportWidth,
			viewportHeight,
			inlineAlign,
			inlineDirection,
			inlineOffset
		});
		setActualDirection(positionState.actualDirection);
		setInlinePosition(positionState.inlinePosition);
		return true;
	}, [getTriggerElement, inlineAlign, inlineDirection, inlineOffset]);

	const updatePosition = useCallback(() => {
		if (layout === 'ring') return calculateRingLayout();
		return calculateInlinePosition();
	}, [calculateInlinePosition, calculateRingLayout, layout]);

	const schedulePosition = useCallback(
		(attempt = 0) => {
			clearPositionFrames();
			const runPosition = (nextAttempt = attempt) => {
				positionFrameRef.current = requestAnimationFrame(() => {
					positionFrameRef.current = null;
					const nextPositionReady = layout === 'ring' ? calculateRingLayout() : calculateInlinePosition();
					if (!nextPositionReady) {
						if (nextAttempt < maxPositionAttempts) runPosition(nextAttempt + 1);
						return;
					}
					setPositionReady(true);
				});
			};
			runPosition();
		},
		[calculateInlinePosition, calculateRingLayout, clearPositionFrames, layout]
	);

	const isTriggerInViewport = useCallback(() => {
		const triggerElement = getTriggerElement();
		if (!triggerElement) return false;
		const triggerRect = triggerElement.getBoundingClientRect();
		const viewportWidth = resolveViewportFallbackDimension({
			value: window.innerWidth,
			fallback: document.documentElement.clientWidth
		});
		const viewportHeight = resolveViewportFallbackDimension({
			value: window.innerHeight,
			fallback: document.documentElement.clientHeight
		});
		return resolveActionPopoverTriggerInViewport({ triggerRect, viewportWidth, viewportHeight });
	}, [getTriggerElement]);

	const setViewportHidden = useCallback((nextHidden: boolean) => {
		hiddenByViewportRef.current = nextHidden;
		setHiddenByViewport(nextHidden);
	}, []);

	const hideForViewport = useCallback(() => {
		const action = resolveActionPopoverHideForViewportAction({
			visible: visibleRef.current,
			hiddenByViewport: hiddenByViewportRef.current
		});
		if (!action.shouldChange) return;
		setViewportHidden(action.nextHiddenByViewport);
	}, [setViewportHidden]);

	const restoreFromViewport = useCallback(() => {
		const action = resolveActionPopoverRestoreFromViewportAction({
			hiddenByViewport: hiddenByViewportRef.current,
			triggerInViewport: isTriggerInViewport()
		});
		if (!action.shouldChange) return;
		setViewportHidden(action.nextHiddenByViewport);
	}, [isTriggerInViewport, setViewportHidden]);

	const emitClose = useCallback(() => {
		onClose?.();
	}, [onClose]);

	const emitCancel = () => {
		onCancel?.();
	};

	const emitClickAction = (index: number, item: ActionProps | RingActionProps) => {
		onClickAction?.(index, item);
	};

	const closePanel = useCallback(() => {
		const action = resolveActionPopoverCloseAction();
		if (action.shouldClose) {
			setViewportHidden(false);
			setInnerVisible(action.nextVisible);
		}
		if (action.shouldEmitClose) emitClose();
	}, [emitClose, setViewportHidden]);

	const handleInlineOutroEnd = useCallback(() => {
		const action = resolveActionPopoverInlineCloseCompleteAction();
		setPositionReady(action.nextPositionReady);
		setShouldRender(action.nextShouldRender);
	}, []);

	const inlineTransitionOptions = useMemo(
		() => ({
			transition: 'scale' as const,
			inParams: {
				...actionPopoverDerived.inlineInParams,
				easing: easingFunctions.cubicOut
			},
			outParams: {
				...actionPopoverDerived.inlineOutParams,
				easing: easingFunctions.cubicOut
			},
			onOutroEnd: handleInlineOutroEnd
		}),
		[actionPopoverDerived.inlineInParams, actionPopoverDerived.inlineOutParams, handleInlineOutroEnd]
	);

	const inlineTransition = useTransition<HTMLDivElement>(actionPopoverDerived.inlineVisible && positionReady, inlineTransitionOptions);

	const setInlinePanelRef = useCallback(
		(node: HTMLDivElement | null) => {
			panelRef.current = node;
			(inlineTransition.ref as { current: HTMLDivElement | null }).current = node;
		},
		[inlineTransition.ref]
	);

	const handleClickOutside = useCallback(
		(event: MouseEvent) => {
			if (!visible) return;
			const target = event.target as Node;
			const triggerElement = getTriggerElement();
			if (panelRef.current && !panelRef.current.contains(target) && triggerElement && !triggerElement.contains(target)) {
				closePanel();
			}
		},
		[closePanel, getTriggerElement, visible]
	);

	const handleCancel = () => {
		// 公共动作函数只返回状态和回调决策，组件层负责写入状态和触发事件。
		// Shared action function only returns state and callback decisions; the component writes state and fires events.
		const action = resolveActionPopoverCancelAction();
		setViewportHidden(false);
		setInnerVisible(action.nextVisible);
		if (action.shouldCancel) emitCancel();
		if (action.shouldClose) emitClose();
	};

	const handleActionClick = (index: number, item: ActionProps) => {
		const action = resolveActionPopoverActionClickFlow({ action: item, actionClosable, index });
		if (!action.shouldSelect) return;
		emitClickAction(action.index, action.action);
		if (action.closeAction.shouldClose) {
			setViewportHidden(false);
			setInnerVisible(action.closeAction.nextVisible);
			if (action.closeAction.shouldEmitClose) emitClose();
		}
	};

	const handleRingActionClick = (index: number, item: RingActionProps) => {
		const action = resolveActionPopoverActionClickFlow({ action: item, actionClosable, index });
		if (!action.shouldSelect) return;
		emitClickAction(action.index, action.action);
		if (action.closeAction.shouldClose) {
			setViewportHidden(false);
			setInnerVisible(action.closeAction.nextVisible);
			if (action.closeAction.shouldEmitClose) emitClose();
		}
	};

	useIsomorphicLayoutEffect(() => {
		clearPositionFrames();
		// 公共 action 只决定渲染生命周期，timer 和状态写入留在组件层。
		// Shared action only decides the render lifecycle; timers and state writes stay in the component layer.
		const renderAction = resolveActionPopoverRenderAction({
			visible,
			layout,
			shouldRender,
			positionReady
		});
		if (renderAction.kind === 'keepInlineOutro') {
			return;
		}
		setShouldRender(renderAction.nextShouldRender);
		setRingAnimate(renderAction.nextRingAnimate);
		setPositionReady(renderAction.nextPositionReady);
		if (renderAction.shouldScheduleRingClose) {
			const timer = setTimeout(() => {
				const completeAction = resolveActionPopoverRingCloseCompleteAction();
				setPositionReady(completeAction.nextPositionReady);
				setShouldRender(completeAction.nextShouldRender);
			}, renderAction.ringCloseDelayMs);
			return () => clearTimeout(timer);
		}
	}, [clearPositionFrames, layout, shouldRender, visible]);

	useIsomorphicLayoutEffect(() => {
		if (!visible || !shouldRender) return;
		schedulePosition();
		return clearPositionFrames;
	}, [clearPositionFrames, schedulePosition, shouldRender, visible]);

	useIsomorphicLayoutEffect(() => {
		if (!visible || !shouldRender || layout !== 'ring' || !positionReady || ringAnimate) return;
		const panelNode = panelRef.current;
		if (!panelNode) return;
		panelNode.getBoundingClientRect();
		ringAnimationFrameRef.current = requestAnimationFrame(() => {
			ringAnimationFrameRef.current = null;
			setRingAnimate(true);
		});
		return () => {
			if (ringAnimationFrameRef.current !== null) {
				cancelAnimationFrame(ringAnimationFrameRef.current);
				ringAnimationFrameRef.current = null;
			}
		};
	}, [layout, positionReady, ringAnimate, shouldRender, visible]);

	useEffect(() => {
		if (!resolveActionPopoverShouldBindGlobalListeners({ visible, hiddenByViewport })) return;
		let frameId = 0;
		const updateOrHide = () => {
			cancelAnimationFrame(frameId);
			frameId = requestAnimationFrame(() => {
				const viewportAction = resolveActionPopoverViewportAction({
					triggerInViewport: isTriggerInViewport(),
					hiddenByViewport: hiddenByViewportRef.current
				});
				if (viewportAction === 'hideForViewport') {
					hideForViewport();
					return;
				}
				if (viewportAction === 'restoreFromViewport') {
					restoreFromViewport();
					return;
				}
				updatePosition();
			});
		};
		const clickTimer = visible
			? setTimeout(() => {
					document.addEventListener('click', handleClickOutside);
				}, 0)
			: null;
		window.addEventListener('scroll', updateOrHide, true);
		window.addEventListener('resize', updateOrHide);
		updateOrHide();

		return () => {
			cancelAnimationFrame(frameId);
			if (clickTimer) clearTimeout(clickTimer);
			document.removeEventListener('click', handleClickOutside);
			window.removeEventListener('scroll', updateOrHide, true);
			window.removeEventListener('resize', updateOrHide);
		};
	}, [handleClickOutside, hiddenByViewport, hideForViewport, isTriggerInViewport, restoreFromViewport, updatePosition, visible]);

	if (!shouldRender) return null;

	if (layout === 'ring') {
		if (!positionReady) return null;
		return (
			<div ref={panelRef} className={actionPopoverDerived.ringPanelClass} style={actionPopoverDerived.ringPanelStyleValue}>
				{actionPopoverDerived.ringItemDerivedList.map((itemDerived, index) => {
					return (
						<button
							key={`ring-${index}`}
							type="button"
							className={itemDerived.buttonClass}
							style={itemDerived.style}
							disabled={itemDerived.disabled}
							onClick={() => handleRingActionClick(index, itemDerived.item)}
						>
							<Icon {...itemDerived.item.icon} state={itemDerived.iconState} injClass={itemDerived.iconInjClass} />
						</button>
					);
				})}
			</div>
		);
	}

	return (
		<div ref={setInlinePanelRef} className={actionPopoverDerived.inlinePanelClass} style={actionPopoverDerived.inlinePanelStyleValue}>
			{actionPopoverDerived.showTitle ? <div className={actionPopoverDerived.titleClass}>{title}</div> : null}
			<div className={actionPopoverDerived.actionContainerClass}>
				{actionPopoverDerived.actionViewStates.map((actionViewState, index) => {
					const item = actionViewState.item;
					return (
						<div key={`${item.content}-${index}`}>
							<button
								type="button"
								className={actionViewState.buttonClass}
								disabled={actionViewState.disabled}
								onClick={() => handleActionClick(index, item)}
							>
								{actionViewState.showIcon && item.icon ? (
									<Icon {...item.icon} state={actionViewState.iconState} injClass={actionViewState.iconInjClass} />
								) : actionViewState.showImage ? (
									<div className={actionViewState.imageClass}>
										<img className={actionViewState.imageInnerClass} src={item.imgSrc} alt="" />
									</div>
								) : null}
								<div className={actionViewState.contentClass}>
									{item.content}
									{actionViewState.showDesc ? <div className={actionViewState.descClass}>{item.desc}</div> : null}
								</div>
							</button>
							{actionViewState.showDivider ? <div className={actionViewState.dividerClass} /> : null}
						</div>
					);
				})}
			</div>
			{actionPopoverDerived.showCancel ? (
				<>
					<div className={actionPopoverDerived.cancelDividerClass} />
					<button type="button" className={actionPopoverDerived.cancelButtonClass} onClick={handleCancel}>
						{cancelText}
					</button>
				</>
			) : null}
		</div>
	);
};

export default ActionPopover;

// packages/vtdf/src/lib/components/ActionPopover.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue';
import { easingFunctions } from '@any-tdf/vue-motion/easing';
import { useTransition } from '@any-tdf/vue-motion';
import { isBrowser } from '@any-tdf/common/utils';
import {
	resolveActionPopoverActionClickFlow,
	resolveActionPopoverCancelAction,
	resolveActionPopoverCloseAction,
	resolveActionPopoverDerived,
	resolveActionPopoverHideForViewportAction,
	resolveActionPopoverIconProps,
	resolveActionPopoverInlineCloseCompleteAction,
	resolveActionPopoverInlinePositionState,
	resolveActionPopoverInitialVisible,
	resolveActionPopoverMeasuredDimension,
	resolveActionPopoverRenderAction,
	resolveActionPopoverRestoreFromViewportAction,
	resolveActionPopoverRingCloseCompleteAction,
	resolveActionPopoverRingPositionState,
	resolveActionPopoverShouldBindGlobalListeners,
	resolveActionPopoverStateOptions,
	resolveActionPopoverTriggerElement,
	resolveActionPopoverTriggerInViewport,
	resolveActionPopoverViewportAction
} from '@any-tdf/common/derived/actionPopover';
import { resolveActionSheetCancelText } from '@any-tdf/common/derived/actionSheet';
import { resolveViewportDimension, resolveViewportFallbackDimension } from '@any-tdf/common/derived/helpers';
import type { ActionPopoverProps, ActionProps, RingActionProps } from '../types';
import { zh_CN } from '../lang';
import { useConfig } from './adapter/config';
import Icon from './Icon.vue';

const props = withDefaults(defineProps<ActionPopoverProps & {}>(), {
	title: '',
	titleAlign: 'center',
	actions: () => [],
	showCancel: false,
	cancelText: undefined,
	actionClosable: true,
	align: 'center',
	inverse: false,
	layout: 'v',
	gridColumns: 3,
	triggerRef: null,
	inlineAlign: 'center',
	inlineDirection: 'auto',
	inlineOffset: 8,
	inlineShadow: 'md',
	inlineRadius: '',
	ringActions: () => [],
	ringRadius: 0,
	ringItemSize: 44,
	ringShape: 'auto'
});

const emit = defineEmits<{
	'update:visible': [visible: boolean];
	cancel: [];
	clickAction: [index: number, action: ActionProps | RingActionProps];
	close: [];
}>();

const config = useConfig();
const innerVisible = ref(resolveActionPopoverInitialVisible(props.visible));
const shouldRender = ref(resolveActionPopoverInitialVisible(props.visible));
const positionReady = ref(false);
const inlinePosition = ref({ top: 0, left: 0 });
const actualDirection = ref<'up' | 'down'>('down');
const ringPosition = ref({ x: 0, y: 0 });
const computedRingShape = ref<'full' | 'half' | 'quarter'>('quarter');
const ringStartAngle = ref(0);
const ringAnimate = ref(false);
const hiddenByViewport = ref(false);
const panelRef = ref<HTMLDivElement | null>(null);
const positionFrame = ref<number | null>(null);
const ringAnimationFrame = ref<number | null>(null);
const ringCloseTimer = ref<ReturnType<typeof setTimeout> | null>(null);

const actionPopoverLang = computed(() => config.locale?.actionSheet || zh_CN.actionSheet);
const cancelText = computed(() => resolveActionSheetCancelText(props.cancelText, actionPopoverLang.value));

type VueTriggerRefLike = HTMLElement | { current?: HTMLElement | null } | { value?: HTMLElement | null } | null | undefined;

const resolveTriggerElement = (): HTMLElement | null => {
	const triggerRef = props.triggerRef as VueTriggerRefLike;
	if (isBrowser && triggerRef instanceof HTMLElement) return triggerRef;
	if (triggerRef && typeof triggerRef === 'object' && 'value' in triggerRef) return triggerRef.value ?? null;
	return resolveActionPopoverTriggerElement<HTMLElement>(triggerRef as HTMLElement | { current?: HTMLElement | null } | null | undefined);
};

// 公共派生层只处理 ActionPopover class、style 和过渡参数，DOM 读取与事件留在组件内。
// Shared derived layer only handles ActionPopover classes, styles and transition params; DOM reads and events stay in the component.
const actionPopoverDerived = computed(() =>
	resolveActionPopoverDerived<ActionProps, RingActionProps>(
		resolveActionPopoverStateOptions<ActionProps, RingActionProps>({
			props: {
				actions: props.actions,
				align: props.align,
				gridColumns: props.gridColumns,
				inlineAlign: props.inlineAlign,
				inlineRadius: props.inlineRadius,
				inlineShadow: props.inlineShadow,
				inverse: props.inverse,
				layout: props.layout,
				ringActions: props.ringActions,
				ringItemSize: props.ringItemSize,
				ringRadius: props.ringRadius,
				showCancel: props.showCancel,
				title: props.title,
				titleAlign: props.titleAlign,
				visible: props.visible
			},
			actualDirection: actualDirection.value,
			computedRingShape: computedRingShape.value,
			hiddenByViewport: hiddenByViewport.value,
			inlinePosition: inlinePosition.value,
			innerVisible: innerVisible.value,
			positionReady: positionReady.value,
			ringAnimate: ringAnimate.value,
			ringPosition: ringPosition.value,
			ringStartAngle: ringStartAngle.value
		})
	)
);
const visible = computed(() => actionPopoverDerived.value.visible);
const inlineVisible = computed(() => actionPopoverDerived.value.inlineVisible);

const inlineTransition = useTransition(
	() => inlineVisible.value,
	() => ({
		transition: 'scale',
		inParams: {
			...actionPopoverDerived.value.inlineInParams,
			easing: easingFunctions.cubicOut
		},
		outParams: {
			...actionPopoverDerived.value.inlineOutParams,
			easing: easingFunctions.cubicOut
		},
		onOutroEnd: () => {
			if (props.layout === 'ring') return;
			const action = resolveActionPopoverInlineCloseCompleteAction();
			positionReady.value = action.nextPositionReady;
			shouldRender.value = action.nextShouldRender;
		}
	})
);

const setInlinePanelRef = (node: unknown) => {
	const panelNode = node instanceof HTMLDivElement ? node : null;
	panelRef.value = panelNode;
	inlineTransition.ref.value = panelNode;
	if (panelNode && visible.value && shouldRender.value && props.layout !== 'ring' && !positionReady.value) {
		schedulePosition();
	}
};

const clearFrames = () => {
	if (positionFrame.value !== null) {
		cancelAnimationFrame(positionFrame.value);
		positionFrame.value = null;
	}
	if (ringAnimationFrame.value !== null) {
		cancelAnimationFrame(ringAnimationFrame.value);
		ringAnimationFrame.value = null;
	}
	if (ringCloseTimer.value) {
		clearTimeout(ringCloseTimer.value);
		ringCloseTimer.value = null;
	}
};

const emitVisible = (nextVisible: boolean) => {
	hiddenByViewport.value = false;
	innerVisible.value = nextVisible;
	emit('update:visible', nextVisible);
};

const setViewportHidden = (nextHidden: boolean) => {
	hiddenByViewport.value = nextHidden;
};

const emitClose = () => {
	emit('close');
};

const emitCancel = () => {
	emit('cancel');
};

const emitClickAction = (index: number, item: ActionProps | RingActionProps) => {
	emit('clickAction', index, item);
};

const closePanel = () => {
	const action = resolveActionPopoverCloseAction();
	if (action.shouldClose) emitVisible(action.nextVisible);
	if (action.shouldEmitClose) emitClose();
};

const calculateRingLayout = () => {
	const triggerElement = resolveTriggerElement();
	if (!triggerElement || props.layout !== 'ring') return false;
	const triggerRect = triggerElement.getBoundingClientRect();
	if (!triggerRect.width || !triggerRect.height) return false;
	const viewportWidth = resolveViewportDimension({ value: window.innerWidth });
	const viewportHeight = resolveViewportDimension({ value: window.innerHeight });
	// 公共位置派生只消费测量结果，DOM 读取保留在组件内。
	// Shared position derivation consumes measurements only; DOM reads stay in the component.
	const positionState = resolveActionPopoverRingPositionState({
		triggerRect,
		viewportWidth,
		viewportHeight,
		itemCount: props.ringActions.length,
		ringShape: props.ringShape
	});
	ringPosition.value = positionState.ringPosition;
	computedRingShape.value = positionState.computedRingShape;
	ringStartAngle.value = positionState.ringStartAngle;
	return true;
};

const calculateInlinePosition = () => {
	const triggerElement = resolveTriggerElement();
	if (!triggerElement || !panelRef.value) return false;
	const triggerRect = triggerElement.getBoundingClientRect();
	const panelRect = panelRef.value.getBoundingClientRect();
	const panelWidth = resolveActionPopoverMeasuredDimension({
		measured: panelRef.value.offsetWidth,
		fallback: panelRect.width
	});
	const panelHeight = resolveActionPopoverMeasuredDimension({
		measured: panelRef.value.offsetHeight,
		fallback: panelRect.height
	});
	if (!triggerRect.width || !triggerRect.height || !panelWidth || !panelHeight) return false;
	const viewportHeight = resolveViewportDimension({ value: window.innerHeight });
	const viewportWidth = resolveViewportDimension({ value: window.innerWidth });

	const positionState = resolveActionPopoverInlinePositionState({
		triggerRect,
		panelWidth,
		panelHeight,
		viewportWidth,
		viewportHeight,
		inlineAlign: props.inlineAlign,
		inlineDirection: props.inlineDirection,
		inlineOffset: props.inlineOffset
	});
	actualDirection.value = positionState.actualDirection;
	inlinePosition.value = positionState.inlinePosition;
	return true;
};

const updatePosition = () => {
	if (props.layout === 'ring') return calculateRingLayout();
	return calculateInlinePosition();
};

const isTriggerInViewport = () => {
	const triggerElement = resolveTriggerElement();
	if (!triggerElement) return false;
	const triggerRect = triggerElement.getBoundingClientRect();
	const viewportWidth = resolveViewportFallbackDimension({
		value: window.innerWidth,
		fallback: document.documentElement.clientWidth
	});
	const viewportHeight = resolveViewportFallbackDimension({
		value: window.innerHeight,
		fallback: document.documentElement.clientHeight
	});
	return resolveActionPopoverTriggerInViewport({ triggerRect, viewportWidth, viewportHeight });
};

const hideForViewport = () => {
	const action = resolveActionPopoverHideForViewportAction({
		visible: visible.value,
		hiddenByViewport: hiddenByViewport.value
	});
	if (!action.shouldChange) return;
	setViewportHidden(action.nextHiddenByViewport);
};

const restoreFromViewport = () => {
	const action = resolveActionPopoverRestoreFromViewportAction({
		hiddenByViewport: hiddenByViewport.value,
		triggerInViewport: isTriggerInViewport()
	});
	if (!action.shouldChange) return;
	setViewportHidden(action.nextHiddenByViewport);
};

const schedulePosition = async () => {
	if (!isBrowser) return;
	clearFrames();
	await nextTick();
	const runPosition = (attempt = 0) => {
		positionFrame.value = requestAnimationFrame(() => {
			positionFrame.value = null;
			const nextReady = props.layout === 'ring' ? calculateRingLayout() : calculateInlinePosition();
			if (!nextReady) {
				if (attempt < 4) runPosition(attempt + 1);
				return;
			}
			positionReady.value = true;
			if (props.layout === 'ring') {
				ringAnimationFrame.value = requestAnimationFrame(() => {
					ringAnimationFrame.value = null;
					ringAnimate.value = true;
				});
			}
		});
	};
	runPosition();
};

const handleClickOutside = (event: MouseEvent) => {
	if (!visible.value) return;
	const target = event.target as Node;
	const triggerElement = resolveTriggerElement();
	if (panelRef.value && !panelRef.value.contains(target) && triggerElement && !triggerElement.contains(target)) {
		closePanel();
	}
};

const handleCancel = () => {
	// 公共动作函数只返回状态和回调决策，组件层负责写入状态和触发事件。
	// Shared action function only returns state and callback decisions; the component writes state and fires events.
	const action = resolveActionPopoverCancelAction();
	emitVisible(action.nextVisible);
	if (action.shouldCancel) emitCancel();
	if (action.shouldClose) emitClose();
};

const handleActionClick = (index: number, item: ActionProps) => {
	const action = resolveActionPopoverActionClickFlow({
		action: item,
		actionClosable: props.actionClosable,
		index
	});
	if (!action.shouldSelect) return;
	emitClickAction(action.index, action.action);
	if (action.closeAction.shouldClose) {
		emitVisible(action.closeAction.nextVisible);
		if (action.closeAction.shouldEmitClose) emitClose();
	}
};

const handleRingActionClick = (index: number, item: RingActionProps) => {
	const action = resolveActionPopoverActionClickFlow({
		action: item,
		actionClosable: props.actionClosable,
		index
	});
	if (!action.shouldSelect) return;
	emitClickAction(action.index, action.action);
	if (action.closeAction.shouldClose) {
		emitVisible(action.closeAction.nextVisible);
		if (action.closeAction.shouldEmitClose) emitClose();
	}
};

watch(
	() => props.visible,
	(nextVisible) => {
		if (nextVisible !== undefined) {
			hiddenByViewport.value = false;
			innerVisible.value = resolveActionPopoverInitialVisible(nextVisible);
		}
	}
);

watch(
	visible,
	(nextVisible, _previousVisible, onCleanup) => {
		clearFrames();
		// 公共 action 只决定渲染生命周期，timer 和响应式写入留在组件层。
		// Shared action only decides the render lifecycle; timers and reactive writes stay in the component layer.
		const renderAction = resolveActionPopoverRenderAction({
			visible: nextVisible,
			layout: props.layout,
			shouldRender: shouldRender.value,
			positionReady: positionReady.value
		});
		if (renderAction.kind === 'keepInlineOutro') {
			return;
		}
		shouldRender.value = renderAction.nextShouldRender;
		ringAnimate.value = renderAction.nextRingAnimate;
		positionReady.value = renderAction.nextPositionReady;
		if (renderAction.shouldSchedulePosition) {
			schedulePosition();
			return;
		}
		if (renderAction.shouldScheduleRingClose) {
			ringCloseTimer.value = setTimeout(() => {
				const completeAction = resolveActionPopoverRingCloseCompleteAction();
				positionReady.value = completeAction.nextPositionReady;
				shouldRender.value = completeAction.nextShouldRender;
			}, renderAction.ringCloseDelayMs);
			onCleanup(() => {
				if (ringCloseTimer.value) {
					clearTimeout(ringCloseTimer.value);
					ringCloseTimer.value = null;
				}
			});
		}
	},
	{ immediate: true }
);

watch(
	() =>
		[
			props.layout,
			props.triggerRef,
			props.inlineAlign,
			props.inlineDirection,
			props.inlineOffset,
			props.ringActions.length,
			props.ringShape
		] as const,
	() => {
		if (visible.value && shouldRender.value) {
			schedulePosition();
		}
	}
);

watch(
	() => [visible.value, hiddenByViewport.value],
	([nextVisible, viewportHidden], _previous, onCleanup) => {
		if (!isBrowser) return;
		if (
			!resolveActionPopoverShouldBindGlobalListeners({
				visible: nextVisible,
				hiddenByViewport: viewportHidden
			})
		)
			return;
		let frameId = 0;
		const updateOrHide = () => {
			cancelAnimationFrame(frameId);
			frameId = requestAnimationFrame(() => {
				const viewportAction = resolveActionPopoverViewportAction({
					triggerInViewport: isTriggerInViewport(),
					hiddenByViewport: hiddenByViewport.value
				});
				if (viewportAction === 'hideForViewport') {
					hideForViewport();
					return;
				}
				if (viewportAction === 'restoreFromViewport') {
					restoreFromViewport();
					return;
				}
				updatePosition();
			});
		};
		const clickTimer = nextVisible ? setTimeout(() => document.addEventListener('click', handleClickOutside), 0) : null;
		window.addEventListener('scroll', updateOrHide, true);
		window.addEventListener('resize', updateOrHide);
		updateOrHide();

		onCleanup(() => {
			cancelAnimationFrame(frameId);
			if (clickTimer) clearTimeout(clickTimer);
			document.removeEventListener('click', handleClickOutside);
			window.removeEventListener('scroll', updateOrHide, true);
			window.removeEventListener('resize', updateOrHide);
		});
	}
);

onBeforeUnmount(() => {
	clearFrames();
	if (!isBrowser) return;
	document.removeEventListener('click', handleClickOutside);
});
</script>

<template>
	<div
		v-if="shouldRender && layout === 'ring' && positionReady"
		ref="panelRef"
		:class="actionPopoverDerived.ringPanelClass"
		:style="actionPopoverDerived.ringPanelStyleString"
	>
		<button
			v-for="(ringItem, index) in actionPopoverDerived.ringItemDerivedList"
			:key="`ring-${index}`"
			type="button"
			:class="ringItem.buttonClass"
			:style="ringItem.styleString"
			:disabled="ringItem.disabled"
			@click="handleRingActionClick(index, ringItem.item)"
		>
			<Icon v-bind="ringItem.item.icon" :state="ringItem.iconState" :inj-class="ringItem.iconInjClass" />
		</button>
	</div>

	<div
		v-else-if="shouldRender && layout !== 'ring' && inlineTransition.shouldRender.value"
		:ref="setInlinePanelRef"
		:class="actionPopoverDerived.inlinePanelClass"
		:style="actionPopoverDerived.inlinePanelStyleString"
	>
		<div v-if="actionPopoverDerived.showTitle" :class="actionPopoverDerived.titleClass">
			{{ title }}
		</div>
		<div :class="actionPopoverDerived.actionContainerClass">
			<template v-for="(actionViewState, index) in actionPopoverDerived.actionViewStates" :key="`${actionViewState.item.content}-${index}`">
				<button
					type="button"
					:class="actionViewState.buttonClass"
					:disabled="actionViewState.disabled"
					@click="handleActionClick(index, actionViewState.item)"
				>
					<Icon
						v-if="actionViewState.showIcon"
						v-bind="resolveActionPopoverIconProps(actionViewState.item.icon)"
						:state="actionViewState.iconState"
						:inj-class="actionViewState.iconInjClass"
					/>
					<div v-else-if="actionViewState.showImage" :class="actionViewState.imageClass">
						<img :class="actionViewState.imageInnerClass" :src="actionViewState.item.imgSrc" alt="" />
					</div>
					<div :class="actionViewState.contentClass">
						{{ actionViewState.item.content }}
						<div v-if="actionViewState.showDesc" :class="actionViewState.descClass">
							{{ actionViewState.item.desc }}
						</div>
					</div>
				</button>
				<div v-if="actionViewState.showDivider" :class="actionViewState.dividerClass" />
			</template>
		</div>
		<template v-if="actionPopoverDerived.showCancel">
			<div :class="actionPopoverDerived.cancelDividerClass" />
			<button type="button" :class="actionPopoverDerived.cancelButtonClass" @click="handleCancel">
				{{ cancelText }}
			</button>
		</template>
	</div>
</template>
