// packages/stdf/src/lib/components/fullKeyboard/FullKeyboard.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import Popup from '../popup/Popup.svelte';
	import { zh_CN, type LangProps } from '../../lang/index.js';
	import type { FullKeyboardProps } from '../../types/index.js';
	import {
		fullKeyboardLetterRows,
		fullKeyboardNumberRow,
		fullKeyboardSymbolRows,
		resolveFullKeyboardCaseToggleAction,
		resolveFullKeyboardDerived,
		resolveFullKeyboardInputKey,
		resolveFullKeyboardKeyFlow,
		resolveFullKeyboardStateOptions,
		resolveFullKeyboardSymbolModeToggleAction,
		resolveFullKeyboardTexts,
		resolveFullKeyboardUsePopup,
		resolveFullKeyboardVisibleChangeFlow
	} from '@any-tdf/common/derived/fullKeyboard';
	import { fullKeyboardShiftSvg } from '@any-tdf/common/svg/fullKeyboard';
	import { numKeyboardDeleteSvg } from '@any-tdf/common/svg/numKeyboard';
	import SvgIcon from '../utils/SvgIcon.svelte';

	// 当前语言
	// current language
	const currentLang = (getContext('STDF_lang') || zh_CN) as LangProps;
	const commonLang: LangProps['common'] = currentLang.common;
	const fullKeyboardLang = currentLang.fullKeyboard || zh_CN.fullKeyboard;

	let {
		value = $bindable(''),
		visible = $bindable(true),
		type = 'button',
		mode = 'full',
		done = true,
		doneText,
		doneDisabled = $bindable(false),
		radius = '',
		preview = false,
		previewMask = false,
		panelClass = '',
		keyClass: keyClassProp = '',
		doneClass = '',
		popup = {},
		onclick,
		onopen,
		onclose
	}: FullKeyboardProps = $props();

	// 是否使用弹出层，当 popup 为 null 时不使用
	// Whether to use popup, when popup is null, do not use
	const usePopup = $derived(resolveFullKeyboardUsePopup(popup));
	const keyboardTexts = $derived(resolveFullKeyboardTexts({ doneText, defaults: { common: commonLang, fullKeyboard: fullKeyboardLang } }));

	// 是否大写模式
	// Whether uppercase mode
	let isUpperCase = $state(false);

	// 是否符号模式（用于 full 模式下切换字母/数字符号）
	// Whether symbol mode (for switching between letters and numbers/symbols in full mode)
	let isSymbolMode = $state(false);
	let previousVisible = $state<boolean | undefined>(undefined);

	const [letterRow1, letterRow2, letterRow3] = fullKeyboardLetterRows;
	const numberRow = fullKeyboardNumberRow;
	const symbolRow4 = fullKeyboardSymbolRows[3];

	// 公共派生层只处理 FullKeyboard 的按键、面板和布局 class，输入事件留在组件内。
	// Shared derived layer only handles FullKeyboard key, panel and layout classes; input events stay in the component.
	const keyboardState = $derived(
		resolveFullKeyboardDerived(
			resolveFullKeyboardStateOptions({
				props: {
					done,
					doneClass,
					keyClass: keyClassProp,
					mode,
					panelClass,
					popup,
					preview,
					previewMask,
					radius,
					type
				},
				doneDisabled,
				isSymbolMode,
				isUpperCase,
				value
			})
		)
	);

	// 点击按键事件
	// Click key event
	const clickKey = (key: string) => {
		// 公共 flow 返回输入值、事件键和关闭动作，事件派发仍留在组件层。
		// Shared flow returns input value, emit key and close action; event dispatch stays in the component layer.
		const flow = resolveFullKeyboardKeyFlow({ value, key, isUpperCase, doneDisabled, closeOptions: { emitClose: false } });
		if (flow.shouldUpdateValue) {
			value = flow.nextValue;
		}
		if (flow.shouldEmit) {
			onclick?.(flow.emitKey);
		}
		if (flow.closeAction) {
			if (flow.closeAction.shouldClose) visible = flow.closeAction.nextVisible;
			if (flow.closeAction.shouldEmitClose) onclose?.();
		}
	};

	// 点击删除
	// Click delete
	const clickDelete = () => {
		clickKey('delete');
	};

	// 点击空格
	// Click space
	const clickSpace = () => {
		clickKey(' ');
	};

	// 点击完成
	// Click done
	const clickDone = () => {
		clickKey('done');
	};

	// 切换大小写
	// Toggle uppercase
	const toggleCase = () => {
		const action = resolveFullKeyboardCaseToggleAction(isUpperCase);
		isUpperCase = action.nextUpperCase;
	};

	// 切换符号模式
	// Toggle symbol mode
	const toggleSymbolMode = () => {
		const action = resolveFullKeyboardSymbolModeToggleAction(isSymbolMode);
		isSymbolMode = action.nextSymbolMode;
	};

	// 激活与关闭键盘事件
	// Activate and close the keyboard event
	$effect(() => {
		// 公共 visibility flow 只判断可见性回调，事件派发仍在组件层。
		// Shared visibility flow only decides visibility callbacks; event emits stay in the component layer.
		const flow = resolveFullKeyboardVisibleChangeFlow({ visible, previousVisible, keyboardHeight: keyboardState.keyboardHeight });
		if (flow.shouldSkip) return;
		previousVisible = flow.nextPreviousVisible;
		if (flow.shouldEmitOpen) {
			onopen?.(flow.openHeight);
		}
		if (flow.shouldEmitClose) {
			onclose?.();
		}
	});
</script>

{#snippet shiftKey()}
	<button
		class={keyboardState.shiftButtonClass}
		onclick={toggleCase}
		aria-label="shift"
	>
		<!-- 公共 FullKeyboard SVG 数据在 common 中维护，大小写状态仍在组件内。 / Shared FullKeyboard SVG data lives in common while case state stays here. -->
		<SvgIcon svg={fullKeyboardShiftSvg} width="18" height="16" class={keyboardState.iconClass} />
	</button>
{/snippet}

{#snippet deleteKey()}
	<button class={keyboardState.deleteButtonClass} onclick={clickDelete} aria-label="delete">
		<SvgIcon svg={numKeyboardDeleteSvg} width="22" height="22" class={keyboardState.iconClass} />
	</button>
{/snippet}

{#snippet letterRows()}
	<div class={keyboardState.gridRow10Class}>
		{#each letterRow1 as key (key)}
			<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>
				{resolveFullKeyboardInputKey(key, isUpperCase)}
			</button>
		{/each}
	</div>
	<div class={keyboardState.gridRow9PxClass}>
		{#each letterRow2 as key (key)}
			<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>
				{resolveFullKeyboardInputKey(key, isUpperCase)}
			</button>
		{/each}
	</div>
	<div class={keyboardState.flexRowClass}>
		{@render shiftKey()}
		<div class={keyboardState.innerGrid7Class}>
			{#each letterRow3 as key (key)}
				<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>
					{resolveFullKeyboardInputKey(key, isUpperCase)}
				</button>
			{/each}
		</div>
		{@render deleteKey()}
	</div>
{/snippet}

{#snippet keyboardContent()}
	<div class={keyboardState.panelClass}>
		{#if preview}
			<!-- 输入预览区 -->
			<!-- Input preview area -->
			<div class={keyboardState.previewClass}>
				{#if keyboardState.previewState.showMask}
					{#each keyboardState.previewState.maskIndexes as index (index)}
						<span class={keyboardState.previewState.dotClass}></span>
					{/each}
				{:else}
					{keyboardState.previewState.displayValue}
				{/if}
			</div>
		{/if}

		{#if keyboardState.layout.showLetterMode}
			<!-- 纯字母模式 -->
			<!-- Letter only mode -->
			{@render letterRows()}
			<!-- 底部行：空格、完成 -->
			<div class={keyboardState.bottomRowClass}>
				<button class={keyboardState.flex1KeyClass} onclick={clickSpace}>
					<span class={keyboardState.spaceTextClass}>{keyboardTexts.spaceText}</span>
				</button>
				{#if keyboardState.layout.showDoneButton}
					<button
						class={keyboardState.doneButtonClass}
						onclick={clickDone}
					>
						{keyboardTexts.doneText}
					</button>
				{/if}
			</div>

		{:else if keyboardState.layout.showLetterNumberMode}
			<!-- 字母+数字模式：数字在字母上方一行 -->
			<!-- Letter + Number mode: numbers in a row above letters -->
			<div class={keyboardState.gridRow10Class}>
				{#each numberRow as key (key)}
					<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>{key}</button>
				{/each}
			</div>
			{@render letterRows()}
			<!-- 底部行：空格、完成 -->
			<div class={keyboardState.bottomRowClass}>
				<button class={keyboardState.flex1KeyClass} onclick={clickSpace}>
					<span class={keyboardState.spaceTextClass}>{keyboardTexts.spaceText}</span>
				</button>
				{#if keyboardState.layout.showDoneButton}
					<button
						class={keyboardState.doneButtonClass}
						onclick={clickDone}
					>
						{keyboardTexts.doneText}
					</button>
				{/if}
			</div>

		{:else}
			<!-- full 模式：字母+数字+符号，可切换 -->
			<!-- Full mode: letters + numbers + symbols, switchable -->
			{#if keyboardState.layout.showSymbolRows}
				<!-- 数字符号模式 -->
				<!-- Number symbol mode -->
				{#each keyboardState.layout.symbolMainRows as row, rowIndex (rowIndex)}
					<div class={keyboardState.gridRow10Class}>
						{#each row as key (key)}
							<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>{key}</button>
						{/each}
					</div>
				{/each}
				<div class={keyboardState.flexRowClass}>
					<div class={keyboardState.innerGrid9Class}>
						{#each symbolRow4 as key (key)}
							<button class={keyboardState.keyButtonClass} onclick={() => clickKey(key)}>{key}</button>
						{/each}
					</div>
					{@render deleteKey()}
				</div>
			{:else}
				<!-- 字母模式 -->
				<!-- Letter mode -->
				{@render letterRows()}
			{/if}

			<!-- 底部行：123/ABC、<>/? (符号模式)、空格、完成 -->
			<!-- Bottom row: 123/ABC, <>/? (symbol mode), space, done -->
			<div class={keyboardState.bottomRowClass}>
				<button class={keyboardState.symbolToggleButtonClass} onclick={toggleSymbolMode}>
					{keyboardState.symbolToggleText}
				</button>
				{#each keyboardState.layout.bottomSymbolKeys as key (key)}
					<button class={keyboardState.symbolKeyClass} onclick={() => clickKey(key)}>{key}</button>
				{/each}
				<button class={keyboardState.flex1KeyClass} onclick={clickSpace}>
					<span class={keyboardState.spaceTextClass}>{keyboardTexts.spaceText}</span>
				</button>
				{#if keyboardState.layout.showDoneButton}
					<button
						class={keyboardState.doneButtonClass}
						onclick={clickDone}
					>
						{keyboardTexts.doneText}
					</button>
				{/if}
			</div>
		{/if}
	</div>
{/snippet}

{#if usePopup}
	<Popup bind:visible {...keyboardState.popupProps}>
		{@render keyboardContent()}
	</Popup>
{:else}
	{@render keyboardContent()}
{/if}

// packages/vtdf/src/lib/components/FullKeyboard.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { FullKeyboardProps } from '../types';
import {
	fullKeyboardLetterRows,
	fullKeyboardNumberRow,
	fullKeyboardSymbolRows,
	resolveFullKeyboardCaseToggleAction,
	resolveFullKeyboardCloseAction,
	resolveFullKeyboardDerived,
	resolveFullKeyboardInitialValue,
	resolveFullKeyboardInitialVisible,
	resolveFullKeyboardInputKey,
	resolveFullKeyboardKeyFlow,
	resolveFullKeyboardRootProps,
	resolveFullKeyboardStateOptions,
	resolveFullKeyboardSymbolModeToggleAction,
	resolveFullKeyboardTexts,
	resolveFullKeyboardUsePopup,
	resolveFullKeyboardVisibleChangeFlow
} from '@any-tdf/common/derived/fullKeyboard';
import { fullKeyboardShiftSvg } from '@any-tdf/common/svg/fullKeyboard';
import { numKeyboardDeleteSvg } from '@any-tdf/common/svg/numKeyboard';
import { zh_CN } from '../lang';
import { useConfig } from './adapter/config';
import Popup from './Popup.vue';
import SvgIcon from './SvgIcon.vue';

const props = withDefaults(defineProps<FullKeyboardProps & {}>(), {
	value: '',
	visible: true,
	type: 'button',
	mode: 'full',
	done: true,
	doneDisabled: false,
	radius: '',
	preview: false,
	previewMask: false,
	panelClass: '',
	keyClass: '',
	doneClass: '',
	popup: () => ({})
});

const emit = defineEmits<{
	'update:value': [value: string];
	'update:visible': [visible: boolean];
	click: [key: string];
	open: [height: number];
	close: [];
}>();

const config = useConfig();
const innerValue = ref(resolveFullKeyboardInitialValue(props.value));
const innerVisible = ref(resolveFullKeyboardInitialVisible(props.visible));
const previousVisible = ref<boolean | undefined>(undefined);
const isUpperCase = ref(false);
const isSymbolMode = ref(false);

const [letterRow1, letterRow2, letterRow3] = fullKeyboardLetterRows;
const numberRow = fullKeyboardNumberRow;
const symbolRow4 = fullKeyboardSymbolRows[3];
const usePopup = computed(() => resolveFullKeyboardUsePopup(props.popup));
const fullKeyboardLang = computed(() => config.locale.fullKeyboard || zh_CN.fullKeyboard);
const keyboardTexts = computed(() =>
	resolveFullKeyboardTexts({
		doneText: props.doneText,
		defaults: { common: config.locale.common, fullKeyboard: fullKeyboardLang.value }
	})
);
// 公共派生层只处理 FullKeyboard 的按键、面板和布局 class，输入事件留在组件内。
// Shared derived layer only handles FullKeyboard key, panel and layout classes; input events stay in the component.
const keyboardState = computed(() =>
	resolveFullKeyboardDerived(
		resolveFullKeyboardStateOptions({
			props: {
				done: props.done,
				doneClass: props.doneClass,
				keyClass: props.keyClass,
				mode: props.mode,
				panelClass: props.panelClass,
				popup: props.popup,
				preview: props.preview,
				previewMask: props.previewMask,
				radius: props.radius,
				type: props.type
			},
			doneDisabled: props.doneDisabled,
			isSymbolMode: isSymbolMode.value,
			isUpperCase: isUpperCase.value,
			value: innerValue.value
		})
	)
);
const rootProps = computed(() =>
	resolveFullKeyboardRootProps({
		usePopup: usePopup.value,
		visible: innerVisible.value,
		popupProps: keyboardState.value.popupProps
	})
);

const syncValue = (value: string) => {
	innerValue.value = value;
	emit('update:value', value);
};

const emitClose = () => {
	emit('close');
};

const setVisible = (visible: boolean) => {
	innerVisible.value = visible;
	emit('update:visible', visible);
};

const emitClick = (key: string) => {
	emit('click', key);
};

const clickKey = (key: string) => {
	// 公共 flow 返回输入值、事件键和关闭动作，事件派发仍留在组件层。
	// Shared flow returns input value, emit key and close action; event dispatch stays in the component layer.
	const flow = resolveFullKeyboardKeyFlow({
		value: innerValue.value,
		key,
		isUpperCase: isUpperCase.value,
		doneDisabled: props.doneDisabled,
		closeOptions: { emitClose: false }
	});
	if (flow.shouldUpdateValue) {
		syncValue(flow.nextValue);
	}
	if (flow.shouldEmit) {
		emitClick(flow.emitKey);
	}
	if (flow.closeAction) {
		if (flow.closeAction.shouldClose) setVisible(flow.closeAction.nextVisible);
		if (flow.closeAction.shouldEmitClose) emitClose();
	}
};

const clickDelete = () => {
	clickKey('delete');
};

const clickSpace = () => {
	clickKey(' ');
};

const clickDone = () => {
	clickKey('done');
};

const toggleCase = () => {
	const action = resolveFullKeyboardCaseToggleAction(isUpperCase.value);
	isUpperCase.value = action.nextUpperCase;
};

const toggleSymbolMode = () => {
	const action = resolveFullKeyboardSymbolModeToggleAction(isSymbolMode.value);
	isSymbolMode.value = action.nextSymbolMode;
};

const handlePopupClose = () => {
	// 公共 close action 只返回可见状态，Popup 关闭事件交给组件层同步。
	// Shared close action only returns visibility state; Popup close synchronization stays in the component layer.
	const action = resolveFullKeyboardCloseAction({ emitClose: false });
	if (action.shouldClose) setVisible(action.nextVisible);
	if (action.shouldEmitClose) emitClose();
};

watch(
	() => props.value,
	(value) => {
		innerValue.value = resolveFullKeyboardInitialValue(value);
	}
);

watch(
	() => props.visible,
	(visible) => {
		innerVisible.value = resolveFullKeyboardInitialVisible(visible);
	}
);

watch(
	innerVisible,
	(visible) => {
		// 公共 visibility flow 只判断可见性回调，响应式写入和 emit 留在组件层。
		// Shared visibility flow only decides visibility callbacks; reactive writes and emits stay in the component layer.
		const flow = resolveFullKeyboardVisibleChangeFlow({
			visible,
			previousVisible: previousVisible.value,
			keyboardHeight: keyboardState.value.keyboardHeight
		});
		if (flow.shouldSkip) return;
		previousVisible.value = flow.nextPreviousVisible;
		if (flow.shouldEmitOpen) {
			emit('open', flow.openHeight);
			return;
		}
		if (flow.shouldEmitClose) {
			emitClose();
		}
	},
	{ immediate: true }
);
</script>

<template>
	<component :is="usePopup ? Popup : 'div'" v-bind="rootProps" @close="handlePopupClose">
		<div :class="keyboardState.panelClass">
			<div v-if="preview" :class="keyboardState.previewClass">
				<template v-if="keyboardState.previewState.showMask">
					<span v-for="index in keyboardState.previewState.maskIndexes" :key="index" :class="keyboardState.previewState.dotClass" />
				</template>
				<template v-else>{{ keyboardState.previewState.displayValue }}</template>
			</div>

			<template v-if="keyboardState.layout.showLetterMode">
				<div :class="keyboardState.gridRow10Class">
					<button v-for="key in letterRow1" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
						{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
					</button>
				</div>
				<div :class="keyboardState.gridRow9PxClass">
					<button v-for="key in letterRow2" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
						{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
					</button>
				</div>
				<div :class="keyboardState.flexRowClass">
					<button type="button" :class="keyboardState.shiftButtonClass" aria-label="shift" @click="toggleCase">
						<!-- 公共 FullKeyboard SVG 数据在 common 中维护。 / Shared FullKeyboard SVG data lives in common. -->
						<SvgIcon :svg="fullKeyboardShiftSvg" width="18" height="16" :class-name="keyboardState.iconClass" />
					</button>
					<div :class="keyboardState.innerGrid7Class">
						<button v-for="key in letterRow3" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
							{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
						</button>
					</div>
					<button type="button" :class="keyboardState.deleteButtonClass" aria-label="delete" @click="clickDelete">
						<SvgIcon :svg="numKeyboardDeleteSvg" width="22" height="22" :class-name="keyboardState.iconClass" />
					</button>
				</div>
				<div :class="keyboardState.bottomRowClass">
					<button type="button" :class="keyboardState.flex1KeyClass" @click="clickSpace">
						<span :class="keyboardState.spaceTextClass">{{ keyboardTexts.spaceText }}</span>
					</button>
					<button
						v-if="keyboardState.layout.showDoneButton"
						type="button"
						:class="keyboardState.doneButtonClass"
						:disabled="doneDisabled"
						@click="clickDone"
					>
						{{ keyboardTexts.doneText }}
					</button>
				</div>
			</template>

			<template v-else-if="keyboardState.layout.showLetterNumberMode">
				<div :class="keyboardState.gridRow10Class">
					<button v-for="key in numberRow" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
						{{ key }}
					</button>
				</div>
				<div :class="keyboardState.gridRow10Class">
					<button v-for="key in letterRow1" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
						{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
					</button>
				</div>
				<div :class="keyboardState.gridRow9PxClass">
					<button v-for="key in letterRow2" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
						{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
					</button>
				</div>
				<div :class="keyboardState.flexRowClass">
					<button type="button" :class="keyboardState.shiftButtonClass" aria-label="shift" @click="toggleCase">
						<SvgIcon :svg="fullKeyboardShiftSvg" width="18" height="16" :class-name="keyboardState.iconClass" />
					</button>
					<div :class="keyboardState.innerGrid7Class">
						<button v-for="key in letterRow3" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
							{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
						</button>
					</div>
					<button type="button" :class="keyboardState.deleteButtonClass" aria-label="delete" @click="clickDelete">
						<SvgIcon :svg="numKeyboardDeleteSvg" width="22" height="22" :class-name="keyboardState.iconClass" />
					</button>
				</div>
				<div :class="keyboardState.bottomRowClass">
					<button type="button" :class="keyboardState.flex1KeyClass" @click="clickSpace">
						<span :class="keyboardState.spaceTextClass">{{ keyboardTexts.spaceText }}</span>
					</button>
					<button
						v-if="keyboardState.layout.showDoneButton"
						type="button"
						:class="keyboardState.doneButtonClass"
						:disabled="doneDisabled"
						@click="clickDone"
					>
						{{ keyboardTexts.doneText }}
					</button>
				</div>
			</template>

			<template v-else>
				<template v-if="keyboardState.layout.showSymbolRows">
					<div v-for="(row, rowIndex) in keyboardState.layout.symbolMainRows" :key="rowIndex" :class="keyboardState.gridRow10Class">
						<button v-for="key in row" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
							{{ key }}
						</button>
					</div>
					<div :class="keyboardState.flexRowClass">
						<div :class="keyboardState.innerGrid9Class">
							<button v-for="key in symbolRow4" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
								{{ key }}
							</button>
						</div>
						<button type="button" :class="keyboardState.deleteButtonClass" aria-label="delete" @click="clickDelete">
							<SvgIcon :svg="numKeyboardDeleteSvg" width="22" height="22" :class-name="keyboardState.iconClass" />
						</button>
					</div>
				</template>
				<template v-else>
					<div :class="keyboardState.gridRow10Class">
						<button v-for="key in letterRow1" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
							{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
						</button>
					</div>
					<div :class="keyboardState.gridRow9PxClass">
						<button v-for="key in letterRow2" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
							{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
						</button>
					</div>
					<div :class="keyboardState.flexRowClass">
						<button type="button" :class="keyboardState.shiftButtonClass" aria-label="shift" @click="toggleCase">
							<SvgIcon :svg="fullKeyboardShiftSvg" width="18" height="16" :class-name="keyboardState.iconClass" />
						</button>
						<div :class="keyboardState.innerGrid7Class">
							<button v-for="key in letterRow3" :key="key" type="button" :class="keyboardState.keyButtonClass" @click="clickKey(key)">
								{{ resolveFullKeyboardInputKey(key, isUpperCase) }}
							</button>
						</div>
						<button type="button" :class="keyboardState.deleteButtonClass" aria-label="delete" @click="clickDelete">
							<SvgIcon :svg="numKeyboardDeleteSvg" width="22" height="22" :class-name="keyboardState.iconClass" />
						</button>
					</div>
				</template>

				<div :class="keyboardState.bottomRowClass">
					<button type="button" :class="keyboardState.symbolToggleButtonClass" @click="toggleSymbolMode">
						{{ keyboardState.symbolToggleText }}
					</button>
					<button
						v-for="key in keyboardState.layout.bottomSymbolKeys"
						:key="key"
						type="button"
						:class="keyboardState.symbolKeyClass"
						@click="clickKey(key)"
					>
						{{ key }}
					</button>
					<button type="button" :class="keyboardState.flex1KeyClass" @click="clickSpace">
						<span :class="keyboardState.spaceTextClass">{{ keyboardTexts.spaceText }}</span>
					</button>
					<button
						v-if="keyboardState.layout.showDoneButton"
						type="button"
						:class="keyboardState.doneButtonClass"
						:disabled="doneDisabled"
						@click="clickDone"
					>
						{{ keyboardTexts.doneText }}
					</button>
				</div>
			</template>
		</div>
	</component>
</template>
