// packages/rtdf/src/lib/components/imagePreview/index.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ImagePreviewItemProps, ImagePreviewProps } from '../../types';
import { zh_CN, type LangProps } from '../../lang';
import { useConfig } from '../config-provider';
import Mask from '../mask';
import Icon from '../icon';
import Loading from '../loading';
import { Transition as MotionTransition } from '../utils/transition';
import {
	resolveImagePreviewBodyOverflowStyle,
	resolveImagePreviewCloseAction,
	resolveImagePreviewDerived,
	resolveImagePreviewInitialRendered,
	resolveImagePreviewInitialVisible,
	resolveImagePreviewLoadStatusAction,
	resolveImagePreviewOutroEndAction,
	resolveImagePreviewPointerDownState,
	resolveImagePreviewPointerList,
	resolveImagePreviewPointerMoveState,
	resolveImagePreviewPointerUpAction,
	resolveImagePreviewPointerUpState,
	resolveImagePreviewRenderedState,
	resolveImagePreviewRotateAction,
	resolveImagePreviewRotationAnimationAction,
	resolveImagePreviewRotationResetAction,
	resolveImagePreviewStateOptions,
	resolveImagePreviewSwitchAction,
	resolveImagePreviewTransformResetAction,
	resolveImagePreviewVisibleResetAction
} from '@any-tdf/common/derived/imagePreview';
import { resolveViewportDimension } from '@any-tdf/common/derived/helpers';
import { arrowLeftSvg, arrowRightSvg, imageLineSvg, imageRotateSvg } from '@any-tdf/common/svg/common';
import { SvgIcon } from '../utils/SvgIcon';

type PointerData = {
	clientX: number;
	clientY: number;
};

const ImagePreview: React.FC<ImagePreviewProps> = (props) => {
	const {
		visible: visibleProp,
		images = [],
		current: currentProp = 0,
		loop = true,
		swipeDuration = 300,
		minScale = 0.5,
		maxScale = 3,
		closePosition = 'tr',
		showNavigation = true,
		navigationPosition = 'center',
		maskClosable = false,
		showIndex = true,
		indicatorType = 'number',
		zIndex = 1000,
		duration = 300,
		outDuration = 200,
		mask = {},
		icon = {},
		showRotation = false,
		rotationIcon = {},
		children,
		loadingChild,
		errorChild,
		indexChild,
		onChange,
		onClose,
		onScale,
		onRotate
	} = props;

	const { locale } = useConfig();
	const imagePreviewLang = (locale?.imagePreview || zh_CN.imagePreview) as NonNullable<LangProps['imagePreview']>;
	const [innerVisible, setInnerVisible] = useState(() => resolveImagePreviewInitialVisible(visibleProp));
	const visible = innerVisible;
	const [rendered, setRendered] = useState(() => resolveImagePreviewInitialRendered(visibleProp));

	const [innerCurrent, setInnerCurrent] = useState(currentProp);
	const currentIndex = innerCurrent;

	const [loadStatus, setLoadStatus] = useState<Record<number, 'loading' | 'loaded' | 'error'>>({});
	const [rotationStatus, setRotationStatus] = useState<Record<number, number>>({});
	const [isResettingRotation, setIsResettingRotation] = useState(false);
	const [currentScale, setCurrentScale] = useState(1);
	const [translateX, setTranslateX] = useState(0);
	const [translateY, setTranslateY] = useState(0);
	const [isMoving, setIsMoving] = useState(false);
	const [isSwiping, setIsSwiping] = useState(false);
	const [swipeOffset, setSwipeOffset] = useState(0);
	const [isPinching, setIsPinching] = useState(false);

	const activePointers = useRef<Map<number, PointerData>>(new Map());
	const startXRef = useRef(0);
	const startYRef = useRef(0);
	const swipeStartXRef = useRef(0);
	const pinchStartDistanceRef = useRef(0);
	const pinchStartScaleRef = useRef(1);
	const hasMovedRef = useRef(false);
	const containerRef = useRef<HTMLDivElement | null>(null);

	// 公共派生层统一 ImagePreview 的展示数据、style、控制区状态和图标参数，事件与 DOM 副作用留在组件层。
	// Shared derivation centralizes ImagePreview display data, styles, control state and icon params; events and DOM side effects stay in the component layer.
	const imagePreviewState = useMemo(
		() =>
			resolveImagePreviewDerived<
				ImagePreviewItemProps,
				NonNullable<ImagePreviewProps['icon']>,
				NonNullable<ImagePreviewProps['rotationIcon']>
			>(
				resolveImagePreviewStateOptions<
					ImagePreviewItemProps,
					NonNullable<ImagePreviewProps['icon']>,
					NonNullable<ImagePreviewProps['rotationIcon']>
				>({
					props: {
						images,
						closePosition,
						zIndex,
						duration,
						outDuration,
						icon,
						rotationIcon,
						loop,
						navigationPosition,
						showIndex,
						showNavigation,
						swipeDuration
					},
					currentIndex,
					currentScale,
					translateX,
					translateY,
					rotationStatus,
					loadStatus,
					loadingContentVisible: Boolean(loadingChild),
					errorContentVisible: Boolean(errorChild),
					isMoving,
					isPinching,
					isResettingRotation,
					isSwiping,
					swipeOffset
				})
			),
		[
			closePosition,
			currentIndex,
			currentScale,
			duration,
			errorChild,
			icon,
			images,
			isMoving,
			isPinching,
			isResettingRotation,
			isSwiping,
			loadStatus,
			loadingChild,
			loop,
			navigationPosition,
			outDuration,
			rotationIcon,
			rotationStatus,
			showIndex,
			showNavigation,
			swipeDuration,
			swipeOffset,
			translateX,
			translateY,
			zIndex
		]
	);

	useEffect(() => {
		setInnerVisible(resolveImagePreviewInitialVisible(visibleProp));
	}, [visibleProp]);

	useEffect(() => {
		setRendered((currentRendered) => resolveImagePreviewRenderedState({ visible, outDuration, currentRendered }));
	}, [outDuration, visible]);

	useEffect(() => {
		setInnerCurrent(currentProp);
	}, [currentProp]);

	useEffect(() => {
		setLoadStatus({});
		setRotationStatus({});
	}, [images]);

	useEffect(() => {
		if (visible) {
			const action = resolveImagePreviewVisibleResetAction();
			setCurrentScale(action.currentScale);
			setTranslateX(action.translateX);
			setTranslateY(action.translateY);
			setSwipeOffset(action.swipeOffset);
			setIsSwiping(action.pointerFlags.isSwiping);
			setIsMoving(action.pointerFlags.isMoving);
			setIsPinching(action.pointerFlags.isPinching);
			if (typeof document !== 'undefined') {
				// DOM 写入保留在组件内，公共函数只返回要写入的值。
				// Keep DOM writes in component code; the shared helper only returns the value to apply.
				document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible });
			}
			return () => {
				if (typeof document !== 'undefined') {
					document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible: false });
				}
			};
		}
		if (typeof document !== 'undefined') {
			document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible });
		}
	}, [visible]);

	const resetTransform = () => {
		const action = resolveImagePreviewTransformResetAction();
		setCurrentScale(action.currentScale);
		setTranslateX(action.translateX);
		setTranslateY(action.translateY);
	};
	const emitChange = (index: number) => {
		onChange?.(index);
	};
	const emitClose = () => {
		onClose?.();
	};
	const emitScale = (scale: number) => {
		onScale?.(scale);
	};
	const emitRotate = (rotation: 0 | 90 | 180 | 270) => {
		onRotate?.(rotation);
	};

	const close = () => {
		// 公共 action 只返回关闭状态和变换重置值，事件触发留在组件内。
		// Shared action only returns close state and transform reset values; event dispatch stays in the component.
		const action = resolveImagePreviewCloseAction({ visible: innerVisible });
		if (!action.shouldClose) return;
		setInnerVisible(action.nextVisible);
		setCurrentScale(action.currentScale);
		setTranslateX(action.translateX);
		setTranslateY(action.translateY);
		if (action.shouldEmitClose) emitClose();
	};

	const switchImage = (index: number) => {
		if (imagePreviewState.total === 0) return;
		const action = resolveImagePreviewSwitchAction({
			currentIndex,
			requestedIndex: index,
			total: imagePreviewState.total,
			loop
		});
		if (!action.shouldChange) return;
		setInnerCurrent(action.nextIndex);
		emitChange(action.nextIndex);
		setCurrentScale(action.currentScale);
		setTranslateX(action.translateX);
		setTranslateY(action.translateY);
	};

	const prev = () => switchImage(currentIndex - 1);
	const next = () => switchImage(currentIndex + 1);

	const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
		containerRef.current?.setPointerCapture(event.pointerId);
		activePointers.current.set(event.pointerId, { clientX: event.clientX, clientY: event.clientY });

		// 公共手势派生只返回下一步状态，pointer capture 和 setState 留在组件内。
		// Shared gesture derivation only returns next state; pointer capture and setState stay in the component.
		const pointerState = resolveImagePreviewPointerDownState({
			currentScale,
			pointers: resolveImagePreviewPointerList(activePointers.current.values())
		});
		hasMovedRef.current = pointerState.hasMoved;
		setIsPinching(pointerState.isPinching);
		setIsSwiping(pointerState.isSwiping);
		setIsMoving(pointerState.isMoving);
		if (pointerState.startX !== undefined) startXRef.current = pointerState.startX;
		if (pointerState.startY !== undefined) startYRef.current = pointerState.startY;
		if (pointerState.swipeStartX !== undefined) swipeStartXRef.current = pointerState.swipeStartX;
		if (pointerState.swipeOffset !== undefined) setSwipeOffset(pointerState.swipeOffset);
		if (pointerState.pinchStartDistance !== undefined) pinchStartDistanceRef.current = pointerState.pinchStartDistance;
		if (pointerState.pinchStartScale !== undefined) pinchStartScaleRef.current = pointerState.pinchStartScale;
	};

	const applyPointerMoveState = (
		pointerState: ReturnType<typeof resolveImagePreviewPointerMoveState>,
		event: React.PointerEvent<HTMLDivElement>
	) => {
		if (pointerState.hasMoved) hasMovedRef.current = true;
		if (pointerState.nextScale !== undefined) {
			setCurrentScale(pointerState.nextScale);
			emitScale(pointerState.nextScale);
		}
		if (pointerState.swipeOffset !== undefined) setSwipeOffset(pointerState.swipeOffset);
		if (pointerState.translateDeltaX !== undefined) setTranslateX((prevValue) => prevValue + pointerState.translateDeltaX!);
		if (pointerState.translateDeltaY !== undefined) setTranslateY((prevValue) => prevValue + pointerState.translateDeltaY!);
		if (pointerState.nextStartX !== undefined) startXRef.current = pointerState.nextStartX;
		if (pointerState.nextStartY !== undefined) startYRef.current = pointerState.nextStartY;
		if (pointerState.preventDefault) event.preventDefault();
	};

	const handlePointerMove = (event: React.PointerEvent<HTMLDivElement>) => {
		if (!activePointers.current.has(event.pointerId)) return;
		activePointers.current.set(event.pointerId, { clientX: event.clientX, clientY: event.clientY });

		const pointerState = resolveImagePreviewPointerMoveState({
			pointers: resolveImagePreviewPointerList(activePointers.current.values()),
			point: { clientX: event.clientX, clientY: event.clientY },
			currentScale,
			isPinching,
			isSwiping,
			isMoving,
			pinchStartDistance: pinchStartDistanceRef.current,
			pinchStartScale: pinchStartScaleRef.current,
			minScale,
			maxScale,
			startX: startXRef.current,
			startY: startYRef.current,
			swipeStartX: swipeStartXRef.current
		});
		applyPointerMoveState(pointerState, event);
	};

	const handlePointerUp = (event: React.PointerEvent<HTMLDivElement>) => {
		containerRef.current?.releasePointerCapture(event.pointerId);
		activePointers.current.delete(event.pointerId);

		const pointerState = resolveImagePreviewPointerUpState({
			pointers: resolveImagePreviewPointerList(activePointers.current.values()),
			currentScale,
			isSwiping,
			swipeOffset,
			viewportWidth: resolveViewportDimension({
				value: typeof window !== 'undefined' ? window.innerWidth : undefined
			}),
			hasMoved: hasMovedRef.current,
			maskClosable
		});
		const pointerAction = resolveImagePreviewPointerUpAction({
			pointerCount: activePointers.current.size,
			pointerState
		});

		if (pointerAction.kind === 'continueTracking') {
			const pointerFlags = pointerAction.pointerFlags;
			setIsPinching(pointerFlags.isPinching);
			setIsSwiping(pointerFlags.isSwiping);
			setIsMoving(pointerFlags.isMoving);
			if (pointerAction.startX !== undefined) startXRef.current = pointerAction.startX;
			if (pointerAction.startY !== undefined) startYRef.current = pointerAction.startY;
			if (pointerAction.swipeStartX !== undefined) swipeStartXRef.current = pointerAction.swipeStartX;
			return;
		}

		if (pointerAction.kind !== 'settled') return;

		// 公共动作决策负责纯分支判断，组件层负责状态写入和回调。
		// Shared action decision handles pure branching while the component layer writes state and emits callbacks.
		const pointerFlags = pointerAction.pointerFlags;
		setIsPinching(pointerFlags.isPinching);
		setIsMoving(pointerFlags.isMoving);

		if (pointerAction.shouldResetSwipeOffset) {
			setIsSwiping(pointerFlags.isSwiping);
			if (pointerAction.shouldSwitchPrev) {
				prev();
			} else if (pointerAction.shouldSwitchNext) {
				next();
			}
			setSwipeOffset(0);
		}

		if (pointerAction.shouldClose) {
			close();
			return;
		}

		if (pointerAction.shouldResetScale) {
			resetTransform();
		}
	};

	const handleImageLoad = (index: number) => {
		setLoadStatus(
			(prev) =>
				resolveImagePreviewLoadStatusAction({ index, loadStatus: prev, status: 'loaded' }).nextLoadStatus as Record<
					number,
					'loading' | 'loaded' | 'error'
				>
		);
	};

	const handleImageError = (index: number) => {
		setLoadStatus(
			(prev) =>
				resolveImagePreviewLoadStatusAction({ index, loadStatus: prev, status: 'error' }).nextLoadStatus as Record<
					number,
					'loading' | 'loaded' | 'error'
				>
		);
	};

	const handleRotate = () => {
		const action = resolveImagePreviewRotateAction({ currentIndex, rotationStatus });
		setRotationStatus(action.nextRotationStatus);
		emitRotate(action.normalizedRotation);

		if (action.shouldResetRotation) {
			const idx = action.resetIndex;
			setTimeout(() => {
				setIsResettingRotation(resolveImagePreviewRotationAnimationAction({ phase: 'start' }).nextIsResettingRotation);
				requestAnimationFrame(() => {
					requestAnimationFrame(() => {
						setRotationStatus((prev) => resolveImagePreviewRotationResetAction({ index: idx, rotationStatus: prev }).nextRotationStatus);
						setTimeout(() => {
							setIsResettingRotation(resolveImagePreviewRotationAnimationAction({ phase: 'end' }).nextIsResettingRotation);
						}, 20);
					});
				});
			}, 200);
		}
	};

	const handleOutroEnd = useCallback(() => {
		const action = resolveImagePreviewOutroEndAction();
		setRendered(action.nextRendered);
	}, []);

	if (!rendered) return null;

	return (
		<>
			<Mask visible={visible} opacity="0.9" duration={duration} outDuration={outDuration} {...mask} zIndex={zIndex} />
			<MotionTransition
				visible={visible}
				transition="fade"
				inParams={imagePreviewState.inParams}
				outParams={imagePreviewState.outParams}
				className={imagePreviewState.overlayClass}
				style={imagePreviewState.overlayStyleValue}
				onOutroEnd={handleOutroEnd}
			>
				<div
					ref={containerRef}
					className={imagePreviewState.containerClass}
					onPointerDown={handlePointerDown}
					onPointerMove={handlePointerMove}
					onPointerUp={handlePointerUp}
					onPointerCancel={handlePointerUp}
				>
					<div className={imagePreviewState.slideClass} style={imagePreviewState.slideStyleValue}>
						{imagePreviewState.imageDisplayItems.map(({ item: img, index, displayState, alt, imageStyleValue }) => {
							return (
								<div key={`${img.url}-${index}`} className={imagePreviewState.itemClass}>
									{displayState.showLoading ? (
										<div className={imagePreviewState.loadingClass}>
											{displayState.showCustomLoading ? loadingChild?.() : <Loading height="12" width="12" theme />}
										</div>
									) : null}
									{displayState.showError ? (
										<div className={imagePreviewState.errorClass}>
											{displayState.showCustomError ? (
												errorChild?.()
											) : (
												<>
													{/* 公共图片占位 SVG 数据在 common 中维护。 / Shared image placeholder SVG data lives in common. */}
													<SvgIcon svg={imageLineSvg} width={48} height={48} className={imagePreviewState.errorIconClass} />
													<span className={imagePreviewState.errorTextClass}>{imagePreviewLang.loadFailedText}</span>
												</>
											)}
										</div>
									) : displayState.showImage ? (
										<img
											src={img.url}
											alt={alt}
											className={imagePreviewState.imageClass}
											style={imageStyleValue}
											draggable={false}
											onLoad={() => handleImageLoad(index)}
											onError={() => handleImageError(index)}
										/>
									) : null}
								</div>
							);
						})}
					</div>

					{children ? (
						<div className={imagePreviewState.customContentClass}>
							{typeof children === 'function'
								? (children as (item: ImagePreviewItemProps, index: number) => React.ReactNode)(
										imagePreviewState.currentImage,
										currentIndex
									)
								: children}
						</div>
					) : null}
				</div>

				<MotionTransition
					visible={true}
					transition="scale"
					inParams={imagePreviewState.controlScaleParams}
					className={imagePreviewState.controlPanelClass}
				>
					{showRotation ? (
						<button type="button" className={imagePreviewState.controlButtonClass} onClick={handleRotate} aria-label="Rotate">
							{/* 公共 ImagePreview 旋转 SVG 数据在 common 中维护。 / Shared ImagePreview rotate SVG data lives in common. */}
							<SvgIcon
								svg={imageRotateSvg}
								width={imagePreviewState.mergedRotationIcon.size}
								height={imagePreviewState.mergedRotationIcon.size}
							/>
						</button>
					) : null}
					<button type="button" className={imagePreviewState.controlButtonClass} onClick={close}>
						<Icon {...imagePreviewState.mergedIcon} />
					</button>
				</MotionTransition>

				{imagePreviewState.controlState.showCenterNavigation ? (
					<>
						{imagePreviewState.controlState.showCenterPrev ? (
							<MotionTransition
								visible={true}
								as="button"
								transition="scale"
								inParams={imagePreviewState.controlScaleParams}
								type="button"
								className={imagePreviewState.centerPrevButtonClass}
								onClick={prev}
								aria-label="Previous"
							>
								{/* 公共 ImagePreview 导航 SVG 数据在 common 中维护。 / Shared ImagePreview navigation SVG data lives in common. */}
								<SvgIcon svg={arrowLeftSvg} width={24} height={24} />
							</MotionTransition>
						) : null}
						{imagePreviewState.controlState.showCenterNext ? (
							<MotionTransition
								visible={true}
								as="button"
								transition="scale"
								inParams={imagePreviewState.controlScaleParams}
								type="button"
								className={imagePreviewState.centerNextButtonClass}
								onClick={next}
								aria-label="Next"
							>
								<SvgIcon svg={arrowRightSvg} width={24} height={24} />
							</MotionTransition>
						) : null}
					</>
				) : null}

				{imagePreviewState.controlState.showBottomBar ? (
					<div className={imagePreviewState.bottomBarClass}>
						{imagePreviewState.controlState.showBottomPrev ? (
							<MotionTransition
								visible={true}
								as="button"
								transition="scale"
								inParams={imagePreviewState.controlScaleParams}
								type="button"
								className={imagePreviewState.controlButtonClass}
								onClick={prev}
								aria-label="Previous"
							>
								<SvgIcon svg={arrowLeftSvg} width={24} height={24} />
							</MotionTransition>
						) : null}

						{imagePreviewState.controlState.showIndex ? (
							indexChild ? (
								indexChild(currentIndex + 1, imagePreviewState.total)
							) : indicatorType === 'dot' ? (
								<div className={imagePreviewState.dotListClass}>
									{imagePreviewState.dotItems.map((dotItem) => (
										<button
											type="button"
											key={`dot-${dotItem.index}`}
											className={dotItem.className}
											onClick={() => switchImage(dotItem.index)}
											aria-label={`Go to image ${dotItem.index + 1}`}
										></button>
									))}
								</div>
							) : (
								<span className={imagePreviewState.indexNumberClass}>
									{currentIndex + 1} / {imagePreviewState.total}
								</span>
							)
						) : null}

						{imagePreviewState.controlState.showBottomNext ? (
							<MotionTransition
								visible={true}
								as="button"
								transition="scale"
								inParams={imagePreviewState.controlScaleParams}
								type="button"
								className={imagePreviewState.controlButtonClass}
								onClick={next}
								aria-label="Next"
							>
								<SvgIcon svg={arrowRightSvg} width={24} height={24} />
							</MotionTransition>
						) : null}
					</div>
				) : null}
			</MotionTransition>
		</>
	);
};

export default ImagePreview;

// packages/vtdf/src/lib/components/ImagePreview.vue
<script setup lang="ts">
import { computed, defineComponent, onBeforeUnmount, ref, useSlots, watch, type PropType } from 'vue';
import { isBrowser } from '@any-tdf/common/utils';
import {
	resolveImagePreviewBodyOverflowStyle,
	resolveImagePreviewCloseAction,
	resolveImagePreviewDerived,
	resolveImagePreviewInitialRendered,
	resolveImagePreviewInitialVisible,
	resolveImagePreviewLoadStatusAction,
	resolveImagePreviewPointerDownState,
	resolveImagePreviewPointerList,
	resolveImagePreviewPointerMoveState,
	resolveImagePreviewPointerUpAction,
	resolveImagePreviewPointerUpState,
	resolveImagePreviewRenderedState,
	resolveImagePreviewRotateAction,
	resolveImagePreviewRotationAnimationAction,
	resolveImagePreviewRotationResetAction,
	resolveImagePreviewStateOptions,
	resolveImagePreviewSwitchAction,
	resolveImagePreviewTransformResetAction,
	resolveImagePreviewVisibleResetAction
} from '@any-tdf/common/derived/imagePreview';
import { resolveViewportDimension } from '@any-tdf/common/derived/helpers';
import { arrowLeftSvg, arrowRightSvg, imageLineSvg, imageRotateSvg } from '@any-tdf/common/svg/common';
import { Transition as MotionTransition } from '@any-tdf/vue-motion';
import type { ImagePreviewItemProps, ImagePreviewProps, VueNode } from '../types';
import { zh_CN, type LangProps } from '../lang';
import { useConfig } from './adapter/config';
import Icon from './Icon.vue';
import Loading from './Loading.vue';
import Mask from './Mask.vue';
import SvgIcon from './SvgIcon.vue';

type PointerData = {
	clientX: number;
	clientY: number;
};
type RotationValue = 0 | 90 | 180 | 270;
type LoadStatus = 'loading' | 'loaded' | 'error';
type ImagePreviewComponentProps = Omit<ImagePreviewProps, 'children' | 'loadingChild' | 'errorChild' | 'indexChild'> & {
	children?: ((item: ImagePreviewItemProps, index: number) => VueNode) | VueNode;
	loadingChild?: () => VueNode;
	errorChild?: () => VueNode;
	indexChild?: (current: number, total: number) => VueNode;
};

const RenderNode = defineComponent({
	name: 'RenderNode',
	props: {
		node: {
			type: null as unknown as PropType<VueNode>,
			default: null
		}
	},
	setup: (renderProps) => () => renderProps.node ?? null
});

const props = withDefaults(defineProps<ImagePreviewComponentProps>(), {
	visible: false,
	images: () => [],
	current: 0,
	loop: true,
	swipeDuration: 300,
	minScale: 0.5,
	maxScale: 3,
	closePosition: 'tr',
	showNavigation: true,
	navigationPosition: 'center',
	maskClosable: false,
	showIndex: true,
	indicatorType: 'number',
	zIndex: 1000,
	duration: 300,
	outDuration: 200,
	mask: () => ({}),
	icon: () => ({}),
	showRotation: false,
	rotationIcon: () => ({})
});

const emit = defineEmits<{
	(event: 'update:visible', value: boolean): void;
	(event: 'update:current', value: number): void;
	(event: 'change', value: number): void;
	(event: 'close'): void;
	(event: 'scale', value: number): void;
	(event: 'rotate', value: RotationValue): void;
}>();

const config = useConfig();
const slots = useSlots();
const innerVisible = ref(resolveImagePreviewInitialVisible(props.visible));
const rendered = ref(resolveImagePreviewInitialRendered(props.visible));
const currentIndex = ref(props.current);
const loadStatus = ref<Record<number, LoadStatus>>({});
const rotationStatus = ref<Record<number, number>>({});
const isResettingRotation = ref(false);
const currentScale = ref(1);
const translateX = ref(0);
const translateY = ref(0);
const isMoving = ref(false);
const isSwiping = ref(false);
const swipeOffset = ref(0);
const isPinching = ref(false);
const containerRef = ref<HTMLDivElement | null>(null);
const activePointers = new Map<number, PointerData>();
const startX = ref(0);
const startY = ref(0);
const swipeStartX = ref(0);
const pinchStartDistance = ref(0);
const pinchStartScale = ref(1);
const hasMoved = ref(false);

const imagePreviewLang = computed(() => (config.locale?.imagePreview || zh_CN.imagePreview) as NonNullable<LangProps['imagePreview']>);
// 公共派生层统一 ImagePreview 的展示数据、style、控制区状态和图标参数，事件与 DOM 副作用留在组件层。
// Shared derivation centralizes ImagePreview display data, styles, control state and icon params; events and DOM side effects stay in the component layer.
const imagePreviewState = computed(() =>
	resolveImagePreviewDerived<
		ImagePreviewItemProps,
		NonNullable<ImagePreviewComponentProps['icon']>,
		NonNullable<ImagePreviewComponentProps['rotationIcon']>
	>(
		resolveImagePreviewStateOptions<
			ImagePreviewItemProps,
			NonNullable<ImagePreviewComponentProps['icon']>,
			NonNullable<ImagePreviewComponentProps['rotationIcon']>
		>({
			props: {
				images: props.images,
				closePosition: props.closePosition,
				zIndex: props.zIndex,
				duration: props.duration,
				outDuration: props.outDuration,
				icon: props.icon,
				rotationIcon: props.rotationIcon,
				loop: props.loop,
				navigationPosition: props.navigationPosition,
				showIndex: props.showIndex,
				showNavigation: props.showNavigation,
				swipeDuration: props.swipeDuration
			},
			currentIndex: currentIndex.value,
			currentScale: currentScale.value,
			translateX: translateX.value,
			translateY: translateY.value,
			rotationStatus: rotationStatus.value,
			loadStatus: loadStatus.value,
			loadingContentVisible: Boolean(slots.loading || props.loadingChild),
			errorContentVisible: Boolean(slots.error || props.errorChild),
			isMoving: isMoving.value,
			isPinching: isPinching.value,
			isResettingRotation: isResettingRotation.value,
			isSwiping: isSwiping.value,
			swipeOffset: swipeOffset.value
		})
	)
);

const resetTransform = () => {
	const action = resolveImagePreviewTransformResetAction();
	currentScale.value = action.currentScale;
	translateX.value = action.translateX;
	translateY.value = action.translateY;
};

const emitChange = (index: number) => {
	emit('update:current', index);
	emit('change', index);
};

const emitClose = () => {
	emit('close');
};

const emitScale = (scale: number) => {
	emit('scale', scale);
};

const emitRotate = (rotation: RotationValue) => {
	emit('rotate', rotation);
};

const close = () => {
	// 公共 action 只返回关闭状态和变换重置值，事件触发留在组件内。
	// Shared action only returns close state and transform reset values; event dispatch stays in the component.
	const action = resolveImagePreviewCloseAction({ visible: innerVisible.value });
	if (!action.shouldClose) return;
	innerVisible.value = action.nextVisible;
	emit('update:visible', action.nextVisible);
	currentScale.value = action.currentScale;
	translateX.value = action.translateX;
	translateY.value = action.translateY;
	if (action.shouldEmitClose) emitClose();
};

const switchImage = (index: number) => {
	if (imagePreviewState.value.total === 0) return;
	const action = resolveImagePreviewSwitchAction({
		currentIndex: currentIndex.value,
		requestedIndex: index,
		total: imagePreviewState.value.total,
		loop: props.loop
	});
	if (!action.shouldChange) return;
	currentIndex.value = action.nextIndex;
	currentScale.value = action.currentScale;
	translateX.value = action.translateX;
	translateY.value = action.translateY;
	emitChange(action.nextIndex);
};

const prev = () => switchImage(currentIndex.value - 1);
const next = () => switchImage(currentIndex.value + 1);

const handlePointerDown = (event: PointerEvent) => {
	containerRef.value?.setPointerCapture(event.pointerId);
	activePointers.set(event.pointerId, { clientX: event.clientX, clientY: event.clientY });

	// 公共手势派生只返回下一步状态，pointer capture 和 ref 赋值留在组件内。
	// Shared gesture derivation only returns next state; pointer capture and ref assignment stay in the component.
	const pointerState = resolveImagePreviewPointerDownState({
		currentScale: currentScale.value,
		pointers: resolveImagePreviewPointerList(activePointers.values())
	});
	hasMoved.value = pointerState.hasMoved;
	isPinching.value = pointerState.isPinching;
	isSwiping.value = pointerState.isSwiping;
	isMoving.value = pointerState.isMoving;
	if (pointerState.startX !== undefined) startX.value = pointerState.startX;
	if (pointerState.startY !== undefined) startY.value = pointerState.startY;
	if (pointerState.swipeStartX !== undefined) swipeStartX.value = pointerState.swipeStartX;
	if (pointerState.swipeOffset !== undefined) swipeOffset.value = pointerState.swipeOffset;
	if (pointerState.pinchStartDistance !== undefined) pinchStartDistance.value = pointerState.pinchStartDistance;
	if (pointerState.pinchStartScale !== undefined) pinchStartScale.value = pointerState.pinchStartScale;
};

const applyPointerMoveState = (pointerState: ReturnType<typeof resolveImagePreviewPointerMoveState>, event: PointerEvent) => {
	if (pointerState.hasMoved) hasMoved.value = true;
	if (pointerState.nextScale !== undefined) {
		currentScale.value = pointerState.nextScale;
		emitScale(pointerState.nextScale);
	}
	if (pointerState.swipeOffset !== undefined) swipeOffset.value = pointerState.swipeOffset;
	if (pointerState.translateDeltaX !== undefined) translateX.value += pointerState.translateDeltaX;
	if (pointerState.translateDeltaY !== undefined) translateY.value += pointerState.translateDeltaY;
	if (pointerState.nextStartX !== undefined) startX.value = pointerState.nextStartX;
	if (pointerState.nextStartY !== undefined) startY.value = pointerState.nextStartY;
	if (pointerState.preventDefault) event.preventDefault();
};

const handlePointerMove = (event: PointerEvent) => {
	if (!activePointers.has(event.pointerId)) return;
	activePointers.set(event.pointerId, { clientX: event.clientX, clientY: event.clientY });

	const pointerState = resolveImagePreviewPointerMoveState({
		pointers: resolveImagePreviewPointerList(activePointers.values()),
		point: { clientX: event.clientX, clientY: event.clientY },
		currentScale: currentScale.value,
		isPinching: isPinching.value,
		isSwiping: isSwiping.value,
		isMoving: isMoving.value,
		pinchStartDistance: pinchStartDistance.value,
		pinchStartScale: pinchStartScale.value,
		minScale: props.minScale,
		maxScale: props.maxScale,
		startX: startX.value,
		startY: startY.value,
		swipeStartX: swipeStartX.value
	});
	applyPointerMoveState(pointerState, event);
};

const handlePointerUp = (event: PointerEvent) => {
	const container = containerRef.value;
	if (container?.hasPointerCapture(event.pointerId)) {
		container.releasePointerCapture(event.pointerId);
	}
	activePointers.delete(event.pointerId);

	const pointerState = resolveImagePreviewPointerUpState({
		pointers: resolveImagePreviewPointerList(activePointers.values()),
		currentScale: currentScale.value,
		isSwiping: isSwiping.value,
		swipeOffset: swipeOffset.value,
		viewportWidth: resolveViewportDimension({ value: window.innerWidth }),
		hasMoved: hasMoved.value,
		maskClosable: props.maskClosable
	});
	const pointerAction = resolveImagePreviewPointerUpAction({
		pointerCount: activePointers.size,
		pointerState
	});

	if (pointerAction.kind === 'continueTracking') {
		const pointerFlags = pointerAction.pointerFlags;
		isPinching.value = pointerFlags.isPinching;
		isSwiping.value = pointerFlags.isSwiping;
		isMoving.value = pointerFlags.isMoving;
		if (pointerAction.startX !== undefined) startX.value = pointerAction.startX;
		if (pointerAction.startY !== undefined) startY.value = pointerAction.startY;
		if (pointerAction.swipeStartX !== undefined) swipeStartX.value = pointerAction.swipeStartX;
		return;
	}

	if (pointerAction.kind !== 'settled') return;

	// 公共动作决策负责纯分支判断，组件层负责状态写入和 emit。
	// Shared action decision handles pure branching while the component layer writes state and emits.
	const pointerFlags = pointerAction.pointerFlags;
	isPinching.value = pointerFlags.isPinching;
	isMoving.value = pointerFlags.isMoving;

	if (pointerAction.shouldResetSwipeOffset) {
		isSwiping.value = pointerFlags.isSwiping;
		if (pointerAction.shouldSwitchPrev) {
			prev();
		} else if (pointerAction.shouldSwitchNext) {
			next();
		}
		swipeOffset.value = 0;
	}

	if (pointerAction.shouldClose) {
		close();
		return;
	}

	if (pointerAction.shouldResetScale) {
		resetTransform();
	}
};

const handleImageLoad = (index: number) => {
	loadStatus.value = resolveImagePreviewLoadStatusAction({
		index,
		loadStatus: loadStatus.value,
		status: 'loaded'
	}).nextLoadStatus as Record<number, LoadStatus>;
};

const handleImageError = (index: number) => {
	loadStatus.value = resolveImagePreviewLoadStatusAction({
		index,
		loadStatus: loadStatus.value,
		status: 'error'
	}).nextLoadStatus as Record<number, LoadStatus>;
};

const handleRotate = () => {
	const action = resolveImagePreviewRotateAction({
		currentIndex: currentIndex.value,
		rotationStatus: rotationStatus.value
	});
	rotationStatus.value = action.nextRotationStatus;
	emitRotate(action.normalizedRotation);

	if (action.shouldResetRotation) {
		const index = action.resetIndex;
		setTimeout(() => {
			isResettingRotation.value = resolveImagePreviewRotationAnimationAction({
				phase: 'start'
			}).nextIsResettingRotation;
			requestAnimationFrame(() => {
				requestAnimationFrame(() => {
					rotationStatus.value = resolveImagePreviewRotationResetAction({
						index,
						rotationStatus: rotationStatus.value
					}).nextRotationStatus;
					setTimeout(() => {
						isResettingRotation.value = resolveImagePreviewRotationAnimationAction({
							phase: 'end'
						}).nextIsResettingRotation;
					}, 20);
				});
			});
		}, 200);
	}
};

const getCustomContent = () => {
	if (typeof props.children === 'function') {
		return props.children(imagePreviewState.value.currentImage, currentIndex.value);
	}
	return props.children;
};

watch(
	() => props.visible,
	(value) => {
		innerVisible.value = resolveImagePreviewInitialVisible(value);
	}
);

watch(
	() => innerVisible.value,
	(value) => {
		rendered.value = resolveImagePreviewRenderedState({
			visible: value,
			outDuration: props.outDuration,
			currentRendered: rendered.value
		});
		if (value) {
			const action = resolveImagePreviewVisibleResetAction();
			currentScale.value = action.currentScale;
			translateX.value = action.translateX;
			translateY.value = action.translateY;
			swipeOffset.value = action.swipeOffset;
			isSwiping.value = action.pointerFlags.isSwiping;
			isMoving.value = action.pointerFlags.isMoving;
			isPinching.value = action.pointerFlags.isPinching;
			// DOM 写入保留在组件内，公共函数只返回要写入的值。
			// Keep DOM writes in component code; the shared helper only returns the value to apply.
			if (isBrowser) document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible: value });
			return;
		}
		if (isBrowser) document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible: value });
	},
	{ immediate: true }
);

watch(
	() => props.current,
	(value) => {
		currentIndex.value = value;
	}
);

watch(
	() => props.images,
	() => {
		loadStatus.value = {};
		rotationStatus.value = {};
	},
	{ deep: true }
);

onBeforeUnmount(() => {
	if (isBrowser) document.body.style.overflow = resolveImagePreviewBodyOverflowStyle({ visible: false });
	activePointers.clear();
});
</script>

<template>
	<template v-if="rendered">
		<Mask :visible="innerVisible" opacity="0.9" :duration="duration" :out-duration="outDuration" v-bind="mask" :z-index="zIndex" />
		<MotionTransition
			:visible="innerVisible"
			transition="fade"
			:in-params="imagePreviewState.inParams"
			:out-params="imagePreviewState.outParams"
			:class="imagePreviewState.overlayClass"
			:style="imagePreviewState.overlayStyleValue"
			@outro-end="rendered = false"
		>
			<div
				ref="containerRef"
				:class="imagePreviewState.containerClass"
				@pointerdown="handlePointerDown"
				@pointermove="handlePointerMove"
				@pointerup="handlePointerUp"
				@pointercancel="handlePointerUp"
			>
				<div :class="imagePreviewState.slideClass" :style="imagePreviewState.slideStyleValue">
					<div
						v-for="imageDisplayItem in imagePreviewState.imageDisplayItems"
						:key="`${imageDisplayItem.item.url}-${imageDisplayItem.index}`"
						:class="imagePreviewState.itemClass"
					>
						<div v-if="imageDisplayItem.displayState.showLoading" :class="imagePreviewState.loadingClass">
							<slot v-if="slots.loading" name="loading" />
							<RenderNode v-else-if="imageDisplayItem.displayState.showCustomLoading" :node="loadingChild?.()" />
							<Loading v-else height="12" width="12" theme />
						</div>

						<div v-if="imageDisplayItem.displayState.showError" :class="imagePreviewState.errorClass">
							<slot v-if="slots.error" name="error" />
							<RenderNode v-else-if="imageDisplayItem.displayState.showCustomError" :node="errorChild?.()" />
							<template v-else>
								<!-- 公共图片占位 SVG 数据在 common 中维护。 / Shared image placeholder SVG data lives in common. -->
								<SvgIcon :svg="imageLineSvg" width="48" height="48" :class-name="imagePreviewState.errorIconClass" />
								<span :class="imagePreviewState.errorTextClass">{{ imagePreviewLang.loadFailedText }}</span>
							</template>
						</div>
						<img
							v-else-if="imageDisplayItem.displayState.showImage"
							:src="imageDisplayItem.item.url"
							:alt="imageDisplayItem.alt"
							:class="imagePreviewState.imageClass"
							:style="imageDisplayItem.imageStyleValue"
							draggable="false"
							@load="handleImageLoad(imageDisplayItem.index)"
							@error="handleImageError(imageDisplayItem.index)"
						/>
					</div>
				</div>

				<div v-if="$slots.default || children" :class="imagePreviewState.customContentClass">
					<slot v-if="$slots.default" :item="imagePreviewState.currentImage" :index="currentIndex" />
					<RenderNode v-else :node="getCustomContent()" />
				</div>
			</div>

			<MotionTransition
				:visible="true"
				transition="scale"
				:in-params="imagePreviewState.controlScaleParams"
				:class="imagePreviewState.controlPanelClass"
			>
				<button v-if="showRotation" type="button" :class="imagePreviewState.controlButtonClass" aria-label="Rotate" @click="handleRotate">
					<!-- 公共 ImagePreview 旋转 SVG 数据在 common 中维护。 / Shared ImagePreview rotate SVG data lives in common. -->
					<SvgIcon
						:svg="imageRotateSvg"
						:width="imagePreviewState.mergedRotationIcon.size"
						:height="imagePreviewState.mergedRotationIcon.size"
					/>
				</button>
				<button type="button" :class="imagePreviewState.controlButtonClass" @click="close">
					<Icon v-bind="imagePreviewState.mergedIcon" />
				</button>
			</MotionTransition>

			<template v-if="imagePreviewState.controlState.showCenterNavigation">
				<MotionTransition
					v-if="imagePreviewState.controlState.showCenterPrev"
					:visible="true"
					as="button"
					type="button"
					transition="scale"
					:in-params="imagePreviewState.controlScaleParams"
					:class="imagePreviewState.centerPrevButtonClass"
					aria-label="Previous"
					@click="prev"
				>
					<!-- 公共 ImagePreview 导航 SVG 数据在 common 中维护。 / Shared ImagePreview navigation SVG data lives in common. -->
					<SvgIcon :svg="arrowLeftSvg" width="24" height="24" />
				</MotionTransition>
				<MotionTransition
					v-if="imagePreviewState.controlState.showCenterNext"
					:visible="true"
					as="button"
					type="button"
					transition="scale"
					:in-params="imagePreviewState.controlScaleParams"
					:class="imagePreviewState.centerNextButtonClass"
					aria-label="Next"
					@click="next"
				>
					<SvgIcon :svg="arrowRightSvg" width="24" height="24" />
				</MotionTransition>
			</template>

			<div v-if="imagePreviewState.controlState.showBottomBar" :class="imagePreviewState.bottomBarClass">
				<MotionTransition
					v-if="imagePreviewState.controlState.showBottomPrev"
					:visible="true"
					as="button"
					type="button"
					transition="scale"
					:in-params="imagePreviewState.controlScaleParams"
					:class="imagePreviewState.controlButtonClass"
					aria-label="Previous"
					@click="prev"
				>
					<SvgIcon :svg="arrowLeftSvg" width="24" height="24" />
				</MotionTransition>

				<template v-if="imagePreviewState.controlState.showIndex">
					<slot v-if="$slots.index" name="index" :current="currentIndex + 1" :total="imagePreviewState.total" />
					<RenderNode v-else-if="indexChild" :node="indexChild(currentIndex + 1, imagePreviewState.total)" />
					<div v-else-if="indicatorType === 'dot'" :class="imagePreviewState.dotListClass">
						<button
							v-for="dotItem in imagePreviewState.dotItems"
							:key="`dot-${dotItem.index}`"
							type="button"
							:class="dotItem.className"
							:aria-label="`Go to image ${dotItem.index + 1}`"
							@click="switchImage(dotItem.index)"
						/>
					</div>
					<span v-else-if="indicatorType === 'number'" :class="imagePreviewState.indexNumberClass">
						{{ currentIndex + 1 }} / {{ imagePreviewState.total }}
					</span>
				</template>

				<MotionTransition
					v-if="imagePreviewState.controlState.showBottomNext"
					:visible="true"
					as="button"
					type="button"
					transition="scale"
					:in-params="imagePreviewState.controlScaleParams"
					:class="imagePreviewState.controlButtonClass"
					aria-label="Next"
					@click="next"
				>
					<SvgIcon :svg="arrowRightSvg" width="24" height="24" />
				</MotionTransition>
			</div>
		</MotionTransition>
	</template>
</template>
