// packages/rtdf/src/lib/components/skeleton/skeleton.tsx
import type { SkeletonProps } from '../../types';
import { forwardRef, memo } from 'react';
import { resolveSkeletonDerived, resolveSkeletonRandomValue, resolveSkeletonStateOptions } from '@any-tdf/common/derived/skeleton';
import { SvgIcon } from '../utils/SvgIcon';

/**
 * Skeleton 组件 - 骨架屏组件
 * Skeleton component for loading placeholders
 */
const Skeleton = memo(
	forwardRef<HTMLDivElement, SkeletonProps>(
		(
			{ type = 'div', width = '6', height = '6', radius = '', space = '1', lines = 3, iconRatio = 0.6, effect = 'pulse', bg = 'gray' },
			ref
		) => {
			// 随机源留在组件层，随机值归一化由公共派生层统一。
			// Random source stays in the component layer, while shared derivations normalize the value.
			const randomValue = resolveSkeletonRandomValue({ random: Math.random() });
			const skeletonState = resolveSkeletonDerived(
				resolveSkeletonStateOptions({
					props: { type, width, height, radius, space, lines, iconRatio, effect, bg },
					randomValue
				})
			);

			// 段落类型的骨架屏
			if (skeletonState.displayState.showParagraph) {
				return (
					<div ref={ref} className={skeletonState.classes.wrapperClass}>
						<div className={skeletonState.paragraphClass}>
							{skeletonState.paragraphLineIndexes.map((i) => (
								<div key={i} className={skeletonState.classes.lineClass} />
							))}
							<div className={skeletonState.randomLineClass} />
						</div>
					</div>
				);
			}

			// 普通类型的骨架屏
			return (
				<div ref={ref} className={skeletonState.classes.wrapperClass}>
					<div className={skeletonState.classes.blockClass}>
						{skeletonState.displayState.showIcon && skeletonState.iconSvg ? (
							<div className={skeletonState.iconWrapClass} style={skeletonState.iconRatioStyleValue}>
								{/* 公共 Skeleton 图标 SVG 数据在 common 中维护。 / Shared Skeleton SVG data lives in common. */}
								<SvgIcon svg={skeletonState.iconSvg} width="100%" height="100%" className={skeletonState.iconSvgClass} />
							</div>
						) : null}
					</div>
				</div>
			);
		}
	)
);

Skeleton.displayName = 'Skeleton';

export default Skeleton;

// packages/vtdf/src/lib/components/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { SkeletonProps } from '../types';
import { resolveSkeletonDerived, resolveSkeletonRandomValue, resolveSkeletonStateOptions } from '@any-tdf/common/derived/skeleton';
import SvgIcon from './SvgIcon.vue';

const props = withDefaults(defineProps<SkeletonProps>(), {
	type: 'div',
	width: '6',
	height: '6',
	radius: '',
	space: '1',
	lines: 3,
	iconRatio: 0.6,
	effect: 'pulse',
	bg: 'gray'
});

// 随机源留在组件层，随机值归一化由公共派生层统一。
// Random source stays in the component layer, while shared derivations normalize the value.
const randomValue = resolveSkeletonRandomValue({ random: Math.random() });
const skeletonState = computed(() =>
	resolveSkeletonDerived(
		resolveSkeletonStateOptions({
			props: {
				type: props.type,
				width: props.width,
				height: props.height,
				radius: props.radius,
				space: props.space,
				lines: props.lines,
				iconRatio: props.iconRatio,
				effect: props.effect,
				bg: props.bg
			},
			randomValue
		})
	)
);
</script>

<template>
	<component :is="'style'" v-html="skeletonState.css" />
	<div :class="skeletonState.classes.wrapperClass">
		<div v-if="skeletonState.displayState.showParagraph" :class="skeletonState.paragraphClass">
			<div v-for="index in skeletonState.paragraphLineIndexes" :key="index" :class="skeletonState.classes.lineClass" />
			<div :class="skeletonState.randomLineClass" />
		</div>
		<div v-else :class="skeletonState.classes.blockClass">
			<div
				v-if="skeletonState.displayState.showIcon && skeletonState.iconSvg"
				:class="skeletonState.iconWrapClass"
				:style="skeletonState.iconRatioStyleValue"
			>
				<!-- 公共 Skeleton 图标 SVG 数据在 common 中维护。 / Shared Skeleton SVG data lives in common. -->
				<SvgIcon :svg="skeletonState.iconSvg" width="100%" height="100%" :class-name="skeletonState.iconSvgClass" />
			</div>
		</div>
	</div>
</template>
