// packages/rtdf/src/lib/components/steps/index.tsx
import type { StepsProps } from '../../types';
import { forwardRef, useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import Icon from '../icon';
import {
	resolveStepsDerived,
	resolveStepsMeasuredClientHeights,
	resolveStepsMeasuredClientWidth,
	resolveStepsMeasuredHeightsState,
	resolveStepsMeasuredWidthState,
	resolveStepsStateOptions
} from '@any-tdf/common/derived/steps';

const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect;

const Steps = forwardRef<HTMLDivElement, StepsProps>(
	({ steps = [], current = 1, radius = '', barBorder = true, vertical = false }, ref) => {
		const containerRef = useRef<HTMLDivElement>(null);
		const itemRefs = useRef<Array<HTMLDivElement | null>>([]);
		const [width, setWidth] = useState(0);
		const [heightList, setHeightList] = useState<number[]>([]);

		// 公共派生层处理 Steps 的数据选择、class 和布局值，DOM 测量留在组件层。
		// Shared derived layer handles Steps data selection, classes and layout values; DOM measurement stays in the component layer.
		const stepsState = useMemo(
			() =>
				resolveStepsDerived(
					resolveStepsStateOptions({
						props: { steps, current, radius, barBorder, vertical },
						width,
						heightList
					})
				),
			[steps, current, radius, barBorder, vertical, width, heightList]
		);

		const setContainerRefs = useCallback(
			(node: HTMLDivElement | null) => {
				containerRef.current = node;
				if (typeof ref === 'function') {
					ref(node);
				} else if (ref) {
					ref.current = node;
				}
			},
			[ref]
		);

		useEffect(() => {
			if (vertical) return;
			const updateWidth = () => {
				if (!containerRef.current) return;
				setWidth(
					(currentWidth) =>
						resolveStepsMeasuredWidthState({
							currentWidth,
							measuredWidth: resolveStepsMeasuredClientWidth(containerRef.current)
						}).width
				);
			};

			updateWidth();
			if (typeof ResizeObserver === 'undefined') return;
			const observer = new ResizeObserver(updateWidth);
			if (containerRef.current) {
				observer.observe(containerRef.current);
			}
			return () => observer.disconnect();
		}, [vertical]);

		const measureHeights = useCallback(() => {
			if (!vertical) return;
			const nextHeights = resolveStepsMeasuredClientHeights(itemRefs.current);
			setHeightList((prev) => {
				const heightState = resolveStepsMeasuredHeightsState({ currentHeights: prev, nextHeights });
				return heightState.heights;
			});
		}, [vertical]);

		useIsomorphicLayoutEffect(() => {
			measureHeights();
		}, [measureHeights, steps.length]);

		useEffect(() => {
			if (!vertical) return;
			if (typeof window === 'undefined') return;
			const onResize = () => {
				measureHeights();
			};
			window.addEventListener('resize', onResize);
			return () => window.removeEventListener('resize', onResize);
		}, [measureHeights, vertical]);

		const renderBar = (itemViewState: (typeof stepsState.items)[number]) => {
			const { itemState } = itemViewState;
			if (itemState.hasBar) {
				return (
					<div className={itemViewState.barWrapperClass}>
						<div className={itemViewState.lineClass} style={itemViewState.lineStyle} />
						<div className={itemViewState.barClass} style={itemViewState.barStyle}>
							{renderBarContent(itemViewState)}
						</div>
					</div>
				);
			}

			return (
				<div className={itemViewState.barWrapperClass}>
					<div className={itemViewState.lineClass} style={itemViewState.lineStyle} />
					<div className={itemViewState.barClass} style={itemViewState.barStyle} />
				</div>
			);
		};

		const renderBarContent = (itemViewState: (typeof stepsState.items)[number]) => {
			const { barContentState } = itemViewState;
			switch (barContentState.kind) {
				case 'icon':
					return (
						<div className={itemViewState.barIconClass}>
							<Icon {...barContentState.iconProps} size={16} />
						</div>
					);
				case 'image':
					return <img className={itemViewState.barImageClass} src={barContentState.src} alt="" />;
				case 'text':
					return <div className={itemViewState.barTextClass}>{barContentState.text}</div>;
				default:
					return null;
			}
		};
		const renderInject = (inject: unknown) => {
			if (!inject) return null;
			return typeof inject === 'function' ? inject() : inject;
		};

		const renderStepContent = (itemViewState: (typeof stepsState.items)[number]) => {
			const itemState = itemViewState.itemState;
			const inject = renderInject(itemState.inject);

			return (
				<div className={itemViewState.contentClass}>
					<div className={itemViewState.titleClass}>{itemState.title}</div>
					{itemState.desc && <div className={itemViewState.descClass}>{itemState.desc}</div>}
					{inject && <div>{inject}</div>}
				</div>
			);
		};

		if (vertical) {
			return (
				<div ref={setContainerRefs} className={stepsState.verticalRootClass}>
					{stepsState.items.map((itemViewState) => (
						<div
							key={itemViewState.index}
							className={itemViewState.verticalItemClass}
							ref={(node) => {
								itemRefs.current[itemViewState.index] = node;
							}}
						>
							{renderBar(itemViewState)}
							{renderStepContent(itemViewState)}
						</div>
					))}
				</div>
			);
		}

		return (
			<div ref={setContainerRefs} className={stepsState.horizontalRootClass}>
				{stepsState.items.map((itemViewState) => (
					<div key={itemViewState.index} className={itemViewState.horizontalItemClass}>
						{renderBar(itemViewState)}
						{renderStepContent(itemViewState)}
					</div>
				))}
			</div>
		);
	}
);

Steps.displayName = 'Steps';

export default Steps;

// packages/vtdf/src/lib/components/Steps.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, onUpdated, ref, watch } from 'vue';
import type { StepsProps } from '../types';
import {
	resolveStepsDerived,
	resolveStepsMeasuredClientHeights,
	resolveStepsMeasuredClientWidth,
	resolveStepsMeasuredHeightsState,
	resolveStepsMeasuredWidthState,
	resolveStepsStateOptions
} from '@any-tdf/common/derived/steps';
import Icon from './Icon.vue';

const props = withDefaults(defineProps<StepsProps>(), {
	steps: () => [],
	current: 1,
	radius: '',
	barBorder: true,
	vertical: false
});

const containerRef = ref<HTMLDivElement | null>(null);
const itemRefs = ref<(HTMLDivElement | null)[]>([]);
const width = ref(0);
const heightList = ref<number[]>([]);
let resizeObserver: ResizeObserver | null = null;

// 公共派生层处理 Steps 的数据选择、class 和布局值，DOM 测量留在组件层。
// Shared derived layer handles Steps data selection, classes and layout values; DOM measurement stays in the component layer.
const stepsState = computed(() =>
	resolveStepsDerived(
		resolveStepsStateOptions({
			props: {
				steps: props.steps,
				current: props.current,
				radius: props.radius,
				barBorder: props.barBorder,
				vertical: props.vertical
			},
			width: width.value,
			heightList: heightList.value
		})
	)
);

const measure = async () => {
	await nextTick();
	if (!props.vertical) {
		const nextWidth = resolveStepsMeasuredClientWidth(containerRef.value);
		const widthState = resolveStepsMeasuredWidthState({
			currentWidth: width.value,
			measuredWidth: nextWidth
		});
		if (widthState.shouldUpdate) {
			width.value = widthState.width;
		}
		return;
	}
	const nextHeightList = resolveStepsMeasuredClientHeights(itemRefs.value);
	const heightState = resolveStepsMeasuredHeightsState({
		currentHeights: heightList.value,
		nextHeights: nextHeightList
	});
	if (heightState.shouldUpdate) {
		heightList.value = heightState.heights;
	}
};

const setItemRef = (element: unknown, index: number) => {
	itemRefs.value[index] = element instanceof HTMLDivElement ? element : null;
};

watch(() => [props.steps.length, props.vertical], measure);

onMounted(() => {
	measure();
	resizeObserver = new ResizeObserver(() => {
		measure();
	});
	if (containerRef.value) {
		resizeObserver.observe(containerRef.value);
	}
	window.addEventListener('resize', measure);
});

onUpdated(() => {
	measure();
});

onBeforeUnmount(() => {
	resizeObserver?.disconnect();
	resizeObserver = null;
	window.removeEventListener('resize', measure);
});
</script>

<template>
	<div v-if="vertical" ref="containerRef" :class="stepsState.verticalRootClass">
		<div
			v-for="itemViewState in stepsState.items"
			:key="itemViewState.index"
			:ref="(element) => setItemRef(element, itemViewState.index)"
			:class="itemViewState.verticalItemClass"
		>
			<div :class="itemViewState.barWrapperClass">
				<div :class="itemViewState.lineClass" :style="itemViewState.lineStyle" />
				<div v-if="itemViewState.itemState.hasBar" :class="itemViewState.barClass" :style="itemViewState.barStyle">
					<template v-if="itemViewState.barContentState.kind === 'icon'">
						<div :class="itemViewState.barIconClass">
							<Icon v-bind="itemViewState.barContentState.iconProps" :size="16" />
						</div>
					</template>
					<img
						v-else-if="itemViewState.barContentState.kind === 'image'"
						:class="itemViewState.barImageClass"
						:src="itemViewState.barContentState.src"
						alt=""
					/>
					<div v-else-if="itemViewState.barContentState.kind === 'text'" :class="itemViewState.barTextClass">
						{{ itemViewState.barContentState.text }}
					</div>
				</div>
				<div v-else :class="itemViewState.barClass" :style="itemViewState.barStyle" />
			</div>
			<div :class="itemViewState.contentClass">
				<div :class="itemViewState.titleClass">
					{{ itemViewState.itemState.title }}
				</div>
				<div v-if="itemViewState.itemState.desc" :class="itemViewState.descClass">
					{{ itemViewState.itemState.desc }}
				</div>
				<component :is="itemViewState.itemState.inject" v-if="itemViewState.itemState.inject" />
			</div>
		</div>
	</div>

	<div v-else ref="containerRef" :class="stepsState.horizontalRootClass">
		<div v-for="itemViewState in stepsState.items" :key="itemViewState.index" :class="itemViewState.horizontalItemClass">
			<div :class="itemViewState.barWrapperClass">
				<div :class="itemViewState.lineClass" :style="itemViewState.lineStyle" />
				<div v-if="itemViewState.itemState.hasBar" :class="itemViewState.barClass" :style="itemViewState.barStyle">
					<template v-if="itemViewState.barContentState.kind === 'icon'">
						<div :class="itemViewState.barIconClass">
							<Icon v-bind="itemViewState.barContentState.iconProps" :size="16" />
						</div>
					</template>
					<img
						v-else-if="itemViewState.barContentState.kind === 'image'"
						:class="itemViewState.barImageClass"
						:src="itemViewState.barContentState.src"
						alt=""
					/>
					<div v-else-if="itemViewState.barContentState.kind === 'text'" :class="itemViewState.barTextClass">
						{{ itemViewState.barContentState.text }}
					</div>
				</div>
				<div v-else :class="itemViewState.barClass" :style="itemViewState.barStyle" />
			</div>
			<div :class="itemViewState.contentClass">
				<div :class="itemViewState.titleClass">
					{{ itemViewState.itemState.title }}
				</div>
				<div v-if="itemViewState.itemState.desc" :class="itemViewState.descClass">
					{{ itemViewState.itemState.desc }}
				</div>
				<component :is="itemViewState.itemState.inject" v-if="itemViewState.itemState.inject" />
			</div>
		</div>
	</div>
</template>
