// packages/rtdf/src/lib/components/switch/index.tsx
import { useState, useEffect } from 'react';
import Loading from '../loading';
import type { SwitchProps } from '../../types';
import {
	resolveSwitchActiveSyncAction,
	resolveSwitchClickAction,
	resolveSwitchDerived,
	resolveSwitchStateOptions,
	resolveSwitchStretchFlow
} from '@any-tdf/common/derived/switch';

const Switch: React.FC<SwitchProps> = ({
	active: propActive = false,
	radius = '',
	inside = null,
	injClass = '',
	disabled = false,
	async = false,
	loading = {},
	trueChild,
	falseChild,
	onChange,
	onClick
}) => {
	const [active, setActive] = useState(propActive);
	const [isLong, setIsLong] = useState(false);

	// 公共派生层只处理 Switch 的 class 字符串、滑块样式和下一状态，事件与 children 留在组件内。
	// Shared derived layer only handles Switch class strings, thumb styles and next state; events and children stay in the component.
	const switchState = resolveSwitchDerived(
		resolveSwitchStateOptions({
			props: { disabled, radius, injClass, inside },
			active,
			isLong,
			hasTrueChild: Boolean(trueChild),
			hasFalseChild: Boolean(falseChild)
		})
	);

	const setChangeFun = () => {
		// 公共动作函数只返回更新和事件触发决策，组件层负责状态写入。
		// Shared action function only returns update and event decisions; the component writes state.
		const action = resolveSwitchClickAction({ active, disabled, async });
		if (action.shouldChange) {
			setActive(action.nextActive);
			onChange?.(action.nextActive);
		}
		if (action.shouldClick) onClick?.();
	};

	useEffect(() => {
		// 公共 action 只返回是否同步内部 active，状态写入留在组件层。
		// Shared action only returns whether to sync internal active; state writes stay in the component layer.
		const action = resolveSwitchActiveSyncAction({ active: propActive, disabled });
		if (action.shouldSync) setActive(action.nextActive);
	}, [propActive, disabled]);

	useEffect(() => {
		// 公共 action 只返回拉伸反馈决策，计时器生命周期留在组件层。
		// Shared action only returns stretch feedback decisions; timer lifecycle stays in the component layer.
		const flow = resolveSwitchStretchFlow({ disabled });
		if (flow.shouldStretch) {
			setIsLong(flow.nextIsLong);
			const timer = setTimeout(() => {
				setIsLong(flow.resetNextIsLong);
			}, flow.resetDelay);
			return () => clearTimeout(timer);
		}
	}, [active, disabled]);

	const renderInside = () => {
		if (switchState.insideState.kind === 'state') {
			return (
				<>
					{switchState.insideState.active ? (
						<div className={switchState.stateTrueMarkClass} />
					) : (
						<div className={switchState.stateFalseMarkClass} />
					)}
				</>
			);
		}

		if (switchState.insideState.kind === 'loading') {
			return (
				<div className={switchState.loadingClass}>
					<Loading width="full" height="full" {...loading} />
				</div>
			);
		}

		if (switchState.insideState.kind === 'children') {
			return (
				<>
					<span className={switchState.insideState.trueClass}>{trueChild}</span>
					<span className={switchState.insideState.falseClass}>{falseChild}</span>
				</>
			);
		}

		if (switchState.insideState.kind === 'array') return switchState.insideState.value;

		return null;
	};

	return (
		<button type="button" onClick={setChangeFun} disabled={disabled} className={switchState.rootClass}>
			<div className={switchState.thumbClass} style={switchState.thumbStyle}>
				{renderInside()}
			</div>
		</button>
	);
};

export type { SwitchProps } from '../../types';
export default Switch;

// packages/vtdf/src/lib/components/Switch.vue
<script setup lang="ts">
import { computed, ref, useSlots, watch } from 'vue';
import type { SwitchProps } from '../types';
import {
	resolveSwitchActiveSyncAction,
	resolveSwitchClickAction,
	resolveSwitchDerived,
	resolveSwitchStateOptions,
	resolveSwitchStretchFlow
} from '@any-tdf/common/derived/switch';
import Loading from './Loading.vue';

const props = withDefaults(defineProps<SwitchProps & {}>(), {
	active: false,
	radius: '',
	inside: null,
	injClass: '',
	disabled: false,
	async: false,
	loading: () => ({})
});

const emit = defineEmits<{
	'update:active': [active: boolean];
	change: [active: boolean];
	click: [];
}>();

const slots = useSlots();
const active = ref(props.active);
const isLong = ref(false);

// 公共派生层只处理 Switch 的 class 字符串、滑块样式和下一状态，事件与 slot 留在组件内。
// Shared derived layer only handles Switch class strings, thumb styles and next state; events and slots stay in the component.
const switchState = computed(() =>
	resolveSwitchDerived(
		resolveSwitchStateOptions({
			props: {
				disabled: props.disabled,
				radius: props.radius,
				injClass: props.injClass,
				inside: props.inside
			},
			active: active.value,
			isLong: isLong.value,
			hasTrueChild: Boolean(slots.true),
			hasFalseChild: Boolean(slots.false)
		})
	)
);

watch(
	() => props.active,
	(nextActive) => {
		// 公共 action 只返回是否同步内部 active，状态写入留在组件层。
		// Shared action only returns whether to sync internal active; state writes stay in the component layer.
		const action = resolveSwitchActiveSyncAction({ active: nextActive, disabled: props.disabled });
		if (action.shouldSync) active.value = action.nextActive;
	}
);

watch(active, () => {
	// 公共 action 只返回拉伸反馈决策，计时器生命周期留在组件层。
	// Shared action only returns stretch feedback decisions; timer lifecycle stays in the component layer.
	const flow = resolveSwitchStretchFlow({ disabled: props.disabled });
	if (!flow.shouldStretch) return;
	isLong.value = flow.nextIsLong;
	setTimeout(() => {
		isLong.value = flow.resetNextIsLong;
	}, flow.resetDelay);
});

const setChangeFun = () => {
	// 公共动作函数只返回更新和事件触发决策，组件层负责状态写入。
	// Shared action function only returns update and event decisions; the component writes state.
	const action = resolveSwitchClickAction({
		active: active.value,
		disabled: props.disabled,
		async: props.async
	});
	if (action.shouldChange) {
		active.value = action.nextActive;
		emit('update:active', action.nextActive);
		emit('change', action.nextActive);
	}
	if (action.shouldClick) emit('click');
};
</script>

<template>
	<button type="button" :disabled="disabled" :class="switchState.rootClass" @click="setChangeFun">
		<div :class="switchState.thumbClass" :style="switchState.thumbStyle">
			<template v-if="switchState.insideState.kind === 'state'">
				<div v-if="switchState.insideState.active" :class="switchState.stateTrueMarkClass" />
				<div v-else :class="switchState.stateFalseMarkClass" />
			</template>
			<div v-else-if="switchState.insideState.kind === 'loading'" :class="switchState.loadingClass">
				<Loading width="full" height="full" v-bind="loading" />
			</div>
			<template v-else-if="switchState.insideState.kind === 'children'">
				<span :class="switchState.insideState.trueClass"><slot name="true" /></span>
				<span :class="switchState.insideState.falseClass"><slot name="false" /></span>
			</template>
			<template v-else-if="switchState.insideState.kind === 'array'">
				<span>{{ switchState.insideState.value }}</span>
			</template>
		</div>
	</button>
</template>
