// packages/stdf/src/lib/components/tabs/Tab.svelte
<script lang="ts">
	import Icon from '../icon/Icon.svelte';
	import type { TabProps } from '../../types/index.js';
	import { resolveHiddenScrollbarCss } from '@any-tdf/common/derived/helpers';
	import {
		resolveTabAutoScrollAction,
		resolveTabClickAction,
		resolveTabDerived,
		resolveTabStateOptions
	} from '@any-tdf/common/derived/tabs';

	let {
		labels = [],
		active = $bindable(0),
		lineType = false,
		radius = '',
		duration = 'base',
		layout = 'h',
		love = false,
		injClass = '',
		tabInjClass = '',
		activeTabInjClass = '',
		activeInjClass = '',
		mx = '2',
		overflow = false,
		showNum = 3,
		autoScroll = true,
		onclickTab
	}: TabProps = $props();

	const clickTabFun = (i: number) => {
		// 公共动作函数只返回 active 更新结果，组件层负责状态写入和事件触发。
		// Shared action function only returns the active update result; the component writes state and fires events.
		const action = resolveTabClickAction({ index: i });
		active = action.nextActive;
		if (action.shouldEmit) onclickTab?.(action.nextActive);
	};
	let tabW = $state(0);
	let tabH = $state(0);

	// 溢出模式下的变量
	// variables in overflow mode
	let ofTabW = $state(0);
	let ofTabH = $state(0);
	let ofDom = $state<HTMLDivElement | null>(null);
	let showIndexsOffset = $state(0);
	// 公共派生层统一 Tab 的 class、style、指标和滚动数学，DOM 测量与滚动执行留在组件层。
	// Shared derivation centralizes Tab classes, styles, metrics and scroll math; DOM reads and scroll execution stay in the component layer.
	let tabState = $derived(
		resolveTabDerived(resolveTabStateOptions({
			props: { active, activeInjClass, activeTabInjClass, duration, height: tabH, injClass, labels, layout, lineType, love, mx, overflow, overflowHeight: ofTabH, overflowWidth: ofTabW, radius, showIndexesOffset: showIndexsOffset, showNum, tabInjClass, width: tabW }
		}))
	);
	const css = resolveHiddenScrollbarCss({ selector: '.no-scrollbar' });
	// 监听 active 变化，当 active 变化时，如果 active 不在可视区域内，则滚动 ofDom，使 active 显示在中间
	// listen to the change of active, when active changes, if active is not in the visible area, scroll ofDom to make active display in the middle
	$effect(() => {
		const action = resolveTabAutoScrollAction({ autoScroll, hasScrollElement: Boolean(ofDom), showOverflow: tabState.showOverflow, scrollState: tabState.overflow.autoScrollState });
		if (action.shouldScroll && ofDom) {
			ofDom.scrollLeft = action.scrollLeft;
			if (action.shouldUpdateOffset) {
				showIndexsOffset = action.nextOffset;
			}
		}
	});
</script>

<svelte:head>
	<style>
		{css}
	</style>
</svelte:head>

{#if tabState.showOverflow}
	<div
		bind:clientWidth={ofTabW}
		bind:clientHeight={ofTabH}
		bind:this={ofDom}
		class={tabState.overflow.rootClass}
	>
		{#if tabState.overflow.lineVisible}
			<div class={tabState.lineClass} style={tabState.overflow.lineStyleString}></div>
		{/if}
		<div
			class={tabState.overflow.indicatorClass}
			style={tabState.overflow.indicatorStyleString}
		></div>
		<div class={tabState.overflow.listClass} style={tabState.overflow.listStyleString}>
			{#each tabState.items as itemState (itemState.index)}
				<button
					class={itemState.overflowButtonClass}
					style={itemState.overflowButtonStyleString}
					onclick={() => clickTabFun(itemState.index)}
				>
					{#if itemState.label.icon}
						<div class={tabState.iconClass}>
							<Icon {...itemState.label.icon} />
						</div>
					{/if}
					{#if itemState.label.text}
						<div class={tabState.textClass}>{itemState.label.text}</div>
					{/if}
				</button>
			{/each}
		</div>
	</div>
{:else}
	<div
		bind:clientWidth={tabW}
		bind:clientHeight={tabH}
		class={tabState.normal.rootClass}
	>
		{#if tabState.normal.lineVisible}
			<div class={tabState.lineClass} style={tabState.normal.lineStyleString}></div>
		{/if}
		<div
			class={tabState.normal.indicatorClass}
			style={tabState.normal.indicatorStyleString}
		></div>
		<div class={tabState.normal.listClass}>
			{#each tabState.items as itemState (itemState.index)}
				<button
					class={itemState.buttonClass}
					onclick={() => clickTabFun(itemState.index)}
				>
					{#if itemState.label.icon}
						<div class={tabState.iconClass}>
							<Icon {...itemState.label.icon} />
						</div>
					{/if}
					{#if itemState.label.text}
						<div class={tabState.textClass}>{itemState.label.text}</div>
					{/if}
				</button>
			{/each}
		</div>
	</div>
{/if}

// packages/vtdf/src/lib/components/Tab.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { TabProps } from '../types';
import { resolveHiddenScrollbarCss } from '@any-tdf/common/derived/helpers';
import {
	resolveTabAutoScrollAction,
	resolveTabClickAction,
	resolveTabDerived,
	resolveTabMeasuredSizeState,
	resolveTabStateOptions
} from '@any-tdf/common/derived/tabs';
import Icon from './Icon.vue';

const props = withDefaults(defineProps<TabProps & {}>(), {
	labels: () => [],
	active: 0,
	lineType: false,
	radius: '',
	duration: 'base',
	layout: 'h',
	love: false,
	injClass: '',
	tabInjClass: '',
	activeTabInjClass: '',
	activeInjClass: '',
	mx: '2',
	overflow: false,
	showNum: 3,
	autoScroll: true
});

const emit = defineEmits<{
	'update:active': [active: number];
	clickTab: [active: number];
}>();

const tabDom = ref<HTMLDivElement | null>(null);
const overflowDom = ref<HTMLDivElement | null>(null);
const tabW = ref(0);
const tabH = ref(0);
const ofTabW = ref(0);
const ofTabH = ref(0);
const showIndexsOffset = ref(0);
let resizeObserver: ResizeObserver | null = null;

// 公共派生层统一 Tab 的 class、style、指标和滚动数学，DOM 测量与滚动执行留在组件层。
// Shared derivation centralizes Tab classes, styles, metrics and scroll math; DOM reads and scroll execution stay in the component layer.
const tabState = computed(() =>
	resolveTabDerived(
		resolveTabStateOptions({
			props: {
				...props,
				height: tabH.value,
				overflowHeight: ofTabH.value,
				overflowWidth: ofTabW.value,
				showIndexesOffset: showIndexsOffset.value,
				width: tabW.value
			}
		})
	)
);
const css = resolveHiddenScrollbarCss({ selector: '.no-scrollbar' });

const clickTabFun = (index: number) => {
	// 公共动作函数只返回 active 更新结果，组件层负责状态写入和事件触发。
	// Shared action function only returns the active update result; the component writes state and fires events.
	const action = resolveTabClickAction({ index });
	emit('update:active', action.nextActive);
	if (action.shouldEmit) emit('clickTab', action.nextActive);
};

const updateSize = () => {
	// 公共测量函数只处理数值状态，DOM 读取仍留在组件层。
	// Shared measurement helper only handles numeric state; DOM reads stay in the component layer.
	const measuredState = resolveTabMeasuredSizeState({
		current: {
			tabWidth: tabW.value,
			tabHeight: tabH.value,
			overflowWidth: ofTabW.value,
			overflowHeight: ofTabH.value
		},
		tabRect: tabDom.value?.getBoundingClientRect(),
		overflowRect: overflowDom.value?.getBoundingClientRect()
	});
	tabW.value = measuredState.tabWidth;
	tabH.value = measuredState.tabHeight;
	ofTabW.value = measuredState.overflowWidth;
	ofTabH.value = measuredState.overflowHeight;
};

watch(
	() => [tabState.value.activeIndex, props.autoScroll, tabState.value.showOverflow, tabState.value.overflow.itemW] as const,
	() => {
		const action = resolveTabAutoScrollAction({
			autoScroll: props.autoScroll,
			hasScrollElement: Boolean(overflowDom.value),
			showOverflow: tabState.value.showOverflow,
			scrollState: tabState.value.overflow.autoScrollState
		});
		if (action.shouldScroll && overflowDom.value) {
			overflowDom.value.scrollLeft = action.scrollLeft;
			if (action.shouldUpdateOffset) {
				showIndexsOffset.value = action.nextOffset;
			}
		}
	}
);

onMounted(() => {
	nextTick(updateSize);
	resizeObserver = new ResizeObserver(updateSize);
	if (tabDom.value) {
		resizeObserver.observe(tabDom.value);
	}
	if (overflowDom.value) {
		resizeObserver.observe(overflowDom.value);
	}
});

onBeforeUnmount(() => {
	resizeObserver?.disconnect();
	resizeObserver = null;
});
</script>

<template>
	<component :is="'style'" v-html="css" />
	<div v-if="tabState.showOverflow" ref="overflowDom" :class="tabState.overflow.rootClass">
		<div v-if="tabState.overflow.lineVisible" :class="tabState.lineClass" :style="tabState.overflow.lineStyleValue" />
		<div :class="tabState.overflow.indicatorClass" :style="tabState.overflow.indicatorStyleValue" />
		<div :class="tabState.overflow.listClass" :style="tabState.overflow.listStyleValue">
			<button
				v-for="itemState in tabState.items"
				:key="itemState.index"
				type="button"
				:class="itemState.overflowButtonClass"
				:style="itemState.overflowButtonStyleValue"
				@click="clickTabFun(itemState.index)"
			>
				<div v-if="itemState.label.icon" :class="tabState.iconClass">
					<Icon v-bind="itemState.label.icon" />
				</div>
				<div v-if="itemState.label.text" :class="tabState.textClass">
					{{ itemState.label.text }}
				</div>
			</button>
		</div>
	</div>

	<div v-else ref="tabDom" :class="tabState.normal.rootClass">
		<div v-if="tabState.normal.lineVisible" :class="tabState.lineClass" :style="tabState.normal.lineStyleValue" />
		<div :class="tabState.normal.indicatorClass" :style="tabState.normal.indicatorStyleValue" />
		<div :class="tabState.normal.listClass">
			<button
				v-for="itemState in tabState.items"
				:key="itemState.index"
				type="button"
				:class="itemState.buttonClass"
				@click="clickTabFun(itemState.index)"
			>
				<div v-if="itemState.label.icon" :class="tabState.iconClass">
					<Icon v-bind="itemState.label.icon" />
				</div>
				<div v-if="itemState.label.text" :class="tabState.textClass">
					{{ itemState.label.text }}
				</div>
			</button>
		</div>
	</div>
</template>
