// apps/rtdf-site/src/components/Tabs.tsx
import { useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Tabs as RtdfTabs } from 'rtdf/components';
import { encodeData, rendererLine } from 'beautify-qrcode';
import { useAppContext } from '../store/appStore';

type TabsProps = {
	currentTab?: number;
	onChange?: (index: number) => void;
};

const tabList = [
	{ zh: '示例', en: 'Demo' },
	{ zh: 'API', en: 'API' },
	{ zh: '指南', en: 'Guide' },
	{ zh: 'FAQ', en: 'FAQ' },
	{ zh: '版本', en: 'Version' }
];

const sourceExtMap: Record<string, 'ts' | 'tsx'> = {
	calendar: 'ts',
	feedback: 'ts',
	grids: 'ts',
	numKeyboard: 'ts',
	placeholder: 'ts',
	skeleton: 'ts',
	timePicker: 'ts'
};

const Tabs = ({ currentTab = 0, onChange }: TabsProps) => {
	const location = useLocation();
	const { lang, themeMode, sysTheme } = useAppContext();
	const isZh = lang === 'zh_CN';
	const tabLabels = tabList.map((item) => ({ text: isZh ? item.zh : item.en }));

	const nav = new URLSearchParams(location.search).get('nav') ?? 'button';
	const demoBaseUrl = import.meta.env.DEV ? `${window.location.protocol}//${window.location.hostname}:8887/` : 'https://demo.rtdf.dev/';
	const demoUrl = `${demoBaseUrl}${nav}/${isZh ? 'zh_CN' : 'en_US'}`;
	const sourceExt = sourceExtMap[nav] || 'tsx';
	const sourceUrl = `https://github.com/any-tdf/any-tdf/blob/main/packages/rtdf/src/lib/components/${nav}/index.${sourceExt}`;
	const stackblitzUrl = `https://stackblitz.com/github/any-tdf/any-tdf?file=apps%2Frtdf-demo%2Fsrc%2Fpages%2F${nav}%2F${isZh ? 'zh_CN' : 'en_US'}.tsx&startScript=dev%3Artdf`;

	const [previewQrOpen, setPreviewQrOpen] = useState(false);
	const [previewQrSvg, setPreviewQrSvg] = useState('');

	const resolvedMode = themeMode === 'auto' ? sysTheme : themeMode;

	const openPreviewQr = () => {
		const qrcode = encodeData({ text: demoUrl, isSpace: false });
		const color = resolvedMode === 'dark' ? 'var(--color-dark)' : 'var(--color-primary)';
		setPreviewQrSvg(rendererLine(qrcode, { posType: 2, otherColor: color, posColor: color }));
		setPreviewQrOpen(true);
	};

	const selectTab = (index: number) => {
		onChange?.(index);
	};

	return (
		<div className="tab-shell">
			<div className="tab-control" role="group" aria-label={isZh ? '组件文档类型' : 'Component documentation type'}>
				<RtdfTabs
					active={currentTab}
					transition={false}
					onChange={selectTab}
					tab={{
						labels: tabLabels,
						mx: '0',
						radius: 'sm',
						injClass: 'component-doc-tabs',
						tabInjClass: 'component-doc-tab',
						activeTabInjClass: 'component-doc-tab-active'
					}}
				/>
			</div>
			<div className="tab-tools">
				<a href={demoUrl} target="_blank" rel="noreferrer">
					Demo ↗
				</a>
				<a href={sourceUrl} target="_blank" rel="noreferrer">
					Source ↗
				</a>
				<a href={stackblitzUrl} target="_blank" rel="noreferrer">
					StackBlitz ↗
				</a>
				<div
					className="tab-preview-action"
					onMouseEnter={openPreviewQr}
					onMouseLeave={() => setPreviewQrOpen(false)}
					onFocus={openPreviewQr}
					onBlur={() => setPreviewQrOpen(false)}
				>
					<a href={demoUrl} target="_blank" rel="noreferrer">
						{isZh ? '移动端预览' : 'Mobile preview'} ↗
					</a>
					{previewQrOpen ? (
						<div className="tab-preview-qr">
							<div className="tab-preview-qr-code" dangerouslySetInnerHTML={{ __html: previewQrSvg }}></div>
							<div>{isZh ? '扫码打开移动端预览' : 'Scan to open mobile preview'}</div>
						</div>
					) : null}
				</div>
			</div>
		</div>
	);
};

export default Tabs;

// apps/vtdf-site/src/components/Tabs.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { Tabs } from 'vtdf/components';
import { appState } from '../store/appStore';
import { encodeData, rendererLine } from 'beautify-qrcode';

const props = withDefaults(
	defineProps<{
		currentTab?: number;
	}>(),
	{
		currentTab: 0
	}
);

const emit = defineEmits<{
	change: [index: number];
}>();

const isZh = computed(() => appState.lang === 'zh_CN');
const tabList = [
	{ zh: '示例', en: 'Demo' },
	{ zh: 'API', en: 'API' },
	{ zh: '指南', en: 'Guide' },
	{ zh: 'FAQ', en: 'FAQ' },
	{ zh: '版本', en: 'Version' }
];
const tabLabels = computed(() => tabList.map((item) => ({ text: isZh.value ? item.zh : item.en })));

const nav = computed(() => new URLSearchParams(appState.search).get('nav') ?? 'button');
const navClassName = computed(() => nav.value.slice(0, 1).toUpperCase() + nav.value.slice(1));
const demoBaseUrl = computed(() => (import.meta.env.DEV ? `${location.protocol}//${location.hostname}:8886/` : 'https://demo.vtdf.dev/'));
const demoUrl = computed(() => `${demoBaseUrl.value}${nav.value}/${isZh.value ? 'zh_CN' : 'en_US'}`);
const sourceUrl = computed(
	() => `https://github.com/any-tdf/any-tdf/blob/main/packages/vtdf/src/lib/components/${nav.value}/${navClassName.value}.vue`
);
const stackblitzUrl = computed(
	() =>
		`https://stackblitz.com/github/any-tdf/any-tdf?file=apps%2Fvtdf-demo%2Fsrc%2Fpages%2F${nav.value}%2F${isZh.value ? 'zh_CN' : 'en_US'}.vue&startScript=dev%3Avtdf`
);
const previewQrOpen = ref(false);
const previewQrSvg = ref('');

const openPreviewQr = () => {
	const qrcode = encodeData({ text: demoUrl.value, isSpace: false });
	const color = appState.currentThemeMode === 'dark' ? 'var(--color-dark)' : 'var(--color-primary)';
	previewQrSvg.value = rendererLine(qrcode, {
		posType: 2,
		otherColor: color,
		posColor: color
	});
	previewQrOpen.value = true;
};

const selectTab = (index: number) => {
	emit('change', index);
};
</script>

<template>
	<div class="tab-shell">
		<div class="tab-control" role="group" :aria-label="isZh ? '组件文档类型' : 'Component documentation type'">
			<Tabs
				:active="props.currentTab"
				:transition="false"
				:tab="{
					labels: tabLabels,
					mx: '0',
					radius: 'sm',
					injClass: 'component-doc-tabs',
					tabInjClass: 'component-doc-tab',
					activeTabInjClass: 'component-doc-tab-active'
				}"
				@change="selectTab"
			/>
		</div>
		<div class="tab-tools">
			<a :href="demoUrl" target="_blank" rel="noreferrer">Demo ↗</a>
			<a :href="sourceUrl" target="_blank" rel="noreferrer">Source ↗</a>
			<a :href="stackblitzUrl" target="_blank" rel="noreferrer">StackBlitz ↗</a>
			<div
				class="tab-preview-action"
				@mouseenter="openPreviewQr"
				@mouseleave="previewQrOpen = false"
				@focusin="openPreviewQr"
				@focusout="previewQrOpen = false"
			>
				<a :href="demoUrl" target="_blank" rel="noreferrer">{{ isZh ? '移动端预览' : 'Mobile preview' }} ↗</a>
				<div v-if="previewQrOpen" class="tab-preview-qr">
					<div class="tab-preview-qr-code" v-html="previewQrSvg"></div>
					<div>{{ isZh ? '扫码打开移动端预览' : 'Scan to open mobile preview' }}</div>
				</div>
			</div>
		</div>
	</div>
</template>
