// packages/vue-motion/docs/src/App.vue
<script setup lang="ts">
import {
	Activity,
	Atom,
	BookOpen,
	ChartNoAxesCombined,
	Code2,
	Package,
	Rocket,
	Sparkles,
	TableProperties,
	type LucideIcon
} from 'lucide-vue-next';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import InlineText from './components/InlineText.vue';
import {
	apiContent,
	defaultLocale,
	demoContent,
	homeContent,
	locales,
	navItems,
	pageKeys,
	quickStartContent,
	uiText,
	type Locale,
	type PageKey
} from './content';
import EasingVisualiser from './demos/EasingVisualiser.vue';

type Route = {
	locale: Locale;
	page: PageKey;
};
type ThemeMode = 'auto' | 'light' | 'dark';
type ResolvedTheme = Exclude<ThemeMode, 'auto'>;

const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
const isPageKey = (value: string): value is PageKey => pageKeys.includes(value as PageKey);
const themeModes: ThemeMode[] = ['auto', 'light', 'dark'];
const themeStorageKey = 'vue-motion-theme';
const actionIcons: Partial<Record<PageKey, LucideIcon>> = {
	'quick-start': Rocket,
	'demo/easing': ChartNoAxesCombined
};
const featureIcons = [Sparkles, Code2, Activity] as const;
const exampleIcons = [Sparkles, Package, Activity] as const;

const isThemeMode = (value: string): value is ThemeMode => themeModes.includes(value as ThemeMode);
const parseRoute = (pathname: string): Route => {
	const parts = pathname.split('/').filter(Boolean);
	const locale = isLocale(parts[0]) ? parts[0] : defaultLocale;
	const pagePath = parts.slice(isLocale(parts[0]) ? 1 : 0).join('/') || 'home';
	return { locale, page: isPageKey(pagePath) ? pagePath : 'home' };
};
const hrefFor = (locale: Locale, page: PageKey) => `/${locale}${page === 'home' ? '' : `/${page}`}`;
const getSystemTheme = (): ResolvedTheme => (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
const getInitialThemeMode = (): ThemeMode => {
	const stored = window.localStorage.getItem(themeStorageKey);
	return stored && isThemeMode(stored) ? stored : 'auto';
};

const route = ref<Route>(parseRoute(window.location.pathname));
const themeMode = ref<ThemeMode>(getInitialThemeMode());
const labels = computed(() => uiText[route.value.locale]);
const home = computed(() => homeContent[route.value.locale]);
const quickStart = computed(() => quickStartContent[route.value.locale]);
const api = computed(() => apiContent[route.value.locale]);
const demo = computed(() => demoContent[route.value.locale]);
const otherLocale = computed<Locale>(() => (route.value.locale === 'zh' ? 'en' : 'zh'));

const navigate = (locale: Locale, page: PageKey) => {
	const href = hrefFor(locale, page);
	window.history.pushState(null, '', href);
	route.value = { locale, page };
};

const syncRoute = () => {
	route.value = parseRoute(window.location.pathname);
};
const media = window.matchMedia('(prefers-color-scheme: dark)');
const applyTheme = () => {
	const resolved = themeMode.value === 'auto' ? getSystemTheme() : themeMode.value;
	document.documentElement.dataset.theme = resolved;
	document.documentElement.dataset.themeMode = themeMode.value;
	document.documentElement.style.colorScheme = resolved;
	window.localStorage.setItem(themeStorageKey, themeMode.value);
};
const handleSystemThemeChange = () => {
	if (themeMode.value === 'auto') applyTheme();
};

watch(themeMode, applyTheme, { immediate: true });
watch(
	() => [route.value.locale, route.value.page] as const,
	() => {
		const currentHref = hrefFor(route.value.locale, route.value.page);
		if (window.location.pathname !== currentHref) window.history.replaceState(null, '', currentHref);
		document.documentElement.lang = route.value.locale === 'zh' ? 'zh-CN' : 'en';
		const pageLabel = navItems[route.value.locale].find((item) => item.key === route.value.page)?.label;
		document.title = `${labels.value.brand} - ${pageLabel ?? labels.value.brand}`;
	},
	{ immediate: true }
);

onMounted(() => {
	window.addEventListener('popstate', syncRoute);
	media.addEventListener('change', handleSystemThemeChange);
});
onBeforeUnmount(() => {
	window.removeEventListener('popstate', syncRoute);
	media.removeEventListener('change', handleSystemThemeChange);
});
</script>

<template>
	<div class="site-shell">
		<header class="site-header">
			<a class="brand" :href="hrefFor(route.locale, 'home')" @click.prevent="navigate(route.locale, 'home')">
				<span class="brand-mark" aria-hidden="true"><Atom :size="20" :stroke-width="2.2" /></span>
				<span class="brand-copy">
					<strong>{{ labels.brand }}</strong>
					<small>{{ labels.tagline }}</small>
				</span>
			</a>

			<nav class="main-nav" aria-label="Primary">
				<a
					v-for="item in navItems[route.locale]"
					:key="item.key"
					:class="{ active: item.key === route.page }"
					:href="hrefFor(route.locale, item.key)"
					@click.prevent="navigate(route.locale, item.key)"
				>
					{{ item.label }}
				</a>
			</nav>

			<div class="header-actions">
				<label class="theme-control">
					<span>{{ labels.theme }}</span>
					<select v-model="themeMode" :aria-label="labels.theme">
						<option v-for="mode in themeModes" :key="mode" :value="mode">{{ labels.themeOptions[mode] }}</option>
					</select>
				</label>
				<a class="language-link" :href="hrefFor(otherLocale, route.page)" @click.prevent="navigate(otherLocale, route.page)">
					{{ labels.language }}
				</a>
			</div>
		</header>

		<main v-if="route.page === 'home'" class="page-content">
			<section class="hero-section">
				<div class="hero-copy">
					<p class="eyebrow">@any-tdf/vue-motion</p>
					<h1>{{ home.title }}</h1>
					<p>{{ home.description }}</p>
					<div class="action-row">
						<a
							v-for="action in home.actions"
							:key="action.key"
							:href="hrefFor(route.locale, action.key)"
							@click.prevent="navigate(route.locale, action.key)"
						>
							<component
								:is="actionIcons[action.key]"
								v-if="actionIcons[action.key]"
								class="button-icon"
								:size="17"
								:stroke-width="2.2"
								aria-hidden="true"
							/>
							<span>{{ action.label }}</span>
						</a>
					</div>
				</div>
				<div class="curve-preview" aria-hidden="true">
					<svg viewBox="0 0 320 220">
						<path d="M22 180 C60 170 82 160 112 118 S180 20 226 78 275 176 298 42" />
						<circle cx="226" cy="78" r="8" />
					</svg>
				</div>
			</section>

			<section class="feature-grid" aria-label="Features">
				<article v-for="(feature, index) in home.features" :key="feature.title" class="feature-card">
					<span class="feature-icon" aria-hidden="true">
						<component :is="featureIcons[index] ?? Sparkles" :size="21" :stroke-width="2.1" />
					</span>
					<h2>{{ feature.title }}</h2>
					<p><InlineText :text="feature.text" /></p>
				</article>
			</section>
		</main>

		<main v-else-if="route.page === 'quick-start'" class="page-content narrow">
			<section class="doc-section">
				<div class="section-heading">
					<BookOpen class="section-icon" :size="28" :stroke-width="2.1" aria-hidden="true" />
					<h1>{{ quickStart.title }}</h1>
				</div>
				<p><InlineText :text="quickStart.intro" /></p>
			</section>

			<section class="doc-section">
				<h2 class="icon-heading">
					<Package class="heading-icon" :size="20" :stroke-width="2.1" aria-hidden="true" />
					<span>{{ labels.install }}</span>
				</h2>
				<pre><code>{{ quickStart.install }}</code></pre>
			</section>

			<section class="doc-section">
				<h2 class="icon-heading">
					<Code2 class="heading-icon" :size="20" :stroke-width="2.1" aria-hidden="true" />
					<span>{{ labels.imports }}</span>
				</h2>
				<div class="example-list">
					<article v-for="(example, index) in quickStart.examples" :key="example.title" class="example-block">
						<h3 class="example-title">
							<component :is="exampleIcons[index] ?? Code2" class="heading-icon" :size="18" :stroke-width="2.1" />
							<span>{{ example.title }}</span>
						</h3>
						<pre><code>{{ example.code }}</code></pre>
					</article>
				</div>
			</section>
		</main>

		<main v-else-if="route.page === 'api'" class="page-content narrow">
			<section class="doc-section">
				<div class="section-heading">
					<TableProperties class="section-icon" :size="28" :stroke-width="2.1" aria-hidden="true" />
					<h1>{{ api.title }}</h1>
				</div>
				<p><InlineText :text="api.intro" /></p>
			</section>

			<section class="doc-section">
				<div class="api-table-wrap">
					<table class="api-table">
						<thead>
							<tr>
								<th>Svelte</th>
								<th>Vue Motion</th>
								<th>Import</th>
							</tr>
						</thead>
						<tbody>
							<tr v-for="row in api.rows" :key="row[0]">
								<td>
									<code>{{ row[0] }}</code>
								</td>
								<td>{{ row[1] }}</td>
								<td>
									<code>{{ row[2] }}</code>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</section>

			<section class="doc-section">
				<ul class="note-list">
					<li v-for="note in api.notes" :key="note"><InlineText :text="note" /></li>
				</ul>
			</section>
		</main>

		<main v-else class="page-content demo-page">
			<section class="doc-section">
				<div class="section-heading compact-heading">
					<ChartNoAxesCombined class="section-icon" :size="24" :stroke-width="2.1" aria-hidden="true" />
					<h1>{{ demo.title }}</h1>
				</div>
				<p><InlineText :text="demo.intro" /></p>
			</section>
			<EasingVisualiser :locale="route.locale" />
		</main>
	</div>
</template>

// packages/react-motion/docs/src/App.tsx
import { useEffect, useMemo, useState } from 'react';
import Activity from 'lucide-react/dist/esm/icons/activity.mjs';
import Atom from 'lucide-react/dist/esm/icons/atom.mjs';
import BookOpen from 'lucide-react/dist/esm/icons/book-open.mjs';
import ChartNoAxesCombined from 'lucide-react/dist/esm/icons/chart-no-axes-combined.mjs';
import Code2 from 'lucide-react/dist/esm/icons/code-2.mjs';
import Package from 'lucide-react/dist/esm/icons/package.mjs';
import Rocket from 'lucide-react/dist/esm/icons/rocket.mjs';
import Sparkles from 'lucide-react/dist/esm/icons/sparkles.mjs';
import TableProperties from 'lucide-react/dist/esm/icons/table-properties.mjs';
import type { LucideIcon } from 'lucide-react';
import { EasingVisualiser } from './demos/EasingVisualiser';
import {
	apiContent,
	defaultLocale,
	demoContent,
	homeContent,
	locales,
	navItems,
	pageKeys,
	quickStartContent,
	uiText,
	type Locale,
	type PageKey
} from './content';

type Route = {
	locale: Locale;
	page: PageKey;
};
type ThemeMode = 'auto' | 'light' | 'dark';
type ResolvedTheme = Exclude<ThemeMode, 'auto'>;
type ThemeState = {
	mode: ThemeMode;
	resolved: ResolvedTheme;
};

const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
const isPageKey = (value: string): value is PageKey => pageKeys.includes(value as PageKey);
const themeModes: ThemeMode[] = ['auto', 'light', 'dark'];
const themeStorageKey = 'react-motion-theme';
const actionIcons: Partial<Record<PageKey, LucideIcon>> = {
	'quick-start': Rocket,
	'demo/easing': ChartNoAxesCombined
};
const featureIcons = [Sparkles, Code2, Activity] as const;
const exampleIcons = [Sparkles, Package, Activity] as const;

const isThemeMode = (value: string): value is ThemeMode => themeModes.includes(value as ThemeMode);

const parseRoute = (pathname: string): Route => {
	const parts = pathname.split('/').filter(Boolean);
	const locale = isLocale(parts[0]) ? parts[0] : defaultLocale;
	const pagePath = parts.slice(isLocale(parts[0]) ? 1 : 0).join('/') || 'home';
	const page = isPageKey(pagePath) ? pagePath : 'home';
	return { locale, page };
};

const hrefFor = (locale: Locale, page: PageKey) => `/${locale}${page === 'home' ? '' : `/${page}`}`;
const getSystemTheme = (): ResolvedTheme => (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
const getInitialThemeState = (): ThemeState => {
	const stored = window.localStorage.getItem(themeStorageKey);
	const mode = stored && isThemeMode(stored) ? stored : 'auto';
	return {
		mode,
		resolved: mode === 'auto' ? getSystemTheme() : mode
	};
};

const App = () => {
	const [route, setRoute] = useState<Route>(() => parseRoute(window.location.pathname));
	const [theme, setTheme] = useState<ThemeState>(getInitialThemeState);
	const labels = uiText[route.locale];
	const otherLocale: Locale = route.locale === 'zh' ? 'en' : 'zh';
	const currentHref = hrefFor(route.locale, route.page);

	useEffect(() => {
		if (window.location.pathname !== currentHref) {
			window.history.replaceState(null, '', currentHref);
		}

		const syncRoute = () => setRoute(parseRoute(window.location.pathname));
		window.addEventListener('popstate', syncRoute);
		return () => window.removeEventListener('popstate', syncRoute);
	}, [currentHref]);

	useEffect(() => {
		const media = window.matchMedia('(prefers-color-scheme: dark)');
		const applyTheme = () => {
			const resolved: ResolvedTheme = theme.mode === 'auto' ? (media.matches ? 'dark' : 'light') : theme.mode;
			document.documentElement.dataset.theme = resolved;
			document.documentElement.dataset.themeMode = theme.mode;
			document.documentElement.style.colorScheme = resolved;
			window.localStorage.setItem(themeStorageKey, theme.mode);
			setTheme((currentTheme) => (currentTheme.resolved === resolved ? currentTheme : { ...currentTheme, resolved }));
		};

		applyTheme();

		if (theme.mode !== 'auto') return;
		media.addEventListener('change', applyTheme);
		return () => media.removeEventListener('change', applyTheme);
	}, [theme.mode]);

	useEffect(() => {
		document.documentElement.lang = route.locale === 'zh' ? 'zh-CN' : 'en';
		document.title = `${labels.brand} - ${navItems[route.locale].find((item) => item.key === route.page)?.label ?? labels.brand}`;
	}, [labels.brand, route.locale, route.page]);

	const navigate = (locale: Locale, page: PageKey) => {
		const nextHref = hrefFor(locale, page);
		window.history.pushState(null, '', nextHref);
		setRoute({ locale, page });
	};

	const page = useMemo(() => {
		if (route.page === 'quick-start') return <QuickStart locale={route.locale} />;
		if (route.page === 'api') return <ApiPage locale={route.locale} />;
		if (route.page === 'demo/easing') return <DemoPage locale={route.locale} />;
		return <HomePage locale={route.locale} navigate={navigate} />;
	}, [route.locale, route.page]);

	return (
		<div className="site-shell">
			<header className="site-header">
				<a
					className="brand"
					href={hrefFor(route.locale, 'home')}
					onClick={(event) => handleLinkClick(event, () => navigate(route.locale, 'home'))}
				>
					<span className="brand-mark" aria-hidden="true">
						<Atom size={20} strokeWidth={2.2} />
					</span>
					<span className="brand-copy">
						<strong>{labels.brand}</strong>
						<small>{labels.tagline}</small>
					</span>
				</a>

				<nav className="main-nav" aria-label="Primary">
					{navItems[route.locale].map((item) => (
						<a
							key={item.key}
							className={item.key === route.page ? 'active' : ''}
							href={hrefFor(route.locale, item.key)}
							onClick={(event) => handleLinkClick(event, () => navigate(route.locale, item.key))}
						>
							{item.label}
						</a>
					))}
				</nav>

				<div className="header-actions">
					<label className="theme-control">
						<span>{labels.theme}</span>
						<select
							value={theme.mode}
							aria-label={labels.theme}
							onChange={(event) => setTheme({ mode: event.currentTarget.value as ThemeMode, resolved: theme.resolved })}
						>
							{themeModes.map((mode) => (
								<option key={mode} value={mode}>
									{labels.themeOptions[mode]}
								</option>
							))}
						</select>
					</label>
					<a
						className="language-link"
						href={hrefFor(otherLocale, route.page)}
						onClick={(event) => handleLinkClick(event, () => navigate(otherLocale, route.page))}
					>
						{labels.language}
					</a>
				</div>
			</header>

			{page}
		</div>
	);
};

const handleLinkClick = (event: React.MouseEvent<HTMLAnchorElement>, navigate: () => void) => {
	event.preventDefault();
	navigate();
};

const InlineCode = ({ text }: { text: string }) => <code>{text}</code>;

const HomePage = ({ locale, navigate }: { locale: Locale; navigate: (locale: Locale, page: PageKey) => void }) => {
	const content = homeContent[locale];

	return (
		<main className="page-content">
			<section className="hero-section">
				<div className="hero-copy">
					<p className="eyebrow">@any-tdf/react-motion</p>
					<h1>{content.title}</h1>
					<p>{content.description}</p>
					<div className="action-row">
						{content.actions.map((action) => {
							const ActionIcon = actionIcons[action.key];
							return (
								<a
									key={action.key}
									href={hrefFor(locale, action.key)}
									onClick={(event) => handleLinkClick(event, () => navigate(locale, action.key))}
								>
									{ActionIcon ? <ActionIcon className="button-icon" size={17} strokeWidth={2.2} aria-hidden="true" /> : null}
									<span>{action.label}</span>
								</a>
							);
						})}
					</div>
				</div>
				<div className="curve-preview" aria-hidden="true">
					<svg viewBox="0 0 320 220">
						<path d="M22 180 C60 170 82 160 112 118 S180 20 226 78 275 176 298 42" />
						<circle cx="226" cy="78" r="8" />
					</svg>
				</div>
			</section>

			<section className="feature-grid" aria-label="Features">
				{content.features.map((feature, index) => {
					const FeatureIcon = featureIcons[index] ?? Sparkles;
					return (
						<article key={feature.title} className="feature-card">
							<span className="feature-icon" aria-hidden="true">
								<FeatureIcon size={21} strokeWidth={2.1} />
							</span>
							<h2>{feature.title}</h2>
							<p>{renderInlineCode(feature.text)}</p>
						</article>
					);
				})}
			</section>
		</main>
	);
};

const QuickStart = ({ locale }: { locale: Locale }) => {
	const content = quickStartContent[locale];
	const labels = uiText[locale];

	return (
		<main className="page-content narrow">
			<section className="doc-section">
				<div className="section-heading">
					<BookOpen className="section-icon" size={28} strokeWidth={2.1} aria-hidden="true" />
					<h1>{content.title}</h1>
				</div>
				<p>{renderInlineCode(content.intro)}</p>
			</section>

			<section className="doc-section">
				<h2 className="icon-heading">
					<Package className="heading-icon" size={20} strokeWidth={2.1} aria-hidden="true" />
					<span>{labels.install}</span>
				</h2>
				<pre>
					<code>{content.install}</code>
				</pre>
			</section>

			<section className="doc-section">
				<h2 className="icon-heading">
					<Code2 className="heading-icon" size={20} strokeWidth={2.1} aria-hidden="true" />
					<span>{labels.imports}</span>
				</h2>
				<div className="example-list">
					{content.examples.map((example, index) => {
						const ExampleIcon = exampleIcons[index] ?? Code2;
						return (
							<article key={example.title} className="example-block">
								<h3 className="example-title">
									<ExampleIcon className="heading-icon" size={18} strokeWidth={2.1} aria-hidden="true" />
									<span>{example.title}</span>
								</h3>
								<pre>
									<code>{example.code}</code>
								</pre>
							</article>
						);
					})}
				</div>
			</section>
		</main>
	);
};

const ApiPage = ({ locale }: { locale: Locale }) => {
	const content = apiContent[locale];

	return (
		<main className="page-content narrow">
			<section className="doc-section">
				<div className="section-heading">
					<TableProperties className="section-icon" size={28} strokeWidth={2.1} aria-hidden="true" />
					<h1>{content.title}</h1>
				</div>
				<p>{renderInlineCode(content.intro)}</p>
			</section>

			<section className="doc-section">
				<div className="api-table-wrap">
					<table className="api-table">
						<thead>
							<tr>
								<th>Svelte</th>
								<th>React Motion</th>
								<th>Import</th>
							</tr>
						</thead>
						<tbody>
							{content.rows.map((row) => (
								<tr key={row[0]}>
									<td>
										<InlineCode text={row[0]} />
									</td>
									<td>{row[1]}</td>
									<td>
										<InlineCode text={row[2]} />
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			</section>

			<section className="doc-section">
				<ul className="note-list">
					{content.notes.map((note) => (
						<li key={note}>{renderInlineCode(note)}</li>
					))}
				</ul>
			</section>
		</main>
	);
};

const DemoPage = ({ locale }: { locale: Locale }) => {
	const content = demoContent[locale];

	return (
		<main className="page-content demo-page">
			<section className="doc-section">
				<div className="section-heading compact-heading">
					<ChartNoAxesCombined className="section-icon" size={24} strokeWidth={2.1} aria-hidden="true" />
					<h1>{content.title}</h1>
				</div>
				<p>{renderInlineCode(content.intro)}</p>
			</section>
			<EasingVisualiser locale={locale} />
		</main>
	);
};

const renderInlineCode = (text: string) => {
	const parts = text.split(/(`[^`]+`)/g);
	return parts.map((part, index) => {
		if (part.startsWith('`') && part.endsWith('`')) {
			return <code key={`${part}-${index}`}>{part.slice(1, -1)}</code>;
		}
		return part;
	});
};

export default App;
